/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.Cas_2024Record;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cas_2024 extends TableImpl<Cas_2024Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.cas_2024</code>
     */
    public static final Cas_2024 CAS_2024 = new Cas_2024();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Cas_2024Record> getRecordType() {
        return Cas_2024Record.class;
    }

    /**
     * The column <code>decreti.cas_2024.id</code>.
     */
    public final TableField<Cas_2024Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.cas_2024.cognome</code>.
     */
    public final TableField<Cas_2024Record, String> COGNOME = createField(DSL.name("cognome"), SQLDataType.VARCHAR(29).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.cas_2024.nome</code>.
     */
    public final TableField<Cas_2024Record, String> NOME = createField(DSL.name("nome"), SQLDataType.VARCHAR(28).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.cas_2024.cf</code>.
     */
    public final TableField<Cas_2024Record, String> CF = createField(DSL.name("cf"), SQLDataType.VARCHAR(16).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.cas_2024.istat_comune</code>.
     */
    public final TableField<Cas_2024Record, Integer> ISTAT_COMUNE = createField(DSL.name("istat_comune"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.cas_2024.comune</code>.
     */
    public final TableField<Cas_2024Record, String> COMUNE = createField(DSL.name("comune"), SQLDataType.VARCHAR(34).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.cas_2024.indirizzo_abitazione</code>.
     */
    public final TableField<Cas_2024Record, String> INDIRIZZO_ABITAZIONE = createField(DSL.name("indirizzo_abitazione"), SQLDataType.VARCHAR(78).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private Cas_2024(Name alias, Table<Cas_2024Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cas_2024(Name alias, Table<Cas_2024Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.cas_2024</code> table reference
     */
    public Cas_2024(String alias) {
        this(DSL.name(alias), CAS_2024);
    }

    /**
     * Create an aliased <code>decreti.cas_2024</code> table reference
     */
    public Cas_2024(Name alias) {
        this(alias, CAS_2024);
    }

    /**
     * Create a <code>decreti.cas_2024</code> table reference
     */
    public Cas_2024() {
        this(DSL.name("cas_2024"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<Cas_2024Record, Integer> getIdentity() {
        return (Identity<Cas_2024Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Cas_2024Record> getPrimaryKey() {
        return Keys.KEY_CAS_2024_PRIMARY;
    }

    @Override
    public Cas_2024 as(String alias) {
        return new Cas_2024(DSL.name(alias), this);
    }

    @Override
    public Cas_2024 as(Name alias) {
        return new Cas_2024(alias, this);
    }

    @Override
    public Cas_2024 as(Table<?> alias) {
        return new Cas_2024(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cas_2024 rename(String name) {
        return new Cas_2024(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cas_2024 rename(Name name) {
        return new Cas_2024(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cas_2024 rename(Table<?> name) {
        return new Cas_2024(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cas_2024 where(Condition condition) {
        return new Cas_2024(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cas_2024 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cas_2024 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cas_2024 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cas_2024 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cas_2024 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cas_2024 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cas_2024 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cas_2024 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cas_2024 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
