/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.tables.records.ComStatofascicoloRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ComStatofascicolo extends TableImpl<ComStatofascicoloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.com_statofascicolo</code>
     */
    public static final ComStatofascicolo COM_STATOFASCICOLO = new ComStatofascicolo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ComStatofascicoloRecord> getRecordType() {
        return ComStatofascicoloRecord.class;
    }

    /**
     * The column <code>decreti.com_statofascicolo.idpratica</code>.
     */
    public final TableField<ComStatofascicoloRecord, Integer> IDPRATICA = createField(DSL.name("idpratica"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.com_statofascicolo.data_notifica</code>.
     */
    public final TableField<ComStatofascicoloRecord, LocalDate> DATA_NOTIFICA = createField(DSL.name("data_notifica"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>decreti.com_statofascicolo.stato</code>.
     */
    public final TableField<ComStatofascicoloRecord, String> STATO = createField(DSL.name("stato"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private ComStatofascicolo(Name alias, Table<ComStatofascicoloRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ComStatofascicolo(Name alias, Table<ComStatofascicoloRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.com_statofascicolo</code> table reference
     */
    public ComStatofascicolo(String alias) {
        this(DSL.name(alias), COM_STATOFASCICOLO);
    }

    /**
     * Create an aliased <code>decreti.com_statofascicolo</code> table reference
     */
    public ComStatofascicolo(Name alias) {
        this(alias, COM_STATOFASCICOLO);
    }

    /**
     * Create a <code>decreti.com_statofascicolo</code> table reference
     */
    public ComStatofascicolo() {
        this(DSL.name("com_statofascicolo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.COM_STATOFASCICOLO_COM_STATOFASCICOLO_IDX);
    }

    @Override
    public ComStatofascicolo as(String alias) {
        return new ComStatofascicolo(DSL.name(alias), this);
    }

    @Override
    public ComStatofascicolo as(Name alias) {
        return new ComStatofascicolo(alias, this);
    }

    @Override
    public ComStatofascicolo as(Table<?> alias) {
        return new ComStatofascicolo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ComStatofascicolo rename(String name) {
        return new ComStatofascicolo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ComStatofascicolo rename(Name name) {
        return new ComStatofascicolo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ComStatofascicolo rename(Table<?> name) {
        return new ComStatofascicolo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComStatofascicolo where(Condition condition) {
        return new ComStatofascicolo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComStatofascicolo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComStatofascicolo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComStatofascicolo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComStatofascicolo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComStatofascicolo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComStatofascicolo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ComStatofascicolo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComStatofascicolo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ComStatofascicolo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
