/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.LTipoPasso.LTipoPassoPath;
import it.usr.web.usromniapp.domain.tables.ProcEsiti.ProcEsitiPath;
import it.usr.web.usromniapp.domain.tables.records.EsitiAttivazioneRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * tabella per l'attivazione automatica del passo successivo anche di diversa
 * procedura a seguito della conclusione di un iter
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EsitiAttivazione extends TableImpl<EsitiAttivazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.esiti_attivazione</code>
     */
    public static final EsitiAttivazione ESITI_ATTIVAZIONE = new EsitiAttivazione();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EsitiAttivazioneRecord> getRecordType() {
        return EsitiAttivazioneRecord.class;
    }

    /**
     * The column <code>decreti.esiti_attivazione.idesiti_attivazione</code>.
     */
    public final TableField<EsitiAttivazioneRecord, Integer> IDESITI_ATTIVAZIONE = createField(DSL.name("idesiti_attivazione"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.esiti_attivazione.id_esito</code>.
     */
    public final TableField<EsitiAttivazioneRecord, Integer> ID_ESITO = createField(DSL.name("id_esito"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.esiti_attivazione.codice_passo</code>.
     */
    public final TableField<EsitiAttivazioneRecord, Integer> CODICE_PASSO = createField(DSL.name("codice_passo"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.esiti_attivazione.attivo</code>.
     */
    public final TableField<EsitiAttivazioneRecord, Boolean> ATTIVO = createField(DSL.name("attivo"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'1'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>decreti.esiti_attivazione.note</code>.
     */
    public final TableField<EsitiAttivazioneRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private EsitiAttivazione(Name alias, Table<EsitiAttivazioneRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EsitiAttivazione(Name alias, Table<EsitiAttivazioneRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("tabella per l'attivazione automatica del passo successivo anche di diversa procedura a seguito della conclusione di un iter"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.esiti_attivazione</code> table reference
     */
    public EsitiAttivazione(String alias) {
        this(DSL.name(alias), ESITI_ATTIVAZIONE);
    }

    /**
     * Create an aliased <code>decreti.esiti_attivazione</code> table reference
     */
    public EsitiAttivazione(Name alias) {
        this(alias, ESITI_ATTIVAZIONE);
    }

    /**
     * Create a <code>decreti.esiti_attivazione</code> table reference
     */
    public EsitiAttivazione() {
        this(DSL.name("esiti_attivazione"), null);
    }

    public <O extends Record> EsitiAttivazione(Table<O> path, ForeignKey<O, EsitiAttivazioneRecord> childPath, InverseForeignKey<O, EsitiAttivazioneRecord> parentPath) {
        super(path, childPath, parentPath, ESITI_ATTIVAZIONE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EsitiAttivazionePath extends EsitiAttivazione implements Path<EsitiAttivazioneRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EsitiAttivazionePath(Table<O> path, ForeignKey<O, EsitiAttivazioneRecord> childPath, InverseForeignKey<O, EsitiAttivazioneRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EsitiAttivazionePath(Name alias, Table<EsitiAttivazioneRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EsitiAttivazionePath as(String alias) {
            return new EsitiAttivazionePath(DSL.name(alias), this);
        }

        @Override
        public EsitiAttivazionePath as(Name alias) {
            return new EsitiAttivazionePath(alias, this);
        }

        @Override
        public EsitiAttivazionePath as(Table<?> alias) {
            return new EsitiAttivazionePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ESITI_ATTIVAZIONE_FK_ESITIATT_ESITI_IDX, Indexes.ESITI_ATTIVAZIONE_FK_ESITIATTIVAZ_TIPOPASS_IDX);
    }

    @Override
    public Identity<EsitiAttivazioneRecord, Integer> getIdentity() {
        return (Identity<EsitiAttivazioneRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EsitiAttivazioneRecord> getPrimaryKey() {
        return Keys.KEY_ESITI_ATTIVAZIONE_PRIMARY;
    }

    @Override
    public List<UniqueKey<EsitiAttivazioneRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ESITI_ATTIVAZIONE_UQ_ESITIATTIVAZIONE);
    }

    @Override
    public List<ForeignKey<EsitiAttivazioneRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ESITIATTIVAZ_ESITI, Keys.FK_ESITIATTIVAZ_TIPOPASS);
    }

    private transient ProcEsitiPath _procEsiti;

    /**
     * Get the implicit join path to the <code>decreti.proc_esiti</code> table.
     */
    public ProcEsitiPath procEsiti() {
        if (_procEsiti == null)
            _procEsiti = new ProcEsitiPath(this, Keys.FK_ESITIATTIVAZ_ESITI, null);

        return _procEsiti;
    }

    private transient LTipoPassoPath _lTipoPasso;

    /**
     * Get the implicit join path to the <code>decreti.l_tipo_passo</code>
     * table.
     */
    public LTipoPassoPath lTipoPasso() {
        if (_lTipoPasso == null)
            _lTipoPasso = new LTipoPassoPath(this, Keys.FK_ESITIATTIVAZ_TIPOPASS, null);

        return _lTipoPasso;
    }

    @Override
    public EsitiAttivazione as(String alias) {
        return new EsitiAttivazione(DSL.name(alias), this);
    }

    @Override
    public EsitiAttivazione as(Name alias) {
        return new EsitiAttivazione(alias, this);
    }

    @Override
    public EsitiAttivazione as(Table<?> alias) {
        return new EsitiAttivazione(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EsitiAttivazione rename(String name) {
        return new EsitiAttivazione(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EsitiAttivazione rename(Name name) {
        return new EsitiAttivazione(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EsitiAttivazione rename(Table<?> name) {
        return new EsitiAttivazione(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EsitiAttivazione where(Condition condition) {
        return new EsitiAttivazione(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EsitiAttivazione where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EsitiAttivazione where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EsitiAttivazione where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EsitiAttivazione where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EsitiAttivazione where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EsitiAttivazione where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EsitiAttivazione where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EsitiAttivazione whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EsitiAttivazione whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
