/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.tables.records.GisCentroidiElementiRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GisCentroidiElementi extends TableImpl<GisCentroidiElementiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.gis_centroidi_elementi</code>
     */
    public static final GisCentroidiElementi GIS_CENTROIDI_ELEMENTI = new GisCentroidiElementi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GisCentroidiElementiRecord> getRecordType() {
        return GisCentroidiElementiRecord.class;
    }

    /**
     * The column <code>decreti.gis_centroidi_elementi.id</code>.
     */
    public final TableField<GisCentroidiElementiRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.gis_centroidi_elementi.codice_prov</code>.
     */
    public final TableField<GisCentroidiElementiRecord, Integer> CODICE_PROV = createField(DSL.name("codice_prov"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.gis_centroidi_elementi.codice_com</code>.
     */
    public final TableField<GisCentroidiElementiRecord, Integer> CODICE_COM = createField(DSL.name("codice_com"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.gis_centroidi_elementi.comune</code>.
     */
    public final TableField<GisCentroidiElementiRecord, String> COMUNE = createField(DSL.name("comune"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<GisCentroidiElementiRecord, Object> CENTRO = createField(DSL.name("centro"), DefaultDataType.getDefaultDataType("\"decreti\".\"gis_centroidi_elementi_centro\"").nullable(false), this, "");

    /**
     * The column <code>decreti.gis_centroidi_elementi.num_elementi</code>.
     */
    public final TableField<GisCentroidiElementiRecord, Long> NUM_ELEMENTI = createField(DSL.name("num_elementi"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "");

    private GisCentroidiElementi(Name alias, Table<GisCentroidiElementiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GisCentroidiElementi(Name alias, Table<GisCentroidiElementiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `gis_centroidi_elementi` as select `gc`.`id` AS `id`,`gc`.`codice_prov` AS `codice_prov`,`gc`.`codice_com` AS `codice_com`,`gc`.`comune` AS `comune`,`gc`.`centro` AS `centro`,(select count(`gp`.`id`) from `decreti`.`gis_privata` `gp` where `gp`.`istat` = `gc`.`codice_com`) AS `num_elementi` from `decreti`.`gis_centroidi` `gc`"), where);
    }

    /**
     * Create an aliased <code>decreti.gis_centroidi_elementi</code> table
     * reference
     */
    public GisCentroidiElementi(String alias) {
        this(DSL.name(alias), GIS_CENTROIDI_ELEMENTI);
    }

    /**
     * Create an aliased <code>decreti.gis_centroidi_elementi</code> table
     * reference
     */
    public GisCentroidiElementi(Name alias) {
        this(alias, GIS_CENTROIDI_ELEMENTI);
    }

    /**
     * Create a <code>decreti.gis_centroidi_elementi</code> table reference
     */
    public GisCentroidiElementi() {
        this(DSL.name("gis_centroidi_elementi"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public GisCentroidiElementi as(String alias) {
        return new GisCentroidiElementi(DSL.name(alias), this);
    }

    @Override
    public GisCentroidiElementi as(Name alias) {
        return new GisCentroidiElementi(alias, this);
    }

    @Override
    public GisCentroidiElementi as(Table<?> alias) {
        return new GisCentroidiElementi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GisCentroidiElementi rename(String name) {
        return new GisCentroidiElementi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisCentroidiElementi rename(Name name) {
        return new GisCentroidiElementi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisCentroidiElementi rename(Table<?> name) {
        return new GisCentroidiElementi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisCentroidiElementi where(Condition condition) {
        return new GisCentroidiElementi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisCentroidiElementi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisCentroidiElementi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisCentroidiElementi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisCentroidiElementi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisCentroidiElementi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisCentroidiElementi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisCentroidiElementi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisCentroidiElementi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisCentroidiElementi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
