/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.GisDettaglioRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GisDettaglio extends TableImpl<GisDettaglioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.gis_dettaglio</code>
     */
    public static final GisDettaglio GIS_DETTAGLIO = new GisDettaglio();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GisDettaglioRecord> getRecordType() {
        return GisDettaglioRecord.class;
    }

    /**
     * The column <code>decreti.gis_dettaglio.id</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.id_pratica</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> ID_PRATICA = createField(DSL.name("id_pratica"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.id_tipo_proprieta</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> ID_TIPO_PROPRIETA = createField(DSL.name("id_tipo_proprieta"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.id_tipo_pratica</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> ID_TIPO_PRATICA = createField(DSL.name("id_tipo_pratica"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.destinatario</code>.
     */
    public final TableField<GisDettaglioRecord, String> DESTINATARIO = createField(DSL.name("destinatario"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.stato</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> STATO = createField(DSL.name("stato"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("-100", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.contributo_richiesto</code>.
     */
    public final TableField<GisDettaglioRecord, BigDecimal> CONTRIBUTO_RICHIESTO = createField(DSL.name("contributo_richiesto"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.contributo_concesso</code>.
     */
    public final TableField<GisDettaglioRecord, BigDecimal> CONTRIBUTO_CONCESSO = createField(DSL.name("contributo_concesso"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.numero_liquidazioni</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> NUMERO_LIQUIDAZIONI = createField(DSL.name("numero_liquidazioni"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.contributo_liquidato</code>.
     */
    public final TableField<GisDettaglioRecord, BigDecimal> CONTRIBUTO_LIQUIDATO = createField(DSL.name("contributo_liquidato"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.ord100</code>.
     */
    public final TableField<GisDettaglioRecord, Short> ORD100 = createField(DSL.name("ord100"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.provvedimento_concessione</code>.
     */
    public final TableField<GisDettaglioRecord, String> PROVVEDIMENTO_CONCESSIONE = createField(DSL.name("provvedimento_concessione"), SQLDataType.VARCHAR(30).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.ordinanza_riferimento</code>.
     */
    public final TableField<GisDettaglioRecord, String> ORDINANZA_RIFERIMENTO = createField(DSL.name("ordinanza_riferimento"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.data_concessione</code>.
     */
    public final TableField<GisDettaglioRecord, LocalDate> DATA_CONCESSIONE = createField(DSL.name("data_concessione"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.data_ultimo_provvedimento</code>.
     */
    public final TableField<GisDettaglioRecord, LocalDate> DATA_ULTIMO_PROVVEDIMENTO = createField(DSL.name("data_ultimo_provvedimento"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>decreti.gis_dettaglio.giorni_durata_lavori</code>.
     */
    public final TableField<GisDettaglioRecord, Integer> GIORNI_DURATA_LAVORI = createField(DSL.name("giorni_durata_lavori"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    private GisDettaglio(Name alias, Table<GisDettaglioRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GisDettaglio(Name alias, Table<GisDettaglioRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.gis_dettaglio</code> table reference
     */
    public GisDettaglio(String alias) {
        this(DSL.name(alias), GIS_DETTAGLIO);
    }

    /**
     * Create an aliased <code>decreti.gis_dettaglio</code> table reference
     */
    public GisDettaglio(Name alias) {
        this(alias, GIS_DETTAGLIO);
    }

    /**
     * Create a <code>decreti.gis_dettaglio</code> table reference
     */
    public GisDettaglio() {
        this(DSL.name("gis_dettaglio"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.GIS_DETTAGLIO_IDX_GISDETTAGLIO_IDPRATICA);
    }

    @Override
    public Identity<GisDettaglioRecord, Integer> getIdentity() {
        return (Identity<GisDettaglioRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GisDettaglioRecord> getPrimaryKey() {
        return Keys.KEY_GIS_DETTAGLIO_PRIMARY;
    }

    @Override
    public GisDettaglio as(String alias) {
        return new GisDettaglio(DSL.name(alias), this);
    }

    @Override
    public GisDettaglio as(Name alias) {
        return new GisDettaglio(alias, this);
    }

    @Override
    public GisDettaglio as(Table<?> alias) {
        return new GisDettaglio(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GisDettaglio rename(String name) {
        return new GisDettaglio(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisDettaglio rename(Name name) {
        return new GisDettaglio(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisDettaglio rename(Table<?> name) {
        return new GisDettaglio(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisDettaglio where(Condition condition) {
        return new GisDettaglio(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisDettaglio where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisDettaglio where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisDettaglio where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisDettaglio where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisDettaglio where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisDettaglio where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisDettaglio where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisDettaglio whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisDettaglio whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
