/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.GisManifestazDettaglioRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GisManifestazDettaglio extends TableImpl<GisManifestazDettaglioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.gis_manifestaz_dettaglio</code>
     */
    public static final GisManifestazDettaglio GIS_MANIFESTAZ_DETTAGLIO = new GisManifestazDettaglio();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GisManifestazDettaglioRecord> getRecordType() {
        return GisManifestazDettaglioRecord.class;
    }

    /**
     * The column <code>decreti.gis_manifestaz_dettaglio.id</code>.
     */
    public final TableField<GisManifestazDettaglioRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.gis_manifestaz_dettaglio.id_poligon</code>.
     */
    public final TableField<GisManifestazDettaglioRecord, Integer> ID_POLIGON = createField(DSL.name("id_poligon"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>decreti.gis_manifestaz_dettaglio.codice_manifestazione</code>.
     */
    public final TableField<GisManifestazDettaglioRecord, String> CODICE_MANIFESTAZIONE = createField(DSL.name("codice_manifestazione"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column
     * <code>decreti.gis_manifestaz_dettaglio.data_manifestazione</code>.
     */
    public final TableField<GisManifestazDettaglioRecord, LocalDate> DATA_MANIFESTAZIONE = createField(DSL.name("data_manifestazione"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private GisManifestazDettaglio(Name alias, Table<GisManifestazDettaglioRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GisManifestazDettaglio(Name alias, Table<GisManifestazDettaglioRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.gis_manifestaz_dettaglio</code> table
     * reference
     */
    public GisManifestazDettaglio(String alias) {
        this(DSL.name(alias), GIS_MANIFESTAZ_DETTAGLIO);
    }

    /**
     * Create an aliased <code>decreti.gis_manifestaz_dettaglio</code> table
     * reference
     */
    public GisManifestazDettaglio(Name alias) {
        this(alias, GIS_MANIFESTAZ_DETTAGLIO);
    }

    /**
     * Create a <code>decreti.gis_manifestaz_dettaglio</code> table reference
     */
    public GisManifestazDettaglio() {
        this(DSL.name("gis_manifestaz_dettaglio"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<GisManifestazDettaglioRecord, Integer> getIdentity() {
        return (Identity<GisManifestazDettaglioRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GisManifestazDettaglioRecord> getPrimaryKey() {
        return Keys.KEY_GIS_MANIFESTAZ_DETTAGLIO_PRIMARY;
    }

    @Override
    public GisManifestazDettaglio as(String alias) {
        return new GisManifestazDettaglio(DSL.name(alias), this);
    }

    @Override
    public GisManifestazDettaglio as(Name alias) {
        return new GisManifestazDettaglio(alias, this);
    }

    @Override
    public GisManifestazDettaglio as(Table<?> alias) {
        return new GisManifestazDettaglio(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GisManifestazDettaglio rename(String name) {
        return new GisManifestazDettaglio(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisManifestazDettaglio rename(Name name) {
        return new GisManifestazDettaglio(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisManifestazDettaglio rename(Table<?> name) {
        return new GisManifestazDettaglio(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisManifestazDettaglio where(Condition condition) {
        return new GisManifestazDettaglio(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisManifestazDettaglio where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisManifestazDettaglio where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisManifestazDettaglio where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisManifestazDettaglio where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisManifestazDettaglio where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisManifestazDettaglio where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisManifestazDettaglio where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisManifestazDettaglio whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisManifestazDettaglio whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
