/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.GismanagerUtentiRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GismanagerUtenti extends TableImpl<GismanagerUtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.gismanager_utenti</code>
     */
    public static final GismanagerUtenti GISMANAGER_UTENTI = new GismanagerUtenti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GismanagerUtentiRecord> getRecordType() {
        return GismanagerUtentiRecord.class;
    }

    /**
     * The column <code>decreti.gismanager_utenti.username</code>.
     */
    public final TableField<GismanagerUtentiRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>decreti.gismanager_utenti.abilitato</code>.
     */
    public final TableField<GismanagerUtentiRecord, Byte> ABILITATO = createField(DSL.name("abilitato"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "");

    private GismanagerUtenti(Name alias, Table<GismanagerUtentiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GismanagerUtenti(Name alias, Table<GismanagerUtentiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.gismanager_utenti</code> table reference
     */
    public GismanagerUtenti(String alias) {
        this(DSL.name(alias), GISMANAGER_UTENTI);
    }

    /**
     * Create an aliased <code>decreti.gismanager_utenti</code> table reference
     */
    public GismanagerUtenti(Name alias) {
        this(alias, GISMANAGER_UTENTI);
    }

    /**
     * Create a <code>decreti.gismanager_utenti</code> table reference
     */
    public GismanagerUtenti() {
        this(DSL.name("gismanager_utenti"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public UniqueKey<GismanagerUtentiRecord> getPrimaryKey() {
        return Keys.KEY_GISMANAGER_UTENTI_PRIMARY;
    }

    @Override
    public GismanagerUtenti as(String alias) {
        return new GismanagerUtenti(DSL.name(alias), this);
    }

    @Override
    public GismanagerUtenti as(Name alias) {
        return new GismanagerUtenti(alias, this);
    }

    @Override
    public GismanagerUtenti as(Table<?> alias) {
        return new GismanagerUtenti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GismanagerUtenti rename(String name) {
        return new GismanagerUtenti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GismanagerUtenti rename(Name name) {
        return new GismanagerUtenti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GismanagerUtenti rename(Table<?> name) {
        return new GismanagerUtenti(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GismanagerUtenti where(Condition condition) {
        return new GismanagerUtenti(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GismanagerUtenti where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GismanagerUtenti where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GismanagerUtenti where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GismanagerUtenti where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GismanagerUtenti where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GismanagerUtenti where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GismanagerUtenti where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GismanagerUtenti whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GismanagerUtenti whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
