/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.GisPrivataInterfacciaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GisPrivataInterfaccia extends TableImpl<GisPrivataInterfacciaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.gis_privata_interfaccia</code>
     */
    public static final GisPrivataInterfaccia GIS_PRIVATA_INTERFACCIA = new GisPrivataInterfaccia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GisPrivataInterfacciaRecord> getRecordType() {
        return GisPrivataInterfacciaRecord.class;
    }

    /**
     * The column
     * <code>decreti.gis_privata_interfaccia.id_pratica_poligono</code>.
     */
    public final TableField<GisPrivataInterfacciaRecord, Integer> ID_PRATICA_POLIGONO = createField(DSL.name("id_pratica_poligono"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.gis_privata_interfaccia.id_pratica</code>.
     */
    public final TableField<GisPrivataInterfacciaRecord, Integer> ID_PRATICA = createField(DSL.name("id_pratica"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.gis_privata_interfaccia.dataora</code>.
     */
    public final TableField<GisPrivataInterfacciaRecord, LocalDateTime> DATAORA = createField(DSL.name("dataora"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private GisPrivataInterfaccia(Name alias, Table<GisPrivataInterfacciaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GisPrivataInterfaccia(Name alias, Table<GisPrivataInterfacciaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.gis_privata_interfaccia</code> table
     * reference
     */
    public GisPrivataInterfaccia(String alias) {
        this(DSL.name(alias), GIS_PRIVATA_INTERFACCIA);
    }

    /**
     * Create an aliased <code>decreti.gis_privata_interfaccia</code> table
     * reference
     */
    public GisPrivataInterfaccia(Name alias) {
        this(alias, GIS_PRIVATA_INTERFACCIA);
    }

    /**
     * Create a <code>decreti.gis_privata_interfaccia</code> table reference
     */
    public GisPrivataInterfaccia() {
        this(DSL.name("gis_privata_interfaccia"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public UniqueKey<GisPrivataInterfacciaRecord> getPrimaryKey() {
        return Keys.KEY_GIS_PRIVATA_INTERFACCIA_PRIMARY;
    }

    @Override
    public List<UniqueKey<GisPrivataInterfacciaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GIS_PRIVATA_INTERFACCIA_ID_PRATICA);
    }

    @Override
    public GisPrivataInterfaccia as(String alias) {
        return new GisPrivataInterfaccia(DSL.name(alias), this);
    }

    @Override
    public GisPrivataInterfaccia as(Name alias) {
        return new GisPrivataInterfaccia(alias, this);
    }

    @Override
    public GisPrivataInterfaccia as(Table<?> alias) {
        return new GisPrivataInterfaccia(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GisPrivataInterfaccia rename(String name) {
        return new GisPrivataInterfaccia(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisPrivataInterfaccia rename(Name name) {
        return new GisPrivataInterfaccia(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GisPrivataInterfaccia rename(Table<?> name) {
        return new GisPrivataInterfaccia(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisPrivataInterfaccia where(Condition condition) {
        return new GisPrivataInterfaccia(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisPrivataInterfaccia where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisPrivataInterfaccia where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisPrivataInterfaccia where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisPrivataInterfaccia where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisPrivataInterfaccia where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisPrivataInterfaccia where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GisPrivataInterfaccia where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisPrivataInterfaccia whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GisPrivataInterfaccia whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
