/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.ProcIncarichi.ProcIncarichiPath;
import it.usr.web.usromniapp.domain.tables.records.LRuoloTecnicoRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LRuoloTecnico extends TableImpl<LRuoloTecnicoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.l_ruolo_tecnico</code>
     */
    public static final LRuoloTecnico L_RUOLO_TECNICO = new LRuoloTecnico();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LRuoloTecnicoRecord> getRecordType() {
        return LRuoloTecnicoRecord.class;
    }

    /**
     * The column <code>decreti.l_ruolo_tecnico.id_ruolo_tecnico</code>.
     */
    public final TableField<LRuoloTecnicoRecord, Integer> ID_RUOLO_TECNICO = createField(DSL.name("id_ruolo_tecnico"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.l_ruolo_tecnico.ruolo_tecnico</code>.
     */
    public final TableField<LRuoloTecnicoRecord, String> RUOLO_TECNICO = createField(DSL.name("ruolo_tecnico"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private LRuoloTecnico(Name alias, Table<LRuoloTecnicoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LRuoloTecnico(Name alias, Table<LRuoloTecnicoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.l_ruolo_tecnico</code> table reference
     */
    public LRuoloTecnico(String alias) {
        this(DSL.name(alias), L_RUOLO_TECNICO);
    }

    /**
     * Create an aliased <code>decreti.l_ruolo_tecnico</code> table reference
     */
    public LRuoloTecnico(Name alias) {
        this(alias, L_RUOLO_TECNICO);
    }

    /**
     * Create a <code>decreti.l_ruolo_tecnico</code> table reference
     */
    public LRuoloTecnico() {
        this(DSL.name("l_ruolo_tecnico"), null);
    }

    public <O extends Record> LRuoloTecnico(Table<O> path, ForeignKey<O, LRuoloTecnicoRecord> childPath, InverseForeignKey<O, LRuoloTecnicoRecord> parentPath) {
        super(path, childPath, parentPath, L_RUOLO_TECNICO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LRuoloTecnicoPath extends LRuoloTecnico implements Path<LRuoloTecnicoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LRuoloTecnicoPath(Table<O> path, ForeignKey<O, LRuoloTecnicoRecord> childPath, InverseForeignKey<O, LRuoloTecnicoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LRuoloTecnicoPath(Name alias, Table<LRuoloTecnicoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LRuoloTecnicoPath as(String alias) {
            return new LRuoloTecnicoPath(DSL.name(alias), this);
        }

        @Override
        public LRuoloTecnicoPath as(Name alias) {
            return new LRuoloTecnicoPath(alias, this);
        }

        @Override
        public LRuoloTecnicoPath as(Table<?> alias) {
            return new LRuoloTecnicoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<LRuoloTecnicoRecord, Integer> getIdentity() {
        return (Identity<LRuoloTecnicoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LRuoloTecnicoRecord> getPrimaryKey() {
        return Keys.KEY_L_RUOLO_TECNICO_PRIMARY;
    }

    private transient ProcIncarichiPath _procIncarichi;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.proc_incarichi</code> table
     */
    public ProcIncarichiPath procIncarichi() {
        if (_procIncarichi == null)
            _procIncarichi = new ProcIncarichiPath(this, null, Keys.FK_PROCINCARICHI_RUOLOTECNICO.getInverseKey());

        return _procIncarichi;
    }

    @Override
    public LRuoloTecnico as(String alias) {
        return new LRuoloTecnico(DSL.name(alias), this);
    }

    @Override
    public LRuoloTecnico as(Name alias) {
        return new LRuoloTecnico(alias, this);
    }

    @Override
    public LRuoloTecnico as(Table<?> alias) {
        return new LRuoloTecnico(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LRuoloTecnico rename(String name) {
        return new LRuoloTecnico(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LRuoloTecnico rename(Name name) {
        return new LRuoloTecnico(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LRuoloTecnico rename(Table<?> name) {
        return new LRuoloTecnico(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LRuoloTecnico where(Condition condition) {
        return new LRuoloTecnico(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LRuoloTecnico where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LRuoloTecnico where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LRuoloTecnico where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LRuoloTecnico where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LRuoloTecnico where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LRuoloTecnico where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LRuoloTecnico where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LRuoloTecnico whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LRuoloTecnico whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
