/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.EsitiAttivazione.EsitiAttivazionePath;
import it.usr.web.usromniapp.domain.tables.LTipoProc.LTipoProcPath;
import it.usr.web.usromniapp.domain.tables.ProcDipendenze.ProcDipendenzePath;
import it.usr.web.usromniapp.domain.tables.ProcEsiti.ProcEsitiPath;
import it.usr.web.usromniapp.domain.tables.ProcIter.ProcIterPath;
import it.usr.web.usromniapp.domain.tables.ProcPassoIniziale.ProcPassoInizialePath;
import it.usr.web.usromniapp.domain.tables.records.LTipoPassoRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LTipoPasso extends TableImpl<LTipoPassoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.l_tipo_passo</code>
     */
    public static final LTipoPasso L_TIPO_PASSO = new LTipoPasso();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LTipoPassoRecord> getRecordType() {
        return LTipoPassoRecord.class;
    }

    /**
     * The column <code>decreti.l_tipo_passo.codice_passo</code>.
     */
    public final TableField<LTipoPassoRecord, Integer> CODICE_PASSO = createField(DSL.name("codice_passo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.testo_passo</code>.
     */
    public final TableField<LTipoPassoRecord, String> TESTO_PASSO = createField(DSL.name("testo_passo"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.visibile</code>.
     */
    public final TableField<LTipoPassoRecord, Integer> VISIBILE = createField(DSL.name("visibile"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.stato</code>.
     */
    public final TableField<LTipoPassoRecord, String> STATO = createField(DSL.name("stato"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.influenza_stato</code>.
     */
    public final TableField<LTipoPassoRecord, Integer> INFLUENZA_STATO = createField(DSL.name("influenza_stato"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.id_tipo_proc</code>.
     */
    public final TableField<LTipoPassoRecord, Integer> ID_TIPO_PROC = createField(DSL.name("id_tipo_proc"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.durata_prevista</code>.
     */
    public final TableField<LTipoPassoRecord, Integer> DURATA_PREVISTA = createField(DSL.name("durata_prevista"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.prot_richiesto</code>.
     */
    public final TableField<LTipoPassoRecord, Boolean> PROT_RICHIESTO = createField(DSL.name("prot_richiesto"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.esito_obbligatorio</code>.
     */
    public final TableField<LTipoPassoRecord, Boolean> ESITO_OBBLIGATORIO = createField(DSL.name("esito_obbligatorio"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.data_automatica</code>.
     */
    public final TableField<LTipoPassoRecord, Boolean> DATA_AUTOMATICA = createField(DSL.name("data_automatica"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.passo_ufficio</code>.
     */
    public final TableField<LTipoPassoRecord, Boolean> PASSO_UFFICIO = createField(DSL.name("passo_ufficio"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'1'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.passo_firma</code>.
     */
    public final TableField<LTipoPassoRecord, Boolean> PASSO_FIRMA = createField(DSL.name("passo_firma"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>decreti.l_tipo_passo.allegati_obbligatori</code>. 0 = NO
     * DOCUMENTI, 1 = DOCUMENTI OBBLIGATORI, 2 = COME 1 + ALMENO UNO FIRMATO
     * DIGITALMENTE
     */
    public final TableField<LTipoPassoRecord, Integer> ALLEGATI_OBBLIGATORI = createField(DSL.name("allegati_obbligatori"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "0 = NO DOCUMENTI, 1 = DOCUMENTI OBBLIGATORI, 2 = COME 1 + ALMENO UNO FIRMATO DIGITALMENTE");

    /**
     * The column <code>decreti.l_tipo_passo.id_tipo_proc_sub</code>.
     */
    public final TableField<LTipoPassoRecord, Integer> ID_TIPO_PROC_SUB = createField(DSL.name("id_tipo_proc_sub"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    private LTipoPasso(Name alias, Table<LTipoPassoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LTipoPasso(Name alias, Table<LTipoPassoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.l_tipo_passo</code> table reference
     */
    public LTipoPasso(String alias) {
        this(DSL.name(alias), L_TIPO_PASSO);
    }

    /**
     * Create an aliased <code>decreti.l_tipo_passo</code> table reference
     */
    public LTipoPasso(Name alias) {
        this(alias, L_TIPO_PASSO);
    }

    /**
     * Create a <code>decreti.l_tipo_passo</code> table reference
     */
    public LTipoPasso() {
        this(DSL.name("l_tipo_passo"), null);
    }

    public <O extends Record> LTipoPasso(Table<O> path, ForeignKey<O, LTipoPassoRecord> childPath, InverseForeignKey<O, LTipoPassoRecord> parentPath) {
        super(path, childPath, parentPath, L_TIPO_PASSO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LTipoPassoPath extends LTipoPasso implements Path<LTipoPassoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LTipoPassoPath(Table<O> path, ForeignKey<O, LTipoPassoRecord> childPath, InverseForeignKey<O, LTipoPassoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LTipoPassoPath(Name alias, Table<LTipoPassoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LTipoPassoPath as(String alias) {
            return new LTipoPassoPath(DSL.name(alias), this);
        }

        @Override
        public LTipoPassoPath as(Name alias) {
            return new LTipoPassoPath(alias, this);
        }

        @Override
        public LTipoPassoPath as(Table<?> alias) {
            return new LTipoPassoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.L_TIPO_PASSO_FK_TIPOPASS_TIPOPROC_IDX, Indexes.L_TIPO_PASSO_FK_TIPOPASSSUB_TIPOPROC_IDX);
    }

    @Override
    public UniqueKey<LTipoPassoRecord> getPrimaryKey() {
        return Keys.KEY_L_TIPO_PASSO_PRIMARY;
    }

    @Override
    public List<ForeignKey<LTipoPassoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_TIPOPASS_TIPOPROC, Keys.FK_TIPOPASSSUB_TIPOPROC);
    }

    private transient LTipoProcPath _fkTipopassTipoproc;

    /**
     * Get the implicit join path to the <code>decreti.l_tipo_proc</code> table,
     * via the <code>fk_tipopass_tipoproc</code> key.
     */
    public LTipoProcPath fkTipopassTipoproc() {
        if (_fkTipopassTipoproc == null)
            _fkTipopassTipoproc = new LTipoProcPath(this, Keys.FK_TIPOPASS_TIPOPROC, null);

        return _fkTipopassTipoproc;
    }

    private transient LTipoProcPath _fkTipopasssubTipoproc;

    /**
     * Get the implicit join path to the <code>decreti.l_tipo_proc</code> table,
     * via the <code>fk_tipopasssub_tipoproc</code> key.
     */
    public LTipoProcPath fkTipopasssubTipoproc() {
        if (_fkTipopasssubTipoproc == null)
            _fkTipopasssubTipoproc = new LTipoProcPath(this, Keys.FK_TIPOPASSSUB_TIPOPROC, null);

        return _fkTipopasssubTipoproc;
    }

    private transient EsitiAttivazionePath _esitiAttivazione;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.esiti_attivazione</code> table
     */
    public EsitiAttivazionePath esitiAttivazione() {
        if (_esitiAttivazione == null)
            _esitiAttivazione = new EsitiAttivazionePath(this, null, Keys.FK_ESITIATTIVAZ_TIPOPASS.getInverseKey());

        return _esitiAttivazione;
    }

    private transient ProcDipendenzePath _procDipendenze;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.proc_dipendenze</code> table
     */
    public ProcDipendenzePath procDipendenze() {
        if (_procDipendenze == null)
            _procDipendenze = new ProcDipendenzePath(this, null, Keys.FK_PROCDIPEND_TIPOPASSO.getInverseKey());

        return _procDipendenze;
    }

    private transient ProcIterPath _procIter;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_iter</code>
     * table
     */
    public ProcIterPath procIter() {
        if (_procIter == null)
            _procIter = new ProcIterPath(this, null, Keys.FK_PROCITER_CODICEPASSO.getInverseKey());

        return _procIter;
    }

    private transient ProcPassoInizialePath _procPassoIniziale;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.proc_passo_iniziale</code> table
     */
    public ProcPassoInizialePath procPassoIniziale() {
        if (_procPassoIniziale == null)
            _procPassoIniziale = new ProcPassoInizialePath(this, null, Keys.FK_PROCPASSOINIZ_TIPOPASSO.getInverseKey());

        return _procPassoIniziale;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>decreti.proc_esiti</code> table
     */
    public ProcEsitiPath procEsiti() {
        return esitiAttivazione().procEsiti();
    }

    @Override
    public LTipoPasso as(String alias) {
        return new LTipoPasso(DSL.name(alias), this);
    }

    @Override
    public LTipoPasso as(Name alias) {
        return new LTipoPasso(alias, this);
    }

    @Override
    public LTipoPasso as(Table<?> alias) {
        return new LTipoPasso(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LTipoPasso rename(String name) {
        return new LTipoPasso(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LTipoPasso rename(Name name) {
        return new LTipoPasso(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LTipoPasso rename(Table<?> name) {
        return new LTipoPasso(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoPasso where(Condition condition) {
        return new LTipoPasso(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoPasso where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoPasso where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoPasso where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoPasso where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoPasso where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoPasso where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoPasso where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoPasso whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoPasso whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
