/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.Delega.DelegaPath;
import it.usr.web.usromniapp.domain.tables.LTipoPasso.LTipoPassoPath;
import it.usr.web.usromniapp.domain.tables.Proc.ProcPath;
import it.usr.web.usromniapp.domain.tables.ProcDipendenze.ProcDipendenzePath;
import it.usr.web.usromniapp.domain.tables.ProcEsiti.ProcEsitiPath;
import it.usr.web.usromniapp.domain.tables.ProcPassoIniziale.ProcPassoInizialePath;
import it.usr.web.usromniapp.domain.tables.TipoProcAss.TipoProcAssPath;
import it.usr.web.usromniapp.domain.tables.TipoProcProgressivo.TipoProcProgressivoPath;
import it.usr.web.usromniapp.domain.tables.records.LTipoProcRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LTipoProc extends TableImpl<LTipoProcRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.l_tipo_proc</code>
     */
    public static final LTipoProc L_TIPO_PROC = new LTipoProc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LTipoProcRecord> getRecordType() {
        return LTipoProcRecord.class;
    }

    /**
     * The column <code>decreti.l_tipo_proc.id_tipo_proc</code>.
     */
    public final TableField<LTipoProcRecord, Integer> ID_TIPO_PROC = createField(DSL.name("id_tipo_proc"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.l_tipo_proc.tipo_proc</code>.
     */
    public final TableField<LTipoProcRecord, String> TIPO_PROC = createField(DSL.name("tipo_proc"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>decreti.l_tipo_proc.gruppo</code>.
     */
    public final TableField<LTipoProcRecord, String> GRUPPO = createField(DSL.name("gruppo"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.l_tipo_proc.funzione</code>. nome della pagina
     * che gestirà i dati di dettaglio (es. VLO, RCR, SAL, ecc.)
     */
    public final TableField<LTipoProcRecord, String> FUNZIONE = createField(DSL.name("funzione"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "nome della pagina che gestirà i dati di dettaglio (es. VLO, RCR, SAL, ecc.)");

    private LTipoProc(Name alias, Table<LTipoProcRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LTipoProc(Name alias, Table<LTipoProcRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.l_tipo_proc</code> table reference
     */
    public LTipoProc(String alias) {
        this(DSL.name(alias), L_TIPO_PROC);
    }

    /**
     * Create an aliased <code>decreti.l_tipo_proc</code> table reference
     */
    public LTipoProc(Name alias) {
        this(alias, L_TIPO_PROC);
    }

    /**
     * Create a <code>decreti.l_tipo_proc</code> table reference
     */
    public LTipoProc() {
        this(DSL.name("l_tipo_proc"), null);
    }

    public <O extends Record> LTipoProc(Table<O> path, ForeignKey<O, LTipoProcRecord> childPath, InverseForeignKey<O, LTipoProcRecord> parentPath) {
        super(path, childPath, parentPath, L_TIPO_PROC);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LTipoProcPath extends LTipoProc implements Path<LTipoProcRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LTipoProcPath(Table<O> path, ForeignKey<O, LTipoProcRecord> childPath, InverseForeignKey<O, LTipoProcRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LTipoProcPath(Name alias, Table<LTipoProcRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LTipoProcPath as(String alias) {
            return new LTipoProcPath(DSL.name(alias), this);
        }

        @Override
        public LTipoProcPath as(Name alias) {
            return new LTipoProcPath(alias, this);
        }

        @Override
        public LTipoProcPath as(Table<?> alias) {
            return new LTipoProcPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<LTipoProcRecord, Integer> getIdentity() {
        return (Identity<LTipoProcRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LTipoProcRecord> getPrimaryKey() {
        return Keys.KEY_L_TIPO_PROC_PRIMARY;
    }

    private transient DelegaPath _delega;

    /**
     * Get the implicit to-many join path to the <code>decreti.delega</code>
     * table
     */
    public DelegaPath delega() {
        if (_delega == null)
            _delega = new DelegaPath(this, null, Keys.FK_DELEGA_TIPOPROC.getInverseKey());

        return _delega;
    }

    private transient ProcEsitiPath _procEsiti;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_esiti</code>
     * table
     */
    public ProcEsitiPath procEsiti() {
        if (_procEsiti == null)
            _procEsiti = new ProcEsitiPath(this, null, Keys.FK_ESITI_TIPO_PROC.getInverseKey());

        return _procEsiti;
    }

    private transient ProcPath _proc;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc</code> table
     */
    public ProcPath proc() {
        if (_proc == null)
            _proc = new ProcPath(this, null, Keys.FK_PROC_TIPOPROC.getInverseKey());

        return _proc;
    }

    private transient ProcDipendenzePath _procDipendenze;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.proc_dipendenze</code> table
     */
    public ProcDipendenzePath procDipendenze() {
        if (_procDipendenze == null)
            _procDipendenze = new ProcDipendenzePath(this, null, Keys.FK_PROCDPEND_TIPOPROC.getInverseKey());

        return _procDipendenze;
    }

    private transient ProcPassoInizialePath _procPassoIniziale;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.proc_passo_iniziale</code> table
     */
    public ProcPassoInizialePath procPassoIniziale() {
        if (_procPassoIniziale == null)
            _procPassoIniziale = new ProcPassoInizialePath(this, null, Keys.FK_PROCPASSOINIZ_TIPOPROC.getInverseKey());

        return _procPassoIniziale;
    }

    private transient LTipoPassoPath _lTipoPasso;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.l_tipo_passo</code> table
     */
    public LTipoPassoPath lTipoPasso() {
        if (_lTipoPasso == null)
            _lTipoPasso = new LTipoPassoPath(this, null, Keys.FK_TIPOPASS_TIPOPROC.getInverseKey());

        return _lTipoPasso;
    }

    private transient TipoProcAssPath _tipoProcAss;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.tipo_proc_ass</code> table
     */
    public TipoProcAssPath tipoProcAss() {
        if (_tipoProcAss == null)
            _tipoProcAss = new TipoProcAssPath(this, null, Keys.FK_TIPOPROCASS_LTIPOPROC.getInverseKey());

        return _tipoProcAss;
    }

    private transient TipoProcProgressivoPath _tipoProcProgressivo;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.tipo_proc_progressivo</code> table
     */
    public TipoProcProgressivoPath tipoProcProgressivo() {
        if (_tipoProcProgressivo == null)
            _tipoProcProgressivo = new TipoProcProgressivoPath(this, null, Keys.FK_TIPOPROCPROGRESSIVO_TIPOPROC.getInverseKey());

        return _tipoProcProgressivo;
    }

    @Override
    public LTipoProc as(String alias) {
        return new LTipoProc(DSL.name(alias), this);
    }

    @Override
    public LTipoProc as(Name alias) {
        return new LTipoProc(alias, this);
    }

    @Override
    public LTipoProc as(Table<?> alias) {
        return new LTipoProc(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LTipoProc rename(String name) {
        return new LTipoProc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LTipoProc rename(Name name) {
        return new LTipoProc(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LTipoProc rename(Table<?> name) {
        return new LTipoProc(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoProc where(Condition condition) {
        return new LTipoProc(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoProc where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoProc where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoProc where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoProc where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoProc where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoProc where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LTipoProc where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoProc whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LTipoProc whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
