/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.ManifestazioniRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Manifestazioni extends TableImpl<ManifestazioniRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.manifestazioni</code>
     */
    public static final Manifestazioni MANIFESTAZIONI = new Manifestazioni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManifestazioniRecord> getRecordType() {
        return ManifestazioniRecord.class;
    }

    /**
     * The column <code>decreti.manifestazioni.id</code>.
     */
    public final TableField<ManifestazioniRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.manifestazioni.Codice_Identificativo</code>.
     */
    public final TableField<ManifestazioniRecord, String> CODICE_IDENTIFICATIVO = createField(DSL.name("Codice_Identificativo"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Richiedente_correlato</code>.
     */
    public final TableField<ManifestazioniRecord, String> RICHIEDENTE_CORRELATO = createField(DSL.name("Richiedente_correlato"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.manifestazioni.Codice_Fiscale_del_Richiedente</code>.
     */
    public final TableField<ManifestazioniRecord, String> CODICE_FISCALE_DEL_RICHIEDENTE = createField(DSL.name("Codice_Fiscale_del_Richiedente"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Tipo_Dichiarante</code>.
     */
    public final TableField<ManifestazioniRecord, String> TIPO_DICHIARANTE = createField(DSL.name("Tipo_Dichiarante"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Data_Trasmissione</code>.
     */
    public final TableField<ManifestazioniRecord, String> DATA_TRASMISSIONE = createField(DSL.name("Data_Trasmissione"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Numero_Protocollo</code>.
     */
    public final TableField<ManifestazioniRecord, String> NUMERO_PROTOCOLLO = createField(DSL.name("Numero_Protocollo"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Data_Protocollazione</code>.
     */
    public final TableField<ManifestazioniRecord, String> DATA_PROTOCOLLAZIONE = createField(DSL.name("Data_Protocollazione"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Edificio</code>.
     */
    public final TableField<ManifestazioniRecord, String> EDIFICIO = createField(DSL.name("Edificio"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Indirizzo_Intervento</code>.
     */
    public final TableField<ManifestazioniRecord, String> INDIRIZZO_INTERVENTO = createField(DSL.name("Indirizzo_Intervento"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Numero_Civico</code>.
     */
    public final TableField<ManifestazioniRecord, String> NUMERO_CIVICO = createField(DSL.name("Numero_Civico"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Foglio</code>.
     */
    public final TableField<ManifestazioniRecord, String> FOGLIO = createField(DSL.name("Foglio"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Part</code>.
     */
    public final TableField<ManifestazioniRecord, String> PART = createField(DSL.name("Part"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.numero_ui</code>.
     */
    public final TableField<ManifestazioniRecord, String> NUMERO_UI = createField(DSL.name("numero_ui"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.ui_con_cas</code>.
     */
    public final TableField<ManifestazioniRecord, String> UI_CON_CAS = createField(DSL.name("ui_con_cas"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.ui_con_sae</code>.
     */
    public final TableField<ManifestazioniRecord, String> UI_CON_SAE = createField(DSL.name("ui_con_sae"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.manifestazioni.ui_con_delocalizzazione_temporanea</code>.
     */
    public final TableField<ManifestazioniRecord, String> UI_CON_DELOCALIZZAZIONE_TEMPORANEA = createField(DSL.name("ui_con_delocalizzazione_temporanea"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.manifestazioni.Superficie_Complessiva_Edificio</code>.
     */
    public final TableField<ManifestazioniRecord, String> SUPERFICIE_COMPLESSIVA_EDIFICIO = createField(DSL.name("Superficie_Complessiva_Edificio"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.manifestazioni.Livello_Operativo_Presunto</code>.
     */
    public final TableField<ManifestazioniRecord, String> LIVELLO_OPERATIVO_PRESUNTO = createField(DSL.name("Livello_Operativo_Presunto"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Importo_Presunto</code>.
     */
    public final TableField<ManifestazioniRecord, BigDecimal> IMPORTO_PRESUNTO = createField(DSL.name("Importo_Presunto"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Importo_Dichiarato</code>.
     */
    public final TableField<ManifestazioniRecord, BigDecimal> IMPORTO_DICHIARATO = createField(DSL.name("Importo_Dichiarato"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>decreti.manifestazioni.Comune</code>.
     */
    public final TableField<ManifestazioniRecord, String> COMUNE = createField(DSL.name("Comune"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.manifestazioni.note_usr_abruzzo</code>.
     */
    public final TableField<ManifestazioniRecord, String> NOTE_USR_ABRUZZO = createField(DSL.name("note_usr_abruzzo"), SQLDataType.VARCHAR(256).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private Manifestazioni(Name alias, Table<ManifestazioniRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Manifestazioni(Name alias, Table<ManifestazioniRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.manifestazioni</code> table reference
     */
    public Manifestazioni(String alias) {
        this(DSL.name(alias), MANIFESTAZIONI);
    }

    /**
     * Create an aliased <code>decreti.manifestazioni</code> table reference
     */
    public Manifestazioni(Name alias) {
        this(alias, MANIFESTAZIONI);
    }

    /**
     * Create a <code>decreti.manifestazioni</code> table reference
     */
    public Manifestazioni() {
        this(DSL.name("manifestazioni"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MANIFESTAZIONI_PK_CODINE_MAN);
    }

    @Override
    public Identity<ManifestazioniRecord, Integer> getIdentity() {
        return (Identity<ManifestazioniRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ManifestazioniRecord> getPrimaryKey() {
        return Keys.KEY_MANIFESTAZIONI_PRIMARY;
    }

    @Override
    public Manifestazioni as(String alias) {
        return new Manifestazioni(DSL.name(alias), this);
    }

    @Override
    public Manifestazioni as(Name alias) {
        return new Manifestazioni(alias, this);
    }

    @Override
    public Manifestazioni as(Table<?> alias) {
        return new Manifestazioni(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Manifestazioni rename(String name) {
        return new Manifestazioni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Manifestazioni rename(Name name) {
        return new Manifestazioni(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Manifestazioni rename(Table<?> name) {
        return new Manifestazioni(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manifestazioni where(Condition condition) {
        return new Manifestazioni(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manifestazioni where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manifestazioni where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manifestazioni where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manifestazioni where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manifestazioni where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manifestazioni where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Manifestazioni where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manifestazioni whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Manifestazioni whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
