/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.ManifestazioniCatRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ManifestazioniCat extends TableImpl<ManifestazioniCatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.manifestazioni_cat</code>
     */
    public static final ManifestazioniCat MANIFESTAZIONI_CAT = new ManifestazioniCat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManifestazioniCatRecord> getRecordType() {
        return ManifestazioniCatRecord.class;
    }

    /**
     * The column <code>decreti.manifestazioni_cat.id</code>.
     */
    public final TableField<ManifestazioniCatRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.manifestazioni_cat.codice</code>.
     */
    public final TableField<ManifestazioniCatRecord, String> CODICE = createField(DSL.name("codice"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>decreti.manifestazioni_cat.istat</code>.
     */
    public final TableField<ManifestazioniCatRecord, Integer> ISTAT = createField(DSL.name("istat"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.manifestazioni_cat.foglio</code>.
     */
    public final TableField<ManifestazioniCatRecord, String> FOGLIO = createField(DSL.name("foglio"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>decreti.manifestazioni_cat.part</code>.
     */
    public final TableField<ManifestazioniCatRecord, String> PART = createField(DSL.name("part"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    private ManifestazioniCat(Name alias, Table<ManifestazioniCatRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ManifestazioniCat(Name alias, Table<ManifestazioniCatRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.manifestazioni_cat</code> table reference
     */
    public ManifestazioniCat(String alias) {
        this(DSL.name(alias), MANIFESTAZIONI_CAT);
    }

    /**
     * Create an aliased <code>decreti.manifestazioni_cat</code> table reference
     */
    public ManifestazioniCat(Name alias) {
        this(alias, MANIFESTAZIONI_CAT);
    }

    /**
     * Create a <code>decreti.manifestazioni_cat</code> table reference
     */
    public ManifestazioniCat() {
        this(DSL.name("manifestazioni_cat"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MANIFESTAZIONI_CAT_PK_MAN);
    }

    @Override
    public Identity<ManifestazioniCatRecord, Integer> getIdentity() {
        return (Identity<ManifestazioniCatRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ManifestazioniCatRecord> getPrimaryKey() {
        return Keys.KEY_MANIFESTAZIONI_CAT_PRIMARY;
    }

    @Override
    public ManifestazioniCat as(String alias) {
        return new ManifestazioniCat(DSL.name(alias), this);
    }

    @Override
    public ManifestazioniCat as(Name alias) {
        return new ManifestazioniCat(alias, this);
    }

    @Override
    public ManifestazioniCat as(Table<?> alias) {
        return new ManifestazioniCat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ManifestazioniCat rename(String name) {
        return new ManifestazioniCat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ManifestazioniCat rename(Name name) {
        return new ManifestazioniCat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ManifestazioniCat rename(Table<?> name) {
        return new ManifestazioniCat(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ManifestazioniCat where(Condition condition) {
        return new ManifestazioniCat(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ManifestazioniCat where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ManifestazioniCat where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ManifestazioniCat where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ManifestazioniCat where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ManifestazioniCat where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ManifestazioniCat where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ManifestazioniCat where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ManifestazioniCat whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ManifestazioniCat whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
