/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.tables.records.MembroRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Membro extends TableImpl<MembroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.membro</code>
     */
    public static final Membro MEMBRO = new Membro();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MembroRecord> getRecordType() {
        return MembroRecord.class;
    }

    /**
     * The column <code>decreti.membro.id_utente</code>.
     */
    public final TableField<MembroRecord, Integer> ID_UTENTE = createField(DSL.name("id_utente"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.membro.id_gruppo</code>.
     */
    public final TableField<MembroRecord, String> ID_GRUPPO = createField(DSL.name("id_gruppo"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>decreti.membro.data_inizio</code>.
     */
    public final TableField<MembroRecord, LocalDate> DATA_INIZIO = createField(DSL.name("data_inizio"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>decreti.membro.data_fine</code>.
     */
    public final TableField<MembroRecord, LocalDate> DATA_FINE = createField(DSL.name("data_fine"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    private Membro(Name alias, Table<MembroRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Membro(Name alias, Table<MembroRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.membro</code> table reference
     */
    public Membro(String alias) {
        this(DSL.name(alias), MEMBRO);
    }

    /**
     * Create an aliased <code>decreti.membro</code> table reference
     */
    public Membro(Name alias) {
        this(alias, MEMBRO);
    }

    /**
     * Create a <code>decreti.membro</code> table reference
     */
    public Membro() {
        this(DSL.name("membro"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MEMBRO_PK_MEMBRO);
    }

    @Override
    public Membro as(String alias) {
        return new Membro(DSL.name(alias), this);
    }

    @Override
    public Membro as(Name alias) {
        return new Membro(alias, this);
    }

    @Override
    public Membro as(Table<?> alias) {
        return new Membro(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Membro rename(String name) {
        return new Membro(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Membro rename(Name name) {
        return new Membro(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Membro rename(Table<?> name) {
        return new Membro(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Membro where(Condition condition) {
        return new Membro(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Membro where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Membro where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Membro where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Membro where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Membro where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Membro where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Membro where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Membro whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Membro whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
