/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.MonAssegnazioneGeneraleRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonAssegnazioneGenerale extends TableImpl<MonAssegnazioneGeneraleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.mon_assegnazione_generale</code>
     */
    public static final MonAssegnazioneGenerale MON_ASSEGNAZIONE_GENERALE = new MonAssegnazioneGenerale();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MonAssegnazioneGeneraleRecord> getRecordType() {
        return MonAssegnazioneGeneraleRecord.class;
    }

    /**
     * The column <code>decreti.mon_assegnazione_generale.id</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.mon_assegnazione_generale.ID_Pratica</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, Integer> ID_PRATICA = createField(DSL.name("ID_Pratica"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.mon_assegnazione_generale.id_neve</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> ID_NEVE = createField(DSL.name("id_neve"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_assegnazione_generale.intestatario</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> INTESTATARIO = createField(DSL.name("intestatario"), SQLDataType.VARCHAR(44).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_assegnazione_generale.comune</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> COMUNE = createField(DSL.name("comune"), SQLDataType.VARCHAR(34).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_assegnazione_generale.istruttore_rp</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> ISTRUTTORE_RP = createField(DSL.name("istruttore_rp"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.mon_assegnazione_generale.data_assegnazione_ita</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> DATA_ASSEGNAZIONE_ITA = createField(DSL.name("data_assegnazione_ita"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.mon_assegnazione_generale.data_assegnazione_testo</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> DATA_ASSEGNAZIONE_TESTO = createField(DSL.name("data_assegnazione_testo"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.mon_assegnazione_generale.data_assegnazione</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, LocalDate> DATA_ASSEGNAZIONE = createField(DSL.name("data_assegnazione"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>decreti.mon_assegnazione_generale.note</code>.
     */
    public final TableField<MonAssegnazioneGeneraleRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private MonAssegnazioneGenerale(Name alias, Table<MonAssegnazioneGeneraleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MonAssegnazioneGenerale(Name alias, Table<MonAssegnazioneGeneraleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.mon_assegnazione_generale</code> table
     * reference
     */
    public MonAssegnazioneGenerale(String alias) {
        this(DSL.name(alias), MON_ASSEGNAZIONE_GENERALE);
    }

    /**
     * Create an aliased <code>decreti.mon_assegnazione_generale</code> table
     * reference
     */
    public MonAssegnazioneGenerale(Name alias) {
        this(alias, MON_ASSEGNAZIONE_GENERALE);
    }

    /**
     * Create a <code>decreti.mon_assegnazione_generale</code> table reference
     */
    public MonAssegnazioneGenerale() {
        this(DSL.name("mon_assegnazione_generale"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<MonAssegnazioneGeneraleRecord, Integer> getIdentity() {
        return (Identity<MonAssegnazioneGeneraleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MonAssegnazioneGeneraleRecord> getPrimaryKey() {
        return Keys.KEY_MON_ASSEGNAZIONE_GENERALE_PRIMARY;
    }

    @Override
    public MonAssegnazioneGenerale as(String alias) {
        return new MonAssegnazioneGenerale(DSL.name(alias), this);
    }

    @Override
    public MonAssegnazioneGenerale as(Name alias) {
        return new MonAssegnazioneGenerale(alias, this);
    }

    @Override
    public MonAssegnazioneGenerale as(Table<?> alias) {
        return new MonAssegnazioneGenerale(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MonAssegnazioneGenerale rename(String name) {
        return new MonAssegnazioneGenerale(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonAssegnazioneGenerale rename(Name name) {
        return new MonAssegnazioneGenerale(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonAssegnazioneGenerale rename(Table<?> name) {
        return new MonAssegnazioneGenerale(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonAssegnazioneGenerale where(Condition condition) {
        return new MonAssegnazioneGenerale(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonAssegnazioneGenerale where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonAssegnazioneGenerale where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonAssegnazioneGenerale where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonAssegnazioneGenerale where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonAssegnazioneGenerale where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonAssegnazioneGenerale where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonAssegnazioneGenerale where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonAssegnazioneGenerale whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonAssegnazioneGenerale whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
