/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.tables.records.MonElencoProgettiNeveRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonElencoProgettiNeve extends TableImpl<MonElencoProgettiNeveRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.mon_elenco_progetti_neve</code>
     */
    public static final MonElencoProgettiNeve MON_ELENCO_PROGETTI_NEVE = new MonElencoProgettiNeve();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MonElencoProgettiNeveRecord> getRecordType() {
        return MonElencoProgettiNeveRecord.class;
    }

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.ID</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.id_comune</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Integer> ID_COMUNE = createField(DSL.name("id_comune"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.COMUNE</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> COMUNE = createField(DSL.name("COMUNE"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.PROV</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> PROV = createField(DSL.name("PROV"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.ID_PROVVISORIO</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> ID_PROVVISORIO = createField(DSL.name("ID_PROVVISORIO"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.prot_num</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> PROT_NUM = createField(DSL.name("prot_num"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.prot_data</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, LocalDateTime> PROT_DATA = createField(DSL.name("prot_data"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.denominazione</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> DENOMINAZIONE = createField(DSL.name("denominazione"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.pi</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> PI = createField(DSL.name("pi"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.cf</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> CF = createField(DSL.name("cf"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.mon_elenco_progetti_neve.importo_immobili</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Double> IMPORTO_IMMOBILI = createField(DSL.name("importo_immobili"), SQLDataType.DOUBLE.defaultValue(DSL.inline("NULL", SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.importo_mobili</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Double> IMPORTO_MOBILI = createField(DSL.name("importo_mobili"), SQLDataType.DOUBLE.defaultValue(DSL.inline("NULL", SQLDataType.DOUBLE)), this, "");

    /**
     * The column
     * <code>decreti.mon_elenco_progetti_neve.importo_demolizioni</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Double> IMPORTO_DEMOLIZIONI = createField(DSL.name("importo_demolizioni"), SQLDataType.DOUBLE.defaultValue(DSL.inline("NULL", SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.importo_scorte</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Double> IMPORTO_SCORTE = createField(DSL.name("importo_scorte"), SQLDataType.DOUBLE.defaultValue(DSL.inline("NULL", SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.tipo_intervento</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> TIPO_INTERVENTO = createField(DSL.name("tipo_intervento"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.indirizzo</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> INDIRIZZO = createField(DSL.name("indirizzo"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.stato_lavori</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> STATO_LAVORI = createField(DSL.name("stato_lavori"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.id_ricognizione</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Short> ID_RICOGNIZIONE = createField(DSL.name("id_ricognizione"), SQLDataType.SMALLINT.defaultValue(DSL.inline("NULL", SQLDataType.SMALLINT)), this, "");

    /**
     * The column
     * <code>decreti.mon_elenco_progetti_neve.ISTRUTTORIA_STATO</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> ISTRUTTORIA_STATO = createField(DSL.name("ISTRUTTORIA_STATO"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.SOMME
     * ACCANTONATE</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, Double> SOMME_ACCANTONATE = createField(DSL.name("SOMME ACCANTONATE"), SQLDataType.DOUBLE.defaultValue(DSL.inline("NULL", SQLDataType.DOUBLE)), this, "");

    /**
     * The column
     * <code>decreti.mon_elenco_progetti_neve.ISTRUTTORIA_TIPOLOGIA</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> ISTRUTTORIA_TIPOLOGIA = createField(DSL.name("ISTRUTTORIA_TIPOLOGIA"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.RESPONSABILE
     * UFFICIO</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> RESPONSABILE_UFFICIO = createField(DSL.name("RESPONSABILE UFFICIO"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_elenco_progetti_neve.RESPONSABILE
     * UFFICIO2</code>.
     */
    public final TableField<MonElencoProgettiNeveRecord, String> RESPONSABILE_UFFICIO2 = createField(DSL.name("RESPONSABILE UFFICIO2"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private MonElencoProgettiNeve(Name alias, Table<MonElencoProgettiNeveRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MonElencoProgettiNeve(Name alias, Table<MonElencoProgettiNeveRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.mon_elenco_progetti_neve</code> table
     * reference
     */
    public MonElencoProgettiNeve(String alias) {
        this(DSL.name(alias), MON_ELENCO_PROGETTI_NEVE);
    }

    /**
     * Create an aliased <code>decreti.mon_elenco_progetti_neve</code> table
     * reference
     */
    public MonElencoProgettiNeve(Name alias) {
        this(alias, MON_ELENCO_PROGETTI_NEVE);
    }

    /**
     * Create a <code>decreti.mon_elenco_progetti_neve</code> table reference
     */
    public MonElencoProgettiNeve() {
        this(DSL.name("mon_elenco_progetti_neve"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public MonElencoProgettiNeve as(String alias) {
        return new MonElencoProgettiNeve(DSL.name(alias), this);
    }

    @Override
    public MonElencoProgettiNeve as(Name alias) {
        return new MonElencoProgettiNeve(alias, this);
    }

    @Override
    public MonElencoProgettiNeve as(Table<?> alias) {
        return new MonElencoProgettiNeve(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MonElencoProgettiNeve rename(String name) {
        return new MonElencoProgettiNeve(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonElencoProgettiNeve rename(Name name) {
        return new MonElencoProgettiNeve(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonElencoProgettiNeve rename(Table<?> name) {
        return new MonElencoProgettiNeve(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonElencoProgettiNeve where(Condition condition) {
        return new MonElencoProgettiNeve(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonElencoProgettiNeve where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonElencoProgettiNeve where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonElencoProgettiNeve where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonElencoProgettiNeve where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonElencoProgettiNeve where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonElencoProgettiNeve where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonElencoProgettiNeve where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonElencoProgettiNeve whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonElencoProgettiNeve whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
