/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.MonLivOpRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonLivOp extends TableImpl<MonLivOpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.mon_liv_op</code>
     */
    public static final MonLivOp MON_LIV_OP = new MonLivOp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MonLivOpRecord> getRecordType() {
        return MonLivOpRecord.class;
    }

    /**
     * The column <code>decreti.mon_liv_op.id_lo</code>.
     */
    public final TableField<MonLivOpRecord, Integer> ID_LO = createField(DSL.name("id_lo"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.mon_liv_op.id_vlo</code>.
     */
    public final TableField<MonLivOpRecord, String> ID_VLO = createField(DSL.name("id_vlo"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_liv_op.data istanza</code>.
     */
    public final TableField<MonLivOpRecord, String> DATA_ISTANZA = createField(DSL.name("data istanza"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_liv_op.comune</code>.
     */
    public final TableField<MonLivOpRecord, String> COMUNE = createField(DSL.name("comune"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_liv_op.istat_comune</code>.
     */
    public final TableField<MonLivOpRecord, String> ISTAT_COMUNE = createField(DSL.name("istat_comune"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_liv_op.fg</code>.
     */
    public final TableField<MonLivOpRecord, String> FG = createField(DSL.name("fg"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.mon_liv_op.part</code>.
     */
    public final TableField<MonLivOpRecord, String> PART = createField(DSL.name("part"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private MonLivOp(Name alias, Table<MonLivOpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MonLivOp(Name alias, Table<MonLivOpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.mon_liv_op</code> table reference
     */
    public MonLivOp(String alias) {
        this(DSL.name(alias), MON_LIV_OP);
    }

    /**
     * Create an aliased <code>decreti.mon_liv_op</code> table reference
     */
    public MonLivOp(Name alias) {
        this(alias, MON_LIV_OP);
    }

    /**
     * Create a <code>decreti.mon_liv_op</code> table reference
     */
    public MonLivOp() {
        this(DSL.name("mon_liv_op"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<MonLivOpRecord, Integer> getIdentity() {
        return (Identity<MonLivOpRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MonLivOpRecord> getPrimaryKey() {
        return Keys.KEY_MON_LIV_OP_PRIMARY;
    }

    @Override
    public MonLivOp as(String alias) {
        return new MonLivOp(DSL.name(alias), this);
    }

    @Override
    public MonLivOp as(Name alias) {
        return new MonLivOp(alias, this);
    }

    @Override
    public MonLivOp as(Table<?> alias) {
        return new MonLivOp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MonLivOp rename(String name) {
        return new MonLivOp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonLivOp rename(Name name) {
        return new MonLivOp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MonLivOp rename(Table<?> name) {
        return new MonLivOp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonLivOp where(Condition condition) {
        return new MonLivOp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonLivOp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonLivOp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonLivOp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonLivOp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonLivOp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonLivOp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MonLivOp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonLivOp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MonLivOp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
