/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.EsitiAttivazione.EsitiAttivazionePath;
import it.usr.web.usromniapp.domain.tables.LTipoPasso.LTipoPassoPath;
import it.usr.web.usromniapp.domain.tables.LTipoProc.LTipoProcPath;
import it.usr.web.usromniapp.domain.tables.ProcIter.ProcIterPath;
import it.usr.web.usromniapp.domain.tables.records.ProcEsitiRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcEsiti extends TableImpl<ProcEsitiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.proc_esiti</code>
     */
    public static final ProcEsiti PROC_ESITI = new ProcEsiti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcEsitiRecord> getRecordType() {
        return ProcEsitiRecord.class;
    }

    /**
     * The column <code>decreti.proc_esiti.id_esito</code>.
     */
    public final TableField<ProcEsitiRecord, Integer> ID_ESITO = createField(DSL.name("id_esito"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.proc_esiti.id_tipo_proc</code>.
     */
    public final TableField<ProcEsitiRecord, Integer> ID_TIPO_PROC = createField(DSL.name("id_tipo_proc"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.proc_esiti.codice</code>. 1 richiesta, 2 ammesso
     */
    public final TableField<ProcEsitiRecord, String> CODICE = createField(DSL.name("codice"), SQLDataType.VARCHAR(32).nullable(false), this, "1 richiesta, 2 ammesso");

    /**
     * The column <code>decreti.proc_esiti.descrizione</code>.
     */
    public final TableField<ProcEsitiRecord, String> DESCRIZIONE = createField(DSL.name("descrizione"), SQLDataType.VARCHAR(48).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.proc_esiti.visibile</code>. codice di visibilità
     * (0 non visibile, 1 visibile, 2 (es) non selezionabile, ecc.)
     */
    public final TableField<ProcEsitiRecord, Integer> VISIBILE = createField(DSL.name("visibile"), SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "codice di visibilità (0 non visibile, 1 visibile, 2 (es) non selezionabile, ecc.)");

    private ProcEsiti(Name alias, Table<ProcEsitiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcEsiti(Name alias, Table<ProcEsitiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.proc_esiti</code> table reference
     */
    public ProcEsiti(String alias) {
        this(DSL.name(alias), PROC_ESITI);
    }

    /**
     * Create an aliased <code>decreti.proc_esiti</code> table reference
     */
    public ProcEsiti(Name alias) {
        this(alias, PROC_ESITI);
    }

    /**
     * Create a <code>decreti.proc_esiti</code> table reference
     */
    public ProcEsiti() {
        this(DSL.name("proc_esiti"), null);
    }

    public <O extends Record> ProcEsiti(Table<O> path, ForeignKey<O, ProcEsitiRecord> childPath, InverseForeignKey<O, ProcEsitiRecord> parentPath) {
        super(path, childPath, parentPath, PROC_ESITI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProcEsitiPath extends ProcEsiti implements Path<ProcEsitiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProcEsitiPath(Table<O> path, ForeignKey<O, ProcEsitiRecord> childPath, InverseForeignKey<O, ProcEsitiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProcEsitiPath(Name alias, Table<ProcEsitiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProcEsitiPath as(String alias) {
            return new ProcEsitiPath(DSL.name(alias), this);
        }

        @Override
        public ProcEsitiPath as(Name alias) {
            return new ProcEsitiPath(alias, this);
        }

        @Override
        public ProcEsitiPath as(Table<?> alias) {
            return new ProcEsitiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROC_ESITI_FK_ESITI_TIPO_PROC_IDX);
    }

    @Override
    public Identity<ProcEsitiRecord, Integer> getIdentity() {
        return (Identity<ProcEsitiRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProcEsitiRecord> getPrimaryKey() {
        return Keys.KEY_PROC_ESITI_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProcEsitiRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ESITI_TIPO_PROC);
    }

    private transient LTipoProcPath _lTipoProc;

    /**
     * Get the implicit join path to the <code>decreti.l_tipo_proc</code> table.
     */
    public LTipoProcPath lTipoProc() {
        if (_lTipoProc == null)
            _lTipoProc = new LTipoProcPath(this, Keys.FK_ESITI_TIPO_PROC, null);

        return _lTipoProc;
    }

    private transient EsitiAttivazionePath _esitiAttivazione;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.esiti_attivazione</code> table
     */
    public EsitiAttivazionePath esitiAttivazione() {
        if (_esitiAttivazione == null)
            _esitiAttivazione = new EsitiAttivazionePath(this, null, Keys.FK_ESITIATTIVAZ_ESITI.getInverseKey());

        return _esitiAttivazione;
    }

    private transient ProcIterPath _procIter;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_iter</code>
     * table
     */
    public ProcIterPath procIter() {
        if (_procIter == null)
            _procIter = new ProcIterPath(this, null, Keys.FK_PROCITER_ESITO.getInverseKey());

        return _procIter;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>decreti.l_tipo_passo</code> table
     */
    public LTipoPassoPath lTipoPasso() {
        return esitiAttivazione().lTipoPasso();
    }

    @Override
    public ProcEsiti as(String alias) {
        return new ProcEsiti(DSL.name(alias), this);
    }

    @Override
    public ProcEsiti as(Name alias) {
        return new ProcEsiti(alias, this);
    }

    @Override
    public ProcEsiti as(Table<?> alias) {
        return new ProcEsiti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcEsiti rename(String name) {
        return new ProcEsiti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcEsiti rename(Name name) {
        return new ProcEsiti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcEsiti rename(Table<?> name) {
        return new ProcEsiti(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcEsiti where(Condition condition) {
        return new ProcEsiti(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcEsiti where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcEsiti where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcEsiti where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcEsiti where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcEsiti where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcEsiti where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcEsiti where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcEsiti whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcEsiti whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
