/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.Proc.ProcPath;
import it.usr.web.usromniapp.domain.tables.records.ProcCatRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcCat extends TableImpl<ProcCatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.proc_cat</code>
     */
    public static final ProcCat PROC_CAT = new ProcCat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcCatRecord> getRecordType() {
        return ProcCatRecord.class;
    }

    /**
     * The column <code>decreti.proc_cat.id_proc_cat</code>.
     */
    public final TableField<ProcCatRecord, Integer> ID_PROC_CAT = createField(DSL.name("id_proc_cat"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.proc_cat.id_proc</code>.
     */
    public final TableField<ProcCatRecord, Integer> ID_PROC = createField(DSL.name("id_proc"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_cat.attivo</code>.
     */
    public final TableField<ProcCatRecord, Integer> ATTIVO = createField(DSL.name("attivo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_cat.istat_comune</code>.
     */
    public final TableField<ProcCatRecord, String> ISTAT_COMUNE = createField(DSL.name("istat_comune"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.proc_cat.sezione</code>.
     */
    public final TableField<ProcCatRecord, String> SEZIONE = createField(DSL.name("sezione"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.proc_cat.foglio</code>.
     */
    public final TableField<ProcCatRecord, String> FOGLIO = createField(DSL.name("foglio"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.proc_cat.particella</code>.
     */
    public final TableField<ProcCatRecord, String> PARTICELLA = createField(DSL.name("particella"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private ProcCat(Name alias, Table<ProcCatRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcCat(Name alias, Table<ProcCatRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.proc_cat</code> table reference
     */
    public ProcCat(String alias) {
        this(DSL.name(alias), PROC_CAT);
    }

    /**
     * Create an aliased <code>decreti.proc_cat</code> table reference
     */
    public ProcCat(Name alias) {
        this(alias, PROC_CAT);
    }

    /**
     * Create a <code>decreti.proc_cat</code> table reference
     */
    public ProcCat() {
        this(DSL.name("proc_cat"), null);
    }

    public <O extends Record> ProcCat(Table<O> path, ForeignKey<O, ProcCatRecord> childPath, InverseForeignKey<O, ProcCatRecord> parentPath) {
        super(path, childPath, parentPath, PROC_CAT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProcCatPath extends ProcCat implements Path<ProcCatRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProcCatPath(Table<O> path, ForeignKey<O, ProcCatRecord> childPath, InverseForeignKey<O, ProcCatRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProcCatPath(Name alias, Table<ProcCatRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProcCatPath as(String alias) {
            return new ProcCatPath(DSL.name(alias), this);
        }

        @Override
        public ProcCatPath as(Name alias) {
            return new ProcCatPath(alias, this);
        }

        @Override
        public ProcCatPath as(Table<?> alias) {
            return new ProcCatPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROC_CAT_FK_PROCCAT_PROC_IDX);
    }

    @Override
    public Identity<ProcCatRecord, Integer> getIdentity() {
        return (Identity<ProcCatRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProcCatRecord> getPrimaryKey() {
        return Keys.KEY_PROC_CAT_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProcCatRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROCCAT_PROC);
    }

    private transient ProcPath _proc;

    /**
     * Get the implicit join path to the <code>decreti.proc</code> table.
     */
    public ProcPath proc() {
        if (_proc == null)
            _proc = new ProcPath(this, Keys.FK_PROCCAT_PROC, null);

        return _proc;
    }

    @Override
    public ProcCat as(String alias) {
        return new ProcCat(DSL.name(alias), this);
    }

    @Override
    public ProcCat as(Name alias) {
        return new ProcCat(alias, this);
    }

    @Override
    public ProcCat as(Table<?> alias) {
        return new ProcCat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcCat rename(String name) {
        return new ProcCat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcCat rename(Name name) {
        return new ProcCat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcCat rename(Table<?> name) {
        return new ProcCat(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcCat where(Condition condition) {
        return new ProcCat(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcCat where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcCat where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcCat where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcCat where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcCat where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcCat where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcCat where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcCat whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcCat whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
