/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.LRuolo.LRuoloPath;
import it.usr.web.usromniapp.domain.tables.LTipoProc.LTipoProcPath;
import it.usr.web.usromniapp.domain.tables.Proc.ProcPath;
import it.usr.web.usromniapp.domain.tables.Uffici.UfficiPath;
import it.usr.web.usromniapp.domain.tables.Utenti.UtentiPath;
import it.usr.web.usromniapp.domain.tables.records.ProcAclRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcAcl extends TableImpl<ProcAclRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.proc_acl</code>
     */
    public static final ProcAcl PROC_ACL = new ProcAcl();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcAclRecord> getRecordType() {
        return ProcAclRecord.class;
    }

    /**
     * The column <code>decreti.proc_acl.id_proc_acl</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_PROC_ACL = createField(DSL.name("id_proc_acl"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.proc_acl.id_tipo_proc</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_TIPO_PROC = createField(DSL.name("id_tipo_proc"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.id_proc</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_PROC = createField(DSL.name("id_proc"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.id_utente</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_UTENTE = createField(DSL.name("id_utente"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.id_ufficio</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_UFFICIO = createField(DSL.name("id_ufficio"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.id_ruolo</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_RUOLO = createField(DSL.name("id_ruolo"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.autorizzazioni</code>.
     */
    public final TableField<ProcAclRecord, Integer> AUTORIZZAZIONI = createField(DSL.name("autorizzazioni"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.proc_acl.id_utente_assegnante</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_UTENTE_ASSEGNANTE = createField(DSL.name("id_utente_assegnante"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.id_utente_delegante</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_UTENTE_DELEGANTE = createField(DSL.name("id_utente_delegante"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.id_utente_rimozione</code>.
     */
    public final TableField<ProcAclRecord, Integer> ID_UTENTE_RIMOZIONE = createField(DSL.name("id_utente_rimozione"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.proc_acl.data_assegnazione</code>.
     */
    public final TableField<ProcAclRecord, LocalDateTime> DATA_ASSEGNAZIONE = createField(DSL.name("data_assegnazione"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>decreti.proc_acl.data_subentro</code>.
     */
    public final TableField<ProcAclRecord, LocalDateTime> DATA_SUBENTRO = createField(DSL.name("data_subentro"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>decreti.proc_acl.data_rimozione</code>.
     */
    public final TableField<ProcAclRecord, LocalDateTime> DATA_RIMOZIONE = createField(DSL.name("data_rimozione"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>decreti.proc_acl.dataora</code>.
     */
    public final TableField<ProcAclRecord, LocalDateTime> DATAORA = createField(DSL.name("dataora"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>decreti.proc_acl.note</code>.
     */
    public final TableField<ProcAclRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private ProcAcl(Name alias, Table<ProcAclRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcAcl(Name alias, Table<ProcAclRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.proc_acl</code> table reference
     */
    public ProcAcl(String alias) {
        this(DSL.name(alias), PROC_ACL);
    }

    /**
     * Create an aliased <code>decreti.proc_acl</code> table reference
     */
    public ProcAcl(Name alias) {
        this(alias, PROC_ACL);
    }

    /**
     * Create a <code>decreti.proc_acl</code> table reference
     */
    public ProcAcl() {
        this(DSL.name("proc_acl"), null);
    }

    public <O extends Record> ProcAcl(Table<O> path, ForeignKey<O, ProcAclRecord> childPath, InverseForeignKey<O, ProcAclRecord> parentPath) {
        super(path, childPath, parentPath, PROC_ACL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProcAclPath extends ProcAcl implements Path<ProcAclRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProcAclPath(Table<O> path, ForeignKey<O, ProcAclRecord> childPath, InverseForeignKey<O, ProcAclRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProcAclPath(Name alias, Table<ProcAclRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProcAclPath as(String alias) {
            return new ProcAclPath(DSL.name(alias), this);
        }

        @Override
        public ProcAclPath as(Name alias) {
            return new ProcAclPath(alias, this);
        }

        @Override
        public ProcAclPath as(Table<?> alias) {
            return new ProcAclPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROC_ACL_FK_PROCACL_PROC_IDX, Indexes.PROC_ACL_FK_PROCACL_RUOLO_IDX, Indexes.PROC_ACL_FK_PROCACL_TIPOPROC_IDX, Indexes.PROC_ACL_FK_PROCACL_UFFICIO_IDX, Indexes.PROC_ACL_FK_PROCACL_UTENTE_ASS_IDX, Indexes.PROC_ACL_FK_PROCACL_UTENTE_DELEG_IDX, Indexes.PROC_ACL_FK_PROCACL_UTENTE_IDX, Indexes.PROC_ACL_FK_PROCACL_UTENTE_RIM_IDX, Indexes.PROC_ACL_IDX_PROCACL_DATAASSRIM);
    }

    @Override
    public Identity<ProcAclRecord, Integer> getIdentity() {
        return (Identity<ProcAclRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProcAclRecord> getPrimaryKey() {
        return Keys.KEY_PROC_ACL_PRIMARY;
    }

    @Override
    public List<ForeignKey<ProcAclRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROCACL_PROC, Keys.FK_PROCACL_RUOLO, Keys.FK_PROCACL_TIPOPROC, Keys.FK_PROCACL_UFFICIO, Keys.FK_PROCACL_UTENTE, Keys.FK_PROCACL_UTENTE_ASS, Keys.FK_PROCACL_UTENTE_DELEG, Keys.FK_PROCACL_UTENTE_RIM);
    }

    private transient ProcPath _proc;

    /**
     * Get the implicit join path to the <code>decreti.proc</code> table.
     */
    public ProcPath proc() {
        if (_proc == null)
            _proc = new ProcPath(this, Keys.FK_PROCACL_PROC, null);

        return _proc;
    }

    private transient LRuoloPath _lRuolo;

    /**
     * Get the implicit join path to the <code>decreti.l_ruolo</code> table.
     */
    public LRuoloPath lRuolo() {
        if (_lRuolo == null)
            _lRuolo = new LRuoloPath(this, Keys.FK_PROCACL_RUOLO, null);

        return _lRuolo;
    }

    private transient LTipoProcPath _lTipoProc;

    /**
     * Get the implicit join path to the <code>decreti.l_tipo_proc</code> table.
     */
    public LTipoProcPath lTipoProc() {
        if (_lTipoProc == null)
            _lTipoProc = new LTipoProcPath(this, Keys.FK_PROCACL_TIPOPROC, null);

        return _lTipoProc;
    }

    private transient UfficiPath _uffici;

    /**
     * Get the implicit join path to the <code>decreti.uffici</code> table.
     */
    public UfficiPath uffici() {
        if (_uffici == null)
            _uffici = new UfficiPath(this, Keys.FK_PROCACL_UFFICIO, null);

        return _uffici;
    }

    private transient UtentiPath _fkProcaclUtente;

    /**
     * Get the implicit join path to the <code>decreti.utenti</code> table, via
     * the <code>fk_procacl_utente</code> key.
     */
    public UtentiPath fkProcaclUtente() {
        if (_fkProcaclUtente == null)
            _fkProcaclUtente = new UtentiPath(this, Keys.FK_PROCACL_UTENTE, null);

        return _fkProcaclUtente;
    }

    private transient UtentiPath _fkProcaclUtenteAss;

    /**
     * Get the implicit join path to the <code>decreti.utenti</code> table, via
     * the <code>fk_procacl_utente_ass</code> key.
     */
    public UtentiPath fkProcaclUtenteAss() {
        if (_fkProcaclUtenteAss == null)
            _fkProcaclUtenteAss = new UtentiPath(this, Keys.FK_PROCACL_UTENTE_ASS, null);

        return _fkProcaclUtenteAss;
    }

    private transient UtentiPath _fkProcaclUtenteDeleg;

    /**
     * Get the implicit join path to the <code>decreti.utenti</code> table, via
     * the <code>fk_procacl_utente_deleg</code> key.
     */
    public UtentiPath fkProcaclUtenteDeleg() {
        if (_fkProcaclUtenteDeleg == null)
            _fkProcaclUtenteDeleg = new UtentiPath(this, Keys.FK_PROCACL_UTENTE_DELEG, null);

        return _fkProcaclUtenteDeleg;
    }

    private transient UtentiPath _fkProcaclUtenteRim;

    /**
     * Get the implicit join path to the <code>decreti.utenti</code> table, via
     * the <code>fk_procacl_utente_rim</code> key.
     */
    public UtentiPath fkProcaclUtenteRim() {
        if (_fkProcaclUtenteRim == null)
            _fkProcaclUtenteRim = new UtentiPath(this, Keys.FK_PROCACL_UTENTE_RIM, null);

        return _fkProcaclUtenteRim;
    }

    @Override
    public ProcAcl as(String alias) {
        return new ProcAcl(DSL.name(alias), this);
    }

    @Override
    public ProcAcl as(Name alias) {
        return new ProcAcl(alias, this);
    }

    @Override
    public ProcAcl as(Table<?> alias) {
        return new ProcAcl(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcAcl rename(String name) {
        return new ProcAcl(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcAcl rename(Name name) {
        return new ProcAcl(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcAcl rename(Table<?> name) {
        return new ProcAcl(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcAcl where(Condition condition) {
        return new ProcAcl(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcAcl where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcAcl where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcAcl where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcAcl where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcAcl where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcAcl where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcAcl where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcAcl whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcAcl whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
