/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.tables.records.ProgettiPrivataRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgettiPrivata extends TableImpl<ProgettiPrivataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.progetti_privata</code>
     */
    public static final ProgettiPrivata PROGETTI_PRIVATA = new ProgettiPrivata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProgettiPrivataRecord> getRecordType() {
        return ProgettiPrivataRecord.class;
    }

    /**
     * The column <code>decreti.progetti_privata.ID_Pratica</code>.
     */
    public final TableField<ProgettiPrivataRecord, Integer> ID_PRATICA = createField(DSL.name("ID_Pratica"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.progetti_privata.Comune</code>.
     */
    public final TableField<ProgettiPrivataRecord, String> COMUNE = createField(DSL.name("Comune"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.progetti_privata.destinatario</code>.
     */
    public final TableField<ProgettiPrivataRecord, String> DESTINATARIO = createField(DSL.name("destinatario"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.progetti_privata.id_tipo_proprieta</code>.
     */
    public final TableField<ProgettiPrivataRecord, Integer> ID_TIPO_PROPRIETA = createField(DSL.name("id_tipo_proprieta"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.progetti_privata.id_tipo_pratica</code>.
     */
    public final TableField<ProgettiPrivataRecord, Integer> ID_TIPO_PRATICA = createField(DSL.name("id_tipo_pratica"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>decreti.progetti_privata.id_ordinanza_riferimento</code>.
     */
    public final TableField<ProgettiPrivataRecord, Integer> ID_ORDINANZA_RIFERIMENTO = createField(DSL.name("id_ordinanza_riferimento"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.progetti_privata.stato</code>.
     */
    public final TableField<ProgettiPrivataRecord, Integer> STATO = createField(DSL.name("stato"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.progetti_privata.Abit_Principale</code>.
     */
    public final TableField<ProgettiPrivataRecord, String> ABIT_PRINCIPALE = createField(DSL.name("Abit_Principale"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.progetti_privata.Assistenza</code>.
     */
    public final TableField<ProgettiPrivataRecord, String> ASSISTENZA = createField(DSL.name("Assistenza"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.progetti_privata.Att_Produttiva</code>.
     */
    public final TableField<ProgettiPrivataRecord, String> ATT_PRODUTTIVA = createField(DSL.name("Att_Produttiva"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.progetti_privata.ord100</code>.
     */
    public final TableField<ProgettiPrivataRecord, Integer> ORD100 = createField(DSL.name("ord100"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    private ProgettiPrivata(Name alias, Table<ProgettiPrivataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProgettiPrivata(Name alias, Table<ProgettiPrivataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.progetti_privata</code> table reference
     */
    public ProgettiPrivata(String alias) {
        this(DSL.name(alias), PROGETTI_PRIVATA);
    }

    /**
     * Create an aliased <code>decreti.progetti_privata</code> table reference
     */
    public ProgettiPrivata(Name alias) {
        this(alias, PROGETTI_PRIVATA);
    }

    /**
     * Create a <code>decreti.progetti_privata</code> table reference
     */
    public ProgettiPrivata() {
        this(DSL.name("progetti_privata"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public ProgettiPrivata as(String alias) {
        return new ProgettiPrivata(DSL.name(alias), this);
    }

    @Override
    public ProgettiPrivata as(Name alias) {
        return new ProgettiPrivata(alias, this);
    }

    @Override
    public ProgettiPrivata as(Table<?> alias) {
        return new ProgettiPrivata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgettiPrivata rename(String name) {
        return new ProgettiPrivata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgettiPrivata rename(Name name) {
        return new ProgettiPrivata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProgettiPrivata rename(Table<?> name) {
        return new ProgettiPrivata(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgettiPrivata where(Condition condition) {
        return new ProgettiPrivata(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgettiPrivata where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgettiPrivata where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgettiPrivata where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgettiPrivata where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgettiPrivata where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgettiPrivata where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProgettiPrivata where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgettiPrivata whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProgettiPrivata whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
