/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.ReportcommissarioworkRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reportcommissariowork extends TableImpl<ReportcommissarioworkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.reportcommissariowork</code>
     */
    public static final Reportcommissariowork REPORTCOMMISSARIOWORK = new Reportcommissariowork();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportcommissarioworkRecord> getRecordType() {
        return ReportcommissarioworkRecord.class;
    }

    /**
     * The column <code>decreti.reportcommissariowork.id</code>.
     */
    public final TableField<ReportcommissarioworkRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.reportcommissariowork.step</code>.
     */
    public final TableField<ReportcommissarioworkRecord, Integer> STEP = createField(DSL.name("step"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.reportcommissariowork.total</code>.
     */
    public final TableField<ReportcommissarioworkRecord, Integer> TOTAL = createField(DSL.name("total"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.reportcommissariowork.dt</code>.
     */
    public final TableField<ReportcommissarioworkRecord, LocalDateTime> DT = createField(DSL.name("dt"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>decreti.reportcommissariowork.completed</code>.
     */
    public final TableField<ReportcommissarioworkRecord, Integer> COMPLETED = createField(DSL.name("completed"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>decreti.reportcommissariowork.error</code>.
     */
    public final TableField<ReportcommissarioworkRecord, String> ERROR = createField(DSL.name("error"), SQLDataType.VARCHAR(2000).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private Reportcommissariowork(Name alias, Table<ReportcommissarioworkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Reportcommissariowork(Name alias, Table<ReportcommissarioworkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.reportcommissariowork</code> table
     * reference
     */
    public Reportcommissariowork(String alias) {
        this(DSL.name(alias), REPORTCOMMISSARIOWORK);
    }

    /**
     * Create an aliased <code>decreti.reportcommissariowork</code> table
     * reference
     */
    public Reportcommissariowork(Name alias) {
        this(alias, REPORTCOMMISSARIOWORK);
    }

    /**
     * Create a <code>decreti.reportcommissariowork</code> table reference
     */
    public Reportcommissariowork() {
        this(DSL.name("reportcommissariowork"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public UniqueKey<ReportcommissarioworkRecord> getPrimaryKey() {
        return Keys.KEY_REPORTCOMMISSARIOWORK_PRIMARY;
    }

    @Override
    public Reportcommissariowork as(String alias) {
        return new Reportcommissariowork(DSL.name(alias), this);
    }

    @Override
    public Reportcommissariowork as(Name alias) {
        return new Reportcommissariowork(alias, this);
    }

    @Override
    public Reportcommissariowork as(Table<?> alias) {
        return new Reportcommissariowork(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reportcommissariowork rename(String name) {
        return new Reportcommissariowork(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reportcommissariowork rename(Name name) {
        return new Reportcommissariowork(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reportcommissariowork rename(Table<?> name) {
        return new Reportcommissariowork(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reportcommissariowork where(Condition condition) {
        return new Reportcommissariowork(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reportcommissariowork where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reportcommissariowork where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reportcommissariowork where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reportcommissariowork where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reportcommissariowork where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reportcommissariowork where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reportcommissariowork where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reportcommissariowork whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reportcommissariowork whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
