/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.StatoProgettiRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StatoProgetti extends TableImpl<StatoProgettiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.stato_progetti</code>
     */
    public static final StatoProgetti STATO_PROGETTI = new StatoProgetti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatoProgettiRecord> getRecordType() {
        return StatoProgettiRecord.class;
    }

    /**
     * The column <code>decreti.stato_progetti.id</code>.
     */
    public final TableField<StatoProgettiRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.stato_progetti.id_pratica</code>.
     */
    public final TableField<StatoProgettiRecord, String> ID_PRATICA = createField(DSL.name("id_pratica"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.progetto_annullato</code>.
     */
    public final TableField<StatoProgettiRecord, String> PROGETTO_ANNULLATO = createField(DSL.name("progetto_annullato"), SQLDataType.VARCHAR(18).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.su_report_commissario</code>.
     */
    public final TableField<StatoProgettiRecord, String> SU_REPORT_COMMISSARIO = createField(DSL.name("su_report_commissario"), SQLDataType.VARCHAR(21).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.ordinanza</code>.
     */
    public final TableField<StatoProgettiRecord, String> ORDINANZA = createField(DSL.name("ordinanza"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.liv_operativo_richiesto</code>.
     */
    public final TableField<StatoProgettiRecord, String> LIV_OPERATIVO_RICHIESTO = createField(DSL.name("liv_operativo_richiesto"), SQLDataType.VARCHAR(30).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.istat_comune</code>.
     */
    public final TableField<StatoProgettiRecord, String> ISTAT_COMUNE = createField(DSL.name("istat_comune"), SQLDataType.VARCHAR(12).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.comune</code>.
     */
    public final TableField<StatoProgettiRecord, String> COMUNE = createField(DSL.name("comune"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.intestatario</code>.
     */
    public final TableField<StatoProgettiRecord, String> INTESTATARIO = createField(DSL.name("intestatario"), SQLDataType.VARCHAR(70).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.foglio</code>.
     */
    public final TableField<StatoProgettiRecord, String> FOGLIO = createField(DSL.name("foglio"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.part</code>.
     */
    public final TableField<StatoProgettiRecord, String> PART = createField(DSL.name("part"), SQLDataType.VARCHAR(30).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.assegnazioni_storico_privata2</code>.
     */
    public final TableField<StatoProgettiRecord, String> ASSEGNAZIONI_STORICO_PRIVATA2 = createField(DSL.name("assegnazioni_storico_privata2"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.data_assegnazione_privata2</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_ASSEGNAZIONE_PRIVATA2 = createField(DSL.name("data_assegnazione_privata2"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.istruttore_tecnico</code>.
     */
    public final TableField<StatoProgettiRecord, String> ISTRUTTORE_TECNICO = createField(DSL.name("istruttore_tecnico"), SQLDataType.VARCHAR(70).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.istruttore_amministrativo</code>.
     */
    public final TableField<StatoProgettiRecord, String> ISTRUTTORE_AMMINISTRATIVO = createField(DSL.name("istruttore_amministrativo"), SQLDataType.VARCHAR(70).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.assegnazioni_storico_direttore</code>.
     */
    public final TableField<StatoProgettiRecord, String> ASSEGNAZIONI_STORICO_DIRETTORE = createField(DSL.name("assegnazioni_storico_direttore"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.data_assegnazioni_storico_direttore</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_ASSEGNAZIONI_STORICO_DIRETTORE = createField(DSL.name("data_assegnazioni_storico_direttore"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.assegnatario_direttore</code>.
     */
    public final TableField<StatoProgettiRecord, String> ASSEGNATARIO_DIRETTORE = createField(DSL.name("assegnatario_direttore"), SQLDataType.VARCHAR(70).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.supervisore_pigreco</code>.
     */
    public final TableField<StatoProgettiRecord, String> SUPERVISORE_PIGRECO = createField(DSL.name("supervisore_pigreco"), SQLDataType.VARCHAR(70).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.istruttore_pigreco</code>.
     */
    public final TableField<StatoProgettiRecord, String> ISTRUTTORE_PIGRECO = createField(DSL.name("istruttore_pigreco"), SQLDataType.VARCHAR(70).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_prima_istanza</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_PRIMA_ISTANZA = createField(DSL.name("data_prima_istanza"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_ultimo_deposito</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_ULTIMO_DEPOSITO = createField(DSL.name("data_ultimo_deposito"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_prima_comunicazione
     * usr</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_PRIMA_COMUNICAZIONE_USR = createField(DSL.name("data_prima_comunicazione usr"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.ultima_comunicazione_usr</code>.
     */
    public final TableField<StatoProgettiRecord, String> ULTIMA_COMUNICAZIONE_USR = createField(DSL.name("ultima_comunicazione_usr"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.data_ultima_comunicazione_usr</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_ULTIMA_COMUNICAZIONE_USR = createField(DSL.name("data_ultima_comunicazione_usr"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.numero_depositi</code>.
     */
    public final TableField<StatoProgettiRecord, Integer> NUMERO_DEPOSITI = createField(DSL.name("numero_depositi"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.stato_progetti.stato</code>.
     */
    public final TableField<StatoProgettiRecord, String> STATO = createField(DSL.name("stato"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.data_conclusione_procedimento</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_CONCLUSIONE_PROCEDIMENTO = createField(DSL.name("data_conclusione_procedimento"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.giorni_da_ultimo_deposito</code>.
     */
    public final TableField<StatoProgettiRecord, Integer> GIORNI_DA_ULTIMO_DEPOSITO = createField(DSL.name("giorni_da_ultimo_deposito"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.giorni_da_comunicazione_usr</code>.
     */
    public final TableField<StatoProgettiRecord, Integer> GIORNI_DA_COMUNICAZIONE_USR = createField(DSL.name("giorni_da_comunicazione_usr"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.data_deposito_post_rigetto</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_DEPOSITO_POST_RIGETTO = createField(DSL.name("data_deposito_post_rigetto"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>decreti.stato_progetti.ordinanza_registro_decreti</code>.
     */
    public final TableField<StatoProgettiRecord, String> ORDINANZA_REGISTRO_DECRETI = createField(DSL.name("ordinanza_registro_decreti"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_rif_inizio_lavori</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_RIF_INIZIO_LAVORI = createField(DSL.name("data_rif_inizio_lavori"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_presentazione_sal0</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_PRESENTAZIONE_SAL0 = createField(DSL.name("data_presentazione_sal0"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_presentazione_sal</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_PRESENTAZIONE_SAL = createField(DSL.name("data_presentazione_sal"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_sal_finale</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_SAL_FINALE = createField(DSL.name("data_sal_finale"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.stato_progetti.durata_lavori</code>.
     */
    public final TableField<StatoProgettiRecord, Integer> DURATA_LAVORI = createField(DSL.name("durata_lavori"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.stato_progetti.data_presunta_fine_lavori</code>.
     */
    public final TableField<StatoProgettiRecord, String> DATA_PRESUNTA_FINE_LAVORI = createField(DSL.name("data_presunta_fine_lavori"), SQLDataType.VARCHAR(15).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private StatoProgetti(Name alias, Table<StatoProgettiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StatoProgetti(Name alias, Table<StatoProgettiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.stato_progetti</code> table reference
     */
    public StatoProgetti(String alias) {
        this(DSL.name(alias), STATO_PROGETTI);
    }

    /**
     * Create an aliased <code>decreti.stato_progetti</code> table reference
     */
    public StatoProgetti(Name alias) {
        this(alias, STATO_PROGETTI);
    }

    /**
     * Create a <code>decreti.stato_progetti</code> table reference
     */
    public StatoProgetti() {
        this(DSL.name("stato_progetti"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<StatoProgettiRecord, Integer> getIdentity() {
        return (Identity<StatoProgettiRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<StatoProgettiRecord> getPrimaryKey() {
        return Keys.KEY_STATO_PROGETTI_PRIMARY;
    }

    @Override
    public StatoProgetti as(String alias) {
        return new StatoProgetti(DSL.name(alias), this);
    }

    @Override
    public StatoProgetti as(Name alias) {
        return new StatoProgetti(alias, this);
    }

    @Override
    public StatoProgetti as(Table<?> alias) {
        return new StatoProgetti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StatoProgetti rename(String name) {
        return new StatoProgetti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StatoProgetti rename(Name name) {
        return new StatoProgetti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StatoProgetti rename(Table<?> name) {
        return new StatoProgetti(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StatoProgetti where(Condition condition) {
        return new StatoProgetti(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StatoProgetti where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StatoProgetti where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StatoProgetti where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StatoProgetti where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StatoProgetti where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StatoProgetti where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StatoProgetti where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StatoProgetti whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StatoProgetti whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
