/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Indexes;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.Delega.DelegaPath;
import it.usr.web.usromniapp.domain.tables.LRuolo.LRuoloPath;
import it.usr.web.usromniapp.domain.tables.ProcAss.ProcAssPath;
import it.usr.web.usromniapp.domain.tables.ProcAssAttuali.ProcAssAttualiPath;
import it.usr.web.usromniapp.domain.tables.ProcIter.ProcIterPath;
import it.usr.web.usromniapp.domain.tables.RuoliUtente.RuoliUtentePath;
import it.usr.web.usromniapp.domain.tables.TipoProcAss.TipoProcAssPath;
import it.usr.web.usromniapp.domain.tables.records.UtentiRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Utenti extends TableImpl<UtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.utenti</code>
     */
    public static final Utenti UTENTI = new Utenti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtentiRecord> getRecordType() {
        return UtentiRecord.class;
    }

    /**
     * The column <code>decreti.utenti.id_utente</code>.
     */
    public final TableField<UtentiRecord, Integer> ID_UTENTE = createField(DSL.name("id_utente"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.utenti.id_gruppo</code>.
     */
    public final TableField<UtentiRecord, Integer> ID_GRUPPO = createField(DSL.name("id_gruppo"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.utenti.id_ambito</code>.
     */
    public final TableField<UtentiRecord, Integer> ID_AMBITO = createField(DSL.name("id_ambito"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.utenti.id_ruolo_predefinito</code>.
     */
    public final TableField<UtentiRecord, Integer> ID_RUOLO_PREDEFINITO = createField(DSL.name("id_ruolo_predefinito"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.utenti.attivo</code>.
     */
    public final TableField<UtentiRecord, Integer> ATTIVO = createField(DSL.name("attivo"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.utenti.utente_fisico</code>.
     */
    public final TableField<UtentiRecord, Integer> UTENTE_FISICO = createField(DSL.name("utente_fisico"), SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.utenti.matricola</code>.
     */
    public final TableField<UtentiRecord, String> MATRICOLA = createField(DSL.name("matricola"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.utenti.nome_utente</code>.
     */
    public final TableField<UtentiRecord, String> NOME_UTENTE = createField(DSL.name("nome_utente"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.utenti.utente</code>.
     */
    public final TableField<UtentiRecord, String> UTENTE = createField(DSL.name("utente"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.utenti.utente_pigrego</code>.
     */
    public final TableField<UtentiRecord, String> UTENTE_PIGREGO = createField(DSL.name("utente_pigrego"), SQLDataType.VARCHAR(80).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.utenti.password</code>.
     */
    public final TableField<UtentiRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.utenti.data_scadenza_password</code>.
     */
    public final TableField<UtentiRecord, LocalDate> DATA_SCADENZA_PASSWORD = createField(DSL.name("data_scadenza_password"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    private Utenti(Name alias, Table<UtentiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Utenti(Name alias, Table<UtentiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.utenti</code> table reference
     */
    public Utenti(String alias) {
        this(DSL.name(alias), UTENTI);
    }

    /**
     * Create an aliased <code>decreti.utenti</code> table reference
     */
    public Utenti(Name alias) {
        this(alias, UTENTI);
    }

    /**
     * Create a <code>decreti.utenti</code> table reference
     */
    public Utenti() {
        this(DSL.name("utenti"), null);
    }

    public <O extends Record> Utenti(Table<O> path, ForeignKey<O, UtentiRecord> childPath, InverseForeignKey<O, UtentiRecord> parentPath) {
        super(path, childPath, parentPath, UTENTI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UtentiPath extends Utenti implements Path<UtentiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UtentiPath(Table<O> path, ForeignKey<O, UtentiRecord> childPath, InverseForeignKey<O, UtentiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UtentiPath(Name alias, Table<UtentiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UtentiPath as(String alias) {
            return new UtentiPath(DSL.name(alias), this);
        }

        @Override
        public UtentiPath as(Name alias) {
            return new UtentiPath(alias, this);
        }

        @Override
        public UtentiPath as(Table<?> alias) {
            return new UtentiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UTENTI_FK_UTENTE_RUOLO_IDX);
    }

    @Override
    public Identity<UtentiRecord, Integer> getIdentity() {
        return (Identity<UtentiRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UtentiRecord> getPrimaryKey() {
        return Keys.KEY_UTENTI_PRIMARY;
    }

    @Override
    public List<ForeignKey<UtentiRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_UTENTE_RUOLO);
    }

    private transient LRuoloPath _lRuolo;

    /**
     * Get the implicit join path to the <code>decreti.l_ruolo</code> table.
     */
    public LRuoloPath lRuolo() {
        if (_lRuolo == null)
            _lRuolo = new LRuoloPath(this, Keys.FK_UTENTE_RUOLO, null);

        return _lRuolo;
    }

    private transient DelegaPath _fkDelegaDelegante;

    /**
     * Get the implicit to-many join path to the <code>decreti.delega</code>
     * table, via the <code>fk_delega_delegante</code> key
     */
    public DelegaPath fkDelegaDelegante() {
        if (_fkDelegaDelegante == null)
            _fkDelegaDelegante = new DelegaPath(this, null, Keys.FK_DELEGA_DELEGANTE.getInverseKey());

        return _fkDelegaDelegante;
    }

    private transient DelegaPath _fkDelegaUtente;

    /**
     * Get the implicit to-many join path to the <code>decreti.delega</code>
     * table, via the <code>fk_delega_utente</code> key
     */
    public DelegaPath fkDelegaUtente() {
        if (_fkDelegaUtente == null)
            _fkDelegaUtente = new DelegaPath(this, null, Keys.FK_DELEGA_UTENTE.getInverseKey());

        return _fkDelegaUtente;
    }

    private transient ProcAssPath _fkProcassUtente;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_ass</code>
     * table, via the <code>fk_procass_utente</code> key
     */
    public ProcAssPath fkProcassUtente() {
        if (_fkProcassUtente == null)
            _fkProcassUtente = new ProcAssPath(this, null, Keys.FK_PROCASS_UTENTE.getInverseKey());

        return _fkProcassUtente;
    }

    private transient ProcAssPath _fkProcassUtenteAss;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_ass</code>
     * table, via the <code>fk_procass_utente_ass</code> key
     */
    public ProcAssPath fkProcassUtenteAss() {
        if (_fkProcassUtenteAss == null)
            _fkProcassUtenteAss = new ProcAssPath(this, null, Keys.FK_PROCASS_UTENTE_ASS.getInverseKey());

        return _fkProcassUtenteAss;
    }

    private transient ProcAssPath _fkProcassUtenteDeleg;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_ass</code>
     * table, via the <code>fk_procass_utente_deleg</code> key
     */
    public ProcAssPath fkProcassUtenteDeleg() {
        if (_fkProcassUtenteDeleg == null)
            _fkProcassUtenteDeleg = new ProcAssPath(this, null, Keys.FK_PROCASS_UTENTE_DELEG.getInverseKey());

        return _fkProcassUtenteDeleg;
    }

    private transient ProcAssPath _fkProcassUtenteRim;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_ass</code>
     * table, via the <code>fk_procass_utente_rim</code> key
     */
    public ProcAssPath fkProcassUtenteRim() {
        if (_fkProcassUtenteRim == null)
            _fkProcassUtenteRim = new ProcAssPath(this, null, Keys.FK_PROCASS_UTENTE_RIM.getInverseKey());

        return _fkProcassUtenteRim;
    }

    private transient ProcAssAttualiPath _procAssAttuali;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.proc_ass_attuali</code> table
     */
    public ProcAssAttualiPath procAssAttuali() {
        if (_procAssAttuali == null)
            _procAssAttuali = new ProcAssAttualiPath(this, null, Keys.FK_PROCASSATT_UTENTE.getInverseKey());

        return _procAssAttuali;
    }

    private transient ProcIterPath _procIter;

    /**
     * Get the implicit to-many join path to the <code>decreti.proc_iter</code>
     * table
     */
    public ProcIterPath procIter() {
        if (_procIter == null)
            _procIter = new ProcIterPath(this, null, Keys.FK_PROCITER_UTENTE.getInverseKey());

        return _procIter;
    }

    private transient RuoliUtentePath _ruoliUtente;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.ruoli_utente</code> table
     */
    public RuoliUtentePath ruoliUtente() {
        if (_ruoliUtente == null)
            _ruoliUtente = new RuoliUtentePath(this, null, Keys.FK_RUOLIUTENTE_UTENTE.getInverseKey());

        return _ruoliUtente;
    }

    private transient TipoProcAssPath _fkTipoprocassUtente;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.tipo_proc_ass</code> table, via the
     * <code>fk_tipoprocass_utente</code> key
     */
    public TipoProcAssPath fkTipoprocassUtente() {
        if (_fkTipoprocassUtente == null)
            _fkTipoprocassUtente = new TipoProcAssPath(this, null, Keys.FK_TIPOPROCASS_UTENTE.getInverseKey());

        return _fkTipoprocassUtente;
    }

    private transient TipoProcAssPath _fkTipoproccassUtenteassegnante;

    /**
     * Get the implicit to-many join path to the
     * <code>decreti.tipo_proc_ass</code> table, via the
     * <code>fk_tipoproccass_utenteassegnante</code> key
     */
    public TipoProcAssPath fkTipoproccassUtenteassegnante() {
        if (_fkTipoproccassUtenteassegnante == null)
            _fkTipoproccassUtenteassegnante = new TipoProcAssPath(this, null, Keys.FK_TIPOPROCCASS_UTENTEASSEGNANTE.getInverseKey());

        return _fkTipoproccassUtenteassegnante;
    }

    @Override
    public Utenti as(String alias) {
        return new Utenti(DSL.name(alias), this);
    }

    @Override
    public Utenti as(Name alias) {
        return new Utenti(alias, this);
    }

    @Override
    public Utenti as(Table<?> alias) {
        return new Utenti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(String name) {
        return new Utenti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(Name name) {
        return new Utenti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Utenti rename(Table<?> name) {
        return new Utenti(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Condition condition) {
        return new Utenti(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Utenti where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Utenti whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
