/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.Keys;
import it.usr.web.usromniapp.domain.tables.records.UtentiUtentiRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UtentiUtenti extends TableImpl<UtentiUtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.utenti_utenti</code>
     */
    public static final UtentiUtenti UTENTI_UTENTI = new UtentiUtenti();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UtentiUtentiRecord> getRecordType() {
        return UtentiUtentiRecord.class;
    }

    /**
     * The column <code>decreti.utenti_utenti.contatore</code>.
     */
    public final TableField<UtentiUtentiRecord, Integer> CONTATORE = createField(DSL.name("contatore"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>decreti.utenti_utenti.id_utente</code>.
     */
    public final TableField<UtentiUtentiRecord, Integer> ID_UTENTE = createField(DSL.name("id_utente"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.utenti_utenti.id_utente_utente</code>.
     */
    public final TableField<UtentiUtentiRecord, Integer> ID_UTENTE_UTENTE = createField(DSL.name("id_utente_utente"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    private UtentiUtenti(Name alias, Table<UtentiUtentiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UtentiUtenti(Name alias, Table<UtentiUtentiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>decreti.utenti_utenti</code> table reference
     */
    public UtentiUtenti(String alias) {
        this(DSL.name(alias), UTENTI_UTENTI);
    }

    /**
     * Create an aliased <code>decreti.utenti_utenti</code> table reference
     */
    public UtentiUtenti(Name alias) {
        this(alias, UTENTI_UTENTI);
    }

    /**
     * Create a <code>decreti.utenti_utenti</code> table reference
     */
    public UtentiUtenti() {
        this(DSL.name("utenti_utenti"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public Identity<UtentiUtentiRecord, Integer> getIdentity() {
        return (Identity<UtentiUtentiRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UtentiUtentiRecord> getPrimaryKey() {
        return Keys.KEY_UTENTI_UTENTI_PRIMARY;
    }

    @Override
    public UtentiUtenti as(String alias) {
        return new UtentiUtenti(DSL.name(alias), this);
    }

    @Override
    public UtentiUtenti as(Name alias) {
        return new UtentiUtenti(alias, this);
    }

    @Override
    public UtentiUtenti as(Table<?> alias) {
        return new UtentiUtenti(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UtentiUtenti rename(String name) {
        return new UtentiUtenti(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UtentiUtenti rename(Name name) {
        return new UtentiUtenti(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UtentiUtenti rename(Table<?> name) {
        return new UtentiUtenti(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UtentiUtenti where(Condition condition) {
        return new UtentiUtenti(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UtentiUtenti where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UtentiUtenti where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UtentiUtenti where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UtentiUtenti where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UtentiUtenti where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UtentiUtenti where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UtentiUtenti where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UtentiUtenti whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UtentiUtenti whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
