/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.tables.records.VOrd100DecretatiRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VOrd100Decretati extends TableImpl<VOrd100DecretatiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.v_ord100_decretati</code>
     */
    public static final VOrd100Decretati V_ORD100_DECRETATI = new VOrd100Decretati();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VOrd100DecretatiRecord> getRecordType() {
        return VOrd100DecretatiRecord.class;
    }

    /**
     * The column <code>decreti.v_ord100_decretati.ID_Pratica</code>.
     */
    public final TableField<VOrd100DecretatiRecord, Integer> ID_PRATICA = createField(DSL.name("ID_Pratica"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>decreti.v_ord100_decretati.data_ora_provvedimento</code>.
     */
    public final TableField<VOrd100DecretatiRecord, LocalDate> DATA_ORA_PROVVEDIMENTO = createField(DSL.name("data_ora_provvedimento"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    private VOrd100Decretati(Name alias, Table<VOrd100DecretatiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VOrd100Decretati(Name alias, Table<VOrd100DecretatiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `v_ord100_decretati` as select `decreti`.`decreti`.`ID_Pratica` AS `ID_Pratica`,min(`decreti`.`decreti`.`data_ora_provvedimento`) AS `data_ora_provvedimento` from `decreti`.`decreti` where `decreti`.`decreti`.`da_rendicontare` = 1 and `decreti`.`decreti`.`numero_provvedimento` is not null and `decreti`.`decreti`.`id_tipo_provvedimento` > 0 and `decreti`.`decreti`.`id_tipo_decreto` = 1 and `decreti`.`decreti`.`id_tipo_pratica` in (1,2,11) and `decreti`.`decreti`.`ID_Pratica` > 0 and `decreti`.`decreti`.`ORD_100` = -1 group by `decreti`.`decreti`.`ID_Pratica`"), where);
    }

    /**
     * Create an aliased <code>decreti.v_ord100_decretati</code> table reference
     */
    public VOrd100Decretati(String alias) {
        this(DSL.name(alias), V_ORD100_DECRETATI);
    }

    /**
     * Create an aliased <code>decreti.v_ord100_decretati</code> table reference
     */
    public VOrd100Decretati(Name alias) {
        this(alias, V_ORD100_DECRETATI);
    }

    /**
     * Create a <code>decreti.v_ord100_decretati</code> table reference
     */
    public VOrd100Decretati() {
        this(DSL.name("v_ord100_decretati"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public VOrd100Decretati as(String alias) {
        return new VOrd100Decretati(DSL.name(alias), this);
    }

    @Override
    public VOrd100Decretati as(Name alias) {
        return new VOrd100Decretati(alias, this);
    }

    @Override
    public VOrd100Decretati as(Table<?> alias) {
        return new VOrd100Decretati(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VOrd100Decretati rename(String name) {
        return new VOrd100Decretati(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VOrd100Decretati rename(Name name) {
        return new VOrd100Decretati(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VOrd100Decretati rename(Table<?> name) {
        return new VOrd100Decretati(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VOrd100Decretati where(Condition condition) {
        return new VOrd100Decretati(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VOrd100Decretati where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VOrd100Decretati where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VOrd100Decretati where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VOrd100Decretati where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VOrd100Decretati where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VOrd100Decretati where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VOrd100Decretati where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VOrd100Decretati whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VOrd100Decretati whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
