/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables;


import it.usr.web.usromniapp.domain.Decreti;
import it.usr.web.usromniapp.domain.tables.records.VUtentiAttiviRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VUtentiAttivi extends TableImpl<VUtentiAttiviRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>decreti.v_utenti_attivi</code>
     */
    public static final VUtentiAttivi V_UTENTI_ATTIVI = new VUtentiAttivi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VUtentiAttiviRecord> getRecordType() {
        return VUtentiAttiviRecord.class;
    }

    /**
     * The column <code>decreti.v_utenti_attivi.id_utente</code>.
     */
    public final TableField<VUtentiAttiviRecord, Integer> ID_UTENTE = createField(DSL.name("id_utente"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.id_gruppo</code>.
     */
    public final TableField<VUtentiAttiviRecord, Integer> ID_GRUPPO = createField(DSL.name("id_gruppo"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.id_ambito</code>.
     */
    public final TableField<VUtentiAttiviRecord, Integer> ID_AMBITO = createField(DSL.name("id_ambito"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.id_ruolo_predefinito</code>.
     */
    public final TableField<VUtentiAttiviRecord, Integer> ID_RUOLO_PREDEFINITO = createField(DSL.name("id_ruolo_predefinito"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.attivo</code>.
     */
    public final TableField<VUtentiAttiviRecord, Integer> ATTIVO = createField(DSL.name("attivo"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.utente_fisico</code>.
     */
    public final TableField<VUtentiAttiviRecord, Integer> UTENTE_FISICO = createField(DSL.name("utente_fisico"), SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.matricola</code>.
     */
    public final TableField<VUtentiAttiviRecord, String> MATRICOLA = createField(DSL.name("matricola"), SQLDataType.VARCHAR(32).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.nome_utente</code>.
     */
    public final TableField<VUtentiAttiviRecord, String> NOME_UTENTE = createField(DSL.name("nome_utente"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.utente</code>.
     */
    public final TableField<VUtentiAttiviRecord, String> UTENTE = createField(DSL.name("utente"), SQLDataType.VARCHAR(128).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.utente_pigrego</code>.
     */
    public final TableField<VUtentiAttiviRecord, String> UTENTE_PIGREGO = createField(DSL.name("utente_pigrego"), SQLDataType.VARCHAR(80).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.password</code>.
     */
    public final TableField<VUtentiAttiviRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>decreti.v_utenti_attivi.data_scadenza_password</code>.
     */
    public final TableField<VUtentiAttiviRecord, LocalDate> DATA_SCADENZA_PASSWORD = createField(DSL.name("data_scadenza_password"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "");

    private VUtentiAttivi(Name alias, Table<VUtentiAttiviRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VUtentiAttivi(Name alias, Table<VUtentiAttiviRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW `v_utenti_attivi` AS select `decreti`.`utenti`.`id_utente` AS `id_utente`,`decreti`.`utenti`.`id_gruppo` AS `id_gruppo`,`decreti`.`utenti`.`id_ambito` AS `id_ambito`,`decreti`.`utenti`.`id_ruolo_predefinito` AS `id_ruolo_predefinito`,`decreti`.`utenti`.`attivo` AS `attivo`,`decreti`.`utenti`.`utente_fisico` AS `utente_fisico`,`decreti`.`utenti`.`matricola` AS `matricola`,`decreti`.`utenti`.`nome_utente` AS `nome_utente`,`decreti`.`utenti`.`utente` AS `utente`,`decreti`.`utenti`.`utente_pigrego` AS `utente_pigrego`,`decreti`.`utenti`.`password` AS `password`,`decreti`.`utenti`.`data_scadenza_password` AS `data_scadenza_password` from `decreti`.`utenti` where `decreti`.`utenti`.`attivo` = 1 and `decreti`.`utenti`.`utente_fisico` = 1"), where);
    }

    /**
     * Create an aliased <code>decreti.v_utenti_attivi</code> table reference
     */
    public VUtentiAttivi(String alias) {
        this(DSL.name(alias), V_UTENTI_ATTIVI);
    }

    /**
     * Create an aliased <code>decreti.v_utenti_attivi</code> table reference
     */
    public VUtentiAttivi(Name alias) {
        this(alias, V_UTENTI_ATTIVI);
    }

    /**
     * Create a <code>decreti.v_utenti_attivi</code> table reference
     */
    public VUtentiAttivi() {
        this(DSL.name("v_utenti_attivi"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Decreti.DECRETI;
    }

    @Override
    public VUtentiAttivi as(String alias) {
        return new VUtentiAttivi(DSL.name(alias), this);
    }

    @Override
    public VUtentiAttivi as(Name alias) {
        return new VUtentiAttivi(alias, this);
    }

    @Override
    public VUtentiAttivi as(Table<?> alias) {
        return new VUtentiAttivi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VUtentiAttivi rename(String name) {
        return new VUtentiAttivi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VUtentiAttivi rename(Name name) {
        return new VUtentiAttivi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VUtentiAttivi rename(Table<?> name) {
        return new VUtentiAttivi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VUtentiAttivi where(Condition condition) {
        return new VUtentiAttivi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VUtentiAttivi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VUtentiAttivi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VUtentiAttivi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VUtentiAttivi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VUtentiAttivi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VUtentiAttivi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VUtentiAttivi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VUtentiAttivi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VUtentiAttivi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
