/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.routines;


import it.usr.web.usromniapp.domain.Decreti;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpAggiornaUfficio extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>decreti.sp_aggiorna_ufficio.id_ufficio</code>.
     */
    public static final Parameter<Integer> ID_UFFICIO = Internal.createParameter("id_ufficio", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>decreti.sp_aggiorna_ufficio.nomeufficio</code>.
     */
    public static final Parameter<String> NOMEUFFICIO = Internal.createParameter("nomeufficio", SQLDataType.VARCHAR(70), false, false);

    /**
     * The parameter <code>decreti.sp_aggiorna_ufficio.id_utente_resp</code>.
     */
    public static final Parameter<Integer> ID_UTENTE_RESP = Internal.createParameter("id_utente_resp", SQLDataType.INTEGER, false, false);

    /**
     * The parameter
     * <code>decreti.sp_aggiorna_ufficio.id_utente_resp_prec</code>.
     */
    public static final Parameter<Integer> ID_UTENTE_RESP_PREC = Internal.createParameter("id_utente_resp_prec", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>decreti.sp_aggiorna_ufficio.estremi_provv</code>.
     */
    public static final Parameter<String> ESTREMI_PROVV = Internal.createParameter("estremi_provv", SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public SpAggiornaUfficio() {
        super("sp_aggiorna_ufficio", Decreti.DECRETI);

        addInParameter(ID_UFFICIO);
        addInParameter(NOMEUFFICIO);
        addInParameter(ID_UTENTE_RESP);
        addInParameter(ID_UTENTE_RESP_PREC);
        addInParameter(ESTREMI_PROVV);
    }

    /**
     * Set the <code>id_ufficio</code> parameter IN value to the routine
     */
    public void setIdUfficio(Integer value) {
        setValue(ID_UFFICIO, value);
    }

    /**
     * Set the <code>nomeufficio</code> parameter IN value to the routine
     */
    public void setNomeufficio(String value) {
        setValue(NOMEUFFICIO, value);
    }

    /**
     * Set the <code>id_utente_resp</code> parameter IN value to the routine
     */
    public void setIdUtenteResp(Integer value) {
        setValue(ID_UTENTE_RESP, value);
    }

    /**
     * Set the <code>id_utente_resp_prec</code> parameter IN value to the
     * routine
     */
    public void setIdUtenteRespPrec(Integer value) {
        setValue(ID_UTENTE_RESP_PREC, value);
    }

    /**
     * Set the <code>estremi_provv</code> parameter IN value to the routine
     */
    public void setEstremiProvv(String value) {
        setValue(ESTREMI_PROVV, value);
    }
}
