/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain;


import it.usr.web.usromniapp.domain.tables.ComConcessione;
import it.usr.web.usromniapp.domain.tables.ComStatofascicolo;
import it.usr.web.usromniapp.domain.tables.Cup;
import it.usr.web.usromniapp.domain.tables.Decreti;
import it.usr.web.usromniapp.domain.tables.Delega;
import it.usr.web.usromniapp.domain.tables.EsitiAttivazione;
import it.usr.web.usromniapp.domain.tables.GisCentroidi;
import it.usr.web.usromniapp.domain.tables.GisDettaglio;
import it.usr.web.usromniapp.domain.tables.GisPrivata;
import it.usr.web.usromniapp.domain.tables.Incarico;
import it.usr.web.usromniapp.domain.tables.IterA;
import it.usr.web.usromniapp.domain.tables.IterB;
import it.usr.web.usromniapp.domain.tables.LTipoPasso;
import it.usr.web.usromniapp.domain.tables.Manifestazioni;
import it.usr.web.usromniapp.domain.tables.ManifestazioniCat;
import it.usr.web.usromniapp.domain.tables.Membro;
import it.usr.web.usromniapp.domain.tables.MonAssegnazioni;
import it.usr.web.usromniapp.domain.tables.MonIter;
import it.usr.web.usromniapp.domain.tables.MonMudeAccess;
import it.usr.web.usromniapp.domain.tables.Proc;
import it.usr.web.usromniapp.domain.tables.ProcAss;
import it.usr.web.usromniapp.domain.tables.ProcAssAttuali;
import it.usr.web.usromniapp.domain.tables.ProcCat;
import it.usr.web.usromniapp.domain.tables.ProcDipendenze;
import it.usr.web.usromniapp.domain.tables.ProcEsiti;
import it.usr.web.usromniapp.domain.tables.ProcIncarichi;
import it.usr.web.usromniapp.domain.tables.ProcIter;
import it.usr.web.usromniapp.domain.tables.ProcPassoIniziale;
import it.usr.web.usromniapp.domain.tables.ProcTecniciSospensione;
import it.usr.web.usromniapp.domain.tables.RuoliUtente;
import it.usr.web.usromniapp.domain.tables.RuoloAmbito;
import it.usr.web.usromniapp.domain.tables.TipoProcAss;
import it.usr.web.usromniapp.domain.tables.Uffici;
import it.usr.web.usromniapp.domain.tables.Utenti;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in decreti.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MON_ITER_AAAA = Internal.createIndex(DSL.name("aaaa"), MonIter.MON_ITER, new OrderField[] { MonIter.MON_ITER.ID_PRATICA }, false);
    public static final Index COM_STATOFASCICOLO_COM_STATOFASCICOLO_IDX = Internal.createIndex(DSL.name("COM_STATOFASCICOLO_IDX"), ComStatofascicolo.COM_STATOFASCICOLO, new OrderField[] { ComStatofascicolo.COM_STATOFASCICOLO.IDPRATICA }, false);
    public static final Index DELEGA_FK_DELEGA_DELEGANTE_IDX = Internal.createIndex(DSL.name("fk_delega_delegante_idx"), Delega.DELEGA, new OrderField[] { Delega.DELEGA.ID_DELEGANTE }, false);
    public static final Index DELEGA_FK_DELEGA_TIPOPROC_IDX = Internal.createIndex(DSL.name("fk_delega_tipoproc_idx"), Delega.DELEGA, new OrderField[] { Delega.DELEGA.ID_TIPO_PROC }, false);
    public static final Index DELEGA_FK_DELEGA_UTENTE_IDX = Internal.createIndex(DSL.name("fk_delega_utente_idx"), Delega.DELEGA, new OrderField[] { Delega.DELEGA.ID_UTENTE }, false);
    public static final Index PROC_ESITI_FK_ESITI_TIPO_PROC_IDX = Internal.createIndex(DSL.name("fk_esiti_tipo_proc_idx"), ProcEsiti.PROC_ESITI, new OrderField[] { ProcEsiti.PROC_ESITI.ID_TIPO_PROC }, false);
    public static final Index ESITI_ATTIVAZIONE_FK_ESITIATT_ESITI_IDX = Internal.createIndex(DSL.name("fk_esitiatt_esiti_idx"), EsitiAttivazione.ESITI_ATTIVAZIONE, new OrderField[] { EsitiAttivazione.ESITI_ATTIVAZIONE.ID_ESITO }, false);
    public static final Index ESITI_ATTIVAZIONE_FK_ESITIATTIVAZ_TIPOPASS_IDX = Internal.createIndex(DSL.name("fk_esitiattivaz_tipopass_idx"), EsitiAttivazione.ESITI_ATTIVAZIONE, new OrderField[] { EsitiAttivazione.ESITI_ATTIVAZIONE.CODICE_PASSO }, false);
    public static final Index INCARICO_FK_INCARICO_PROC_IDX = Internal.createIndex(DSL.name("fk_incarico_proc_idx"), Incarico.INCARICO, new OrderField[] { Incarico.INCARICO.ID_PROC }, false);
    public static final Index INCARICO_FK_INCARICO_RUOLO_IDX = Internal.createIndex(DSL.name("fk_incarico_ruolo_idx"), Incarico.INCARICO, new OrderField[] { Incarico.INCARICO.ID_RUOLO }, false);
    public static final Index INCARICO_FK_INCARICO_TECNICO_IDX = Internal.createIndex(DSL.name("fk_incarico_tecnico_idx"), Incarico.INCARICO, new OrderField[] { Incarico.INCARICO.ID_TECNICO }, false);
    public static final Index PROC_FK_PROC_GISCENTROIDI_IDX = Internal.createIndex(DSL.name("fk_proc_giscentroidi_idx"), Proc.PROC, new OrderField[] { Proc.PROC.CODICE_COM }, false);
    public static final Index PROC_FK_PROC_PROCITER_IDX = Internal.createIndex(DSL.name("fk_proc_prociter_idx"), Proc.PROC, new OrderField[] { Proc.PROC.ID_PROC_ITER_ULTIMO }, false);
    public static final Index PROC_FK_PROC_TIPOPROC_IDX = Internal.createIndex(DSL.name("fk_proc_tipoproc_idx"), Proc.PROC, new OrderField[] { Proc.PROC.ID_TIPO_PROC }, false);
    public static final Index PROC_ASS_FK_PROCASS_PROC_IDX = Internal.createIndex(DSL.name("fk_procass_proc_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_PROC }, false);
    public static final Index PROC_ASS_FK_PROCASS_UFFICIO_IDX = Internal.createIndex(DSL.name("fk_procass_ufficio_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_UFFICIO }, false);
    public static final Index PROC_ASS_FK_PROCASS_UTENTE_ASS_IDX = Internal.createIndex(DSL.name("fk_procass_utente_ass_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_UTENTE_ASSEGNANTE }, false);
    public static final Index PROC_ASS_FK_PROCASS_UTENTE_DELEG_IDX = Internal.createIndex(DSL.name("fk_procass_utente_deleg_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_UTENTE_DELEGANTE }, false);
    public static final Index PROC_ASS_FK_PROCASS_UTENTE_IDX = Internal.createIndex(DSL.name("fk_procass_utente_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_UTENTE }, false);
    public static final Index PROC_ASS_FK_PROCASS_UTENTE_RIM_IDX = Internal.createIndex(DSL.name("fk_procass_utente_rim_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_UTENTE_RIMOZIONE }, false);
    public static final Index PROC_ASS_ATTUALI_FK_PROCASSATT_PROC_IDX = Internal.createIndex(DSL.name("fk_procassatt_proc_idx"), ProcAssAttuali.PROC_ASS_ATTUALI, new OrderField[] { ProcAssAttuali.PROC_ASS_ATTUALI.ID_PROC }, false);
    public static final Index PROC_ASS_ATTUALI_FK_PROCASSATT_RUOLO_IDX = Internal.createIndex(DSL.name("fk_procassatt_ruolo_idx"), ProcAssAttuali.PROC_ASS_ATTUALI, new OrderField[] { ProcAssAttuali.PROC_ASS_ATTUALI.ID_RUOLO }, false);
    public static final Index PROC_ASS_ATTUALI_FK_PROCASSATT_UTENTE_IDX = Internal.createIndex(DSL.name("fk_procassatt_utente_idx"), ProcAssAttuali.PROC_ASS_ATTUALI, new OrderField[] { ProcAssAttuali.PROC_ASS_ATTUALI.ID_UTENTE }, false);
    public static final Index PROC_ASS_FK_PROCCASS_RUOLO_IDX = Internal.createIndex(DSL.name("fk_proccass_ruolo_idx"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.ID_RUOLO }, false);
    public static final Index PROC_CAT_FK_PROCCAT_PROC_IDX = Internal.createIndex(DSL.name("fk_proccat_proc_idx"), ProcCat.PROC_CAT, new OrderField[] { ProcCat.PROC_CAT.ID_PROC }, false);
    public static final Index PROC_DIPENDENZE_FK_PROCDIPEND_TIPOPASSO_CODICEPS_IDX = Internal.createIndex(DSL.name("fk_procdipend_tipopasso_codiceps_idx"), ProcDipendenze.PROC_DIPENDENZE, new OrderField[] { ProcDipendenze.PROC_DIPENDENZE.CODICE_PASSO_SUCC }, false);
    public static final Index PROC_DIPENDENZE_FK_PROCDPEND_TIPOPROC_IDX = Internal.createIndex(DSL.name("fk_procdpend_tipoproc_idx"), ProcDipendenze.PROC_DIPENDENZE, new OrderField[] { ProcDipendenze.PROC_DIPENDENZE.ID_TIPO_PROC }, false);
    public static final Index PROC_INCARICHI_FK_PROCINCARICHI_PROC_IDX = Internal.createIndex(DSL.name("fk_procincarichi_proc_idx"), ProcIncarichi.PROC_INCARICHI, new OrderField[] { ProcIncarichi.PROC_INCARICHI.ID_PROC }, false);
    public static final Index PROC_INCARICHI_FK_PROCINCARICHI_RUOLOTECNICO_IDX = Internal.createIndex(DSL.name("fk_procincarichi_ruolotecnico_idx"), ProcIncarichi.PROC_INCARICHI, new OrderField[] { ProcIncarichi.PROC_INCARICHI.ID_RUOLO_TECNICO }, false);
    public static final Index PROC_INCARICHI_FK_PROCINCARICHI_TECNICI_IDX = Internal.createIndex(DSL.name("fk_procincarichi_tecnici_idx"), ProcIncarichi.PROC_INCARICHI, new OrderField[] { ProcIncarichi.PROC_INCARICHI.ID_TECNICO }, false);
    public static final Index PROC_ITER_FK_PROCITER_CODICEPASSO_IDX = Internal.createIndex(DSL.name("fk_prociter_codicepasso_idx"), ProcIter.PROC_ITER, new OrderField[] { ProcIter.PROC_ITER.CODICE_PASSO }, false);
    public static final Index PROC_ITER_FK_PROCITER_ESITO_IDX = Internal.createIndex(DSL.name("fk_prociter_esito_idx"), ProcIter.PROC_ITER, new OrderField[] { ProcIter.PROC_ITER.ID_ESITO }, false);
    public static final Index PROC_ITER_FK_PROCITER_PROC_IDX = Internal.createIndex(DSL.name("fk_prociter_proc_idx"), ProcIter.PROC_ITER, new OrderField[] { ProcIter.PROC_ITER.ID_PROC }, false);
    public static final Index PROC_ITER_FK_PROCITER_UTENTE_IDX = Internal.createIndex(DSL.name("fk_prociter_utente_idx"), ProcIter.PROC_ITER, new OrderField[] { ProcIter.PROC_ITER.ID_UTENTE }, false);
    public static final Index PROC_PASSO_INIZIALE_FK_PROCPASSOINIZ_TIPOPASSO_IDX = Internal.createIndex(DSL.name("fk_procpassoiniz_tipopasso_idx"), ProcPassoIniziale.PROC_PASSO_INIZIALE, new OrderField[] { ProcPassoIniziale.PROC_PASSO_INIZIALE.CODICE_PASSO }, false);
    public static final Index PROC_TECNICI_SOSPENSIONE_FK_PROCTECNICISOSP_PROCTECNICI_IDX = Internal.createIndex(DSL.name("fk_proctecnicisosp_proctecnici_idx"), ProcTecniciSospensione.PROC_TECNICI_SOSPENSIONE, new OrderField[] { ProcTecniciSospensione.PROC_TECNICI_SOSPENSIONE.ID_TECNICO }, false);
    public static final Index RUOLI_UTENTE_FK_RUOLIUTENTE_RUOLO_IDX = Internal.createIndex(DSL.name("fk_ruoliutente_ruolo_idx"), RuoliUtente.RUOLI_UTENTE, new OrderField[] { RuoliUtente.RUOLI_UTENTE.ID_RUOLO }, false);
    public static final Index RUOLI_UTENTE_FK_RUOLIUTENTE_UTENTE_IDX = Internal.createIndex(DSL.name("fk_ruoliutente_utente_idx"), RuoliUtente.RUOLI_UTENTE, new OrderField[] { RuoliUtente.RUOLI_UTENTE.ID_UTENTE }, false);
    public static final Index RUOLO_AMBITO_FK_RUOLOAMBITO_AMBITO_IDX = Internal.createIndex(DSL.name("fk_ruoloambito_ambito_idx"), RuoloAmbito.RUOLO_AMBITO, new OrderField[] { RuoloAmbito.RUOLO_AMBITO.ID_AMBITO }, false);
    public static final Index RUOLO_AMBITO_FK_RUOLOAMBITO_RUOLO_IDX = Internal.createIndex(DSL.name("fk_ruoloambito_ruolo_idx"), RuoloAmbito.RUOLO_AMBITO, new OrderField[] { RuoloAmbito.RUOLO_AMBITO.ID_RUOLO }, false);
    public static final Index L_TIPO_PASSO_FK_TIPOPASS_TIPOPROC_IDX = Internal.createIndex(DSL.name("fk_tipopass_tipoproc_idx"), LTipoPasso.L_TIPO_PASSO, new OrderField[] { LTipoPasso.L_TIPO_PASSO.ID_TIPO_PROC }, false);
    public static final Index TIPO_PROC_ASS_FK_TIPOPROCASS_LTIPOPROC_IDX = Internal.createIndex(DSL.name("fk_tipoprocass_ltipoproc_idx"), TipoProcAss.TIPO_PROC_ASS, new OrderField[] { TipoProcAss.TIPO_PROC_ASS.ID_TIPO_PROC }, false);
    public static final Index TIPO_PROC_ASS_FK_TIPOPROCASS_RUOLO_IDX = Internal.createIndex(DSL.name("fk_tipoprocass_ruolo_idx"), TipoProcAss.TIPO_PROC_ASS, new OrderField[] { TipoProcAss.TIPO_PROC_ASS.ID_RUOLO }, false);
    public static final Index TIPO_PROC_ASS_FK_TIPOPROCASS_UFFICIO_IDX = Internal.createIndex(DSL.name("fk_tipoprocass_ufficio_idx"), TipoProcAss.TIPO_PROC_ASS, new OrderField[] { TipoProcAss.TIPO_PROC_ASS.ID_UFFICIO }, false);
    public static final Index TIPO_PROC_ASS_FK_TIPOPROCASS_UTENTE_IDX = Internal.createIndex(DSL.name("fk_tipoprocass_utente_idx"), TipoProcAss.TIPO_PROC_ASS, new OrderField[] { TipoProcAss.TIPO_PROC_ASS.ID_UTENTE }, false);
    public static final Index TIPO_PROC_ASS_FK_TIPOPROCASS_UTENTEASSEGNANTE_IDX = Internal.createIndex(DSL.name("fk_tipoprocass_utenteassegnante_idx"), TipoProcAss.TIPO_PROC_ASS, new OrderField[] { TipoProcAss.TIPO_PROC_ASS.ID_UTENTE_ASSEGNANTE }, false);
    public static final Index UFFICI_FK_UFFICI_SOVRAORDINATO_IDX = Internal.createIndex(DSL.name("fk_uffici_sovraordinato_idx"), Uffici.UFFICI, new OrderField[] { Uffici.UFFICI.ID_UFFICIO_SOVRAORDINATO }, false);
    public static final Index UTENTI_FK_UTENTE_RUOLO_IDX = Internal.createIndex(DSL.name("fk_utente_ruolo_idx"), Utenti.UTENTI, new OrderField[] { Utenti.UTENTI.ID_RUOLO_PREDEFINITO }, false);
    public static final Index MON_ASSEGNAZIONI_I_ID_PRATICA = Internal.createIndex(DSL.name("i_id_pratica"), MonAssegnazioni.MON_ASSEGNAZIONI, new OrderField[] { MonAssegnazioni.MON_ASSEGNAZIONI.ID_PRATICA }, false);
    public static final Index MON_ITER_ID_PRATICA = Internal.createIndex(DSL.name("ID_Pratica"), MonIter.MON_ITER, new OrderField[] { MonIter.MON_ITER.ID_PRATICA }, false);
    public static final Index MON_MUDE_ACCESS_ID_PRATICA = Internal.createIndex(DSL.name("ID_Pratica"), MonMudeAccess.MON_MUDE_ACCESS, new OrderField[] { MonMudeAccess.MON_MUDE_ACCESS.ID_PRATICA }, false);
    public static final Index GIS_CENTROIDI_IDX_GISCENTROIDI_CENTRO = Internal.createIndex(DSL.name("idx_giscentroidi_centro"), GisCentroidi.GIS_CENTROIDI, new OrderField[] { GisCentroidi.GIS_CENTROIDI.CENTRO }, false);
    public static final Index GIS_PRIVATA_IDX_GISDETTAGLIO_IDLAYER = Internal.createIndex(DSL.name("idx_gisdettaglio_idlayer"), GisPrivata.GIS_PRIVATA, new OrderField[] { GisPrivata.GIS_PRIVATA.ID_LAYER }, false);
    public static final Index GIS_DETTAGLIO_IDX_GISDETTAGLIO_IDPRATICA = Internal.createIndex(DSL.name("idx_gisdettaglio_idpratica"), GisDettaglio.GIS_DETTAGLIO, new OrderField[] { GisDettaglio.GIS_DETTAGLIO.ID_PRATICA }, false);
    public static final Index GIS_PRIVATA_IDX_GISPOLIGONI_GEOMETRIA = Internal.createIndex(DSL.name("idx_gispoligoni_geometria"), GisPrivata.GIS_PRIVATA, new OrderField[] { GisPrivata.GIS_PRIVATA.GEOMETRIA }, false);
    public static final Index GIS_PRIVATA_IDX_GISPOLIGONI_IDPRATICA_ISTAT = Internal.createIndex(DSL.name("idx_gispoligoni_idpratica_istat"), GisPrivata.GIS_PRIVATA, new OrderField[] { GisPrivata.GIS_PRIVATA.ID_PRATICA, GisPrivata.GIS_PRIVATA.ISTAT }, false);
    public static final Index COM_CONCESSIONE_IDX_IDPRATICA_TIPO = Internal.createIndex(DSL.name("IDX_IDPRATICA_TIPO"), ComConcessione.COM_CONCESSIONE, new OrderField[] { ComConcessione.COM_CONCESSIONE.ID_PRATICA, ComConcessione.COM_CONCESSIONE.TIPO }, false);
    public static final Index GIS_PRIVATA_IDX_IDTIPOPROPRIETA_ABILITATO = Internal.createIndex(DSL.name("idx_idtipoproprieta_abilitato"), GisPrivata.GIS_PRIVATA, new OrderField[] { GisPrivata.GIS_PRIVATA.ID_TIPO_PROPRIETA, GisPrivata.GIS_PRIVATA.ABILITATO }, false);
    public static final Index ITER_A_IDX_ITERA_IDPRATICA = Internal.createIndex(DSL.name("idx_itera_idpratica"), IterA.ITER_A, new OrderField[] { IterA.ITER_A.ID_PRATICA }, false);
    public static final Index ITER_B_IDX_ITERB_IDPRATICA = Internal.createIndex(DSL.name("idx_iterb_idpratica"), IterB.ITER_B, new OrderField[] { IterB.ITER_B.ID_PRATICA }, false);
    public static final Index PROC_ASS_IDX_PROCASS_DATAASSRIM = Internal.createIndex(DSL.name("idx_procass_dataassrim"), ProcAss.PROC_ASS, new OrderField[] { ProcAss.PROC_ASS.DATA_ASSEGNAZIONE, ProcAss.PROC_ASS.DATA_RIMOZIONE }, false);
    public static final Index TIPO_PROC_ASS_IDX_TIPOPROCASS_DATAASSRIM = Internal.createIndex(DSL.name("idx_tipoprocass_dataassrim"), TipoProcAss.TIPO_PROC_ASS, new OrderField[] { TipoProcAss.TIPO_PROC_ASS.DATA_ASSEGNAZIONE, TipoProcAss.TIPO_PROC_ASS.DATA_RIMOZIONE }, false);
    public static final Index DECRETI_IND_CUP = Internal.createIndex(DSL.name("ind_CUP"), Decreti.DECRETI_, new OrderField[] { Decreti.DECRETI_.CUP }, false);
    public static final Index DECRETI_IND_ID_ORDINANZA_RIFERIMENTO = Internal.createIndex(DSL.name("ind_id_ordinanza_riferimento"), Decreti.DECRETI_, new OrderField[] { Decreti.DECRETI_.ID_ORDINANZA_RIFERIMENTO }, false);
    public static final Index DECRETI_IND_ID_PRATICA = Internal.createIndex(DSL.name("ind_ID_Pratica"), Decreti.DECRETI_, new OrderField[] { Decreti.DECRETI_.ID_PRATICA }, false);
    public static final Index DECRETI_IND_ID_PROVVISORIO_NEVE = Internal.createIndex(DSL.name("ind_id_provvisorio_neve"), Decreti.DECRETI_, new OrderField[] { Decreti.DECRETI_.ID_PROVVISORIO_NEVE }, false);
    public static final Index CUP_INDEX_CUP = Internal.createIndex(DSL.name("index_cup"), Cup.CUP, new OrderField[] { Cup.CUP.CUP_ }, false);
    public static final Index MANIFESTAZIONI_PK_CODINE_MAN = Internal.createIndex(DSL.name("pk_codine_man"), Manifestazioni.MANIFESTAZIONI, new OrderField[] { Manifestazioni.MANIFESTAZIONI.CODICE_IDENTIFICATIVO }, false);
    public static final Index MANIFESTAZIONI_CAT_PK_MAN = Internal.createIndex(DSL.name("pk_man"), ManifestazioniCat.MANIFESTAZIONI_CAT, new OrderField[] { ManifestazioniCat.MANIFESTAZIONI_CAT.CODICE }, false);
    public static final Index MEMBRO_PK_MEMBRO = Internal.createIndex(DSL.name("pk_membro"), Membro.MEMBRO, new OrderField[] { Membro.MEMBRO.ID_UTENTE, Membro.MEMBRO.ID_GRUPPO }, false);
}
