/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain;


import it.usr.web.usromniapp.domain.routines.SpAggiornaUfficio;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in decreti.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>decreti.sp_aggiorna_ufficio</code>
     */
    public static void spAggiornaUfficio(
          Configuration configuration
        , Integer idUfficio
        , String nomeufficio
        , Integer idUtenteResp
        , Integer idUtenteRespPrec
        , String estremiProvv
    ) {
        SpAggiornaUfficio p = new SpAggiornaUfficio();
        p.setIdUfficio(idUfficio);
        p.setNomeufficio(nomeufficio);
        p.setIdUtenteResp(idUtenteResp);
        p.setIdUtenteRespPrec(idUtenteRespPrec);
        p.setEstremiProvv(estremiProvv);

        p.execute(configuration);
    }
}
