/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.Cas_2024;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cas_2024Record extends UpdatableRecordImpl<Cas_2024Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.cas_2024.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.cas_2024.cognome</code>.
     */
    public void setCognome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.cognome</code>.
     */
    public String getCognome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>decreti.cas_2024.nome</code>.
     */
    public void setNome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.nome</code>.
     */
    public String getNome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.cas_2024.cf</code>.
     */
    public void setCf(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.cf</code>.
     */
    public String getCf() {
        return (String) get(3);
    }

    /**
     * Setter for <code>decreti.cas_2024.istat_comune</code>.
     */
    public void setIstatComune(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.istat_comune</code>.
     */
    public Integer getIstatComune() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>decreti.cas_2024.comune</code>.
     */
    public void setComune(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.comune</code>.
     */
    public String getComune() {
        return (String) get(5);
    }

    /**
     * Setter for <code>decreti.cas_2024.indirizzo_abitazione</code>.
     */
    public void setIndirizzoAbitazione(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.cas_2024.indirizzo_abitazione</code>.
     */
    public String getIndirizzoAbitazione() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Cas_2024Record
     */
    public Cas_2024Record() {
        super(Cas_2024.CAS_2024);
    }

    /**
     * Create a detached, initialised Cas_2024Record
     */
    public Cas_2024Record(Integer id, String cognome, String nome, String cf, Integer istatComune, String comune, String indirizzoAbitazione) {
        super(Cas_2024.CAS_2024);

        setId(id);
        setCognome(cognome);
        setNome(nome);
        setCf(cf);
        setIstatComune(istatComune);
        setComune(comune);
        setIndirizzoAbitazione(indirizzoAbitazione);
        resetChangedOnNotNull();
    }
}
