/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.DecretiNumero;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DecretiNumeroRecord extends TableRecordImpl<DecretiNumeroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.decreti_numero.numero_decreto</code>.
     */
    public void setNumeroDecreto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.decreti_numero.numero_decreto</code>.
     */
    public Integer getNumeroDecreto() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.decreti_numero.anno_decreto</code>.
     */
    public void setAnnoDecreto(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.decreti_numero.anno_decreto</code>.
     */
    public Integer getAnnoDecreto() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.decreti_numero.id_tipo_provvedimento</code>.
     */
    public void setIdTipoProvvedimento(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.decreti_numero.id_tipo_provvedimento</code>.
     */
    public Integer getIdTipoProvvedimento() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.decreti_numero.id_atto</code>.
     */
    public void setIdAtto(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.decreti_numero.id_atto</code>.
     */
    public Integer getIdAtto() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.decreti_numero.data_ora</code>.
     */
    public void setDataOra(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.decreti_numero.data_ora</code>.
     */
    public LocalDateTime getDataOra() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>decreti.decreti_numero.pubblicato</code>.
     */
    public void setPubblicato(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.decreti_numero.pubblicato</code>.
     */
    public Integer getPubblicato() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DecretiNumeroRecord
     */
    public DecretiNumeroRecord() {
        super(DecretiNumero.DECRETI_NUMERO);
    }

    /**
     * Create a detached, initialised DecretiNumeroRecord
     */
    public DecretiNumeroRecord(Integer numeroDecreto, Integer annoDecreto, Integer idTipoProvvedimento, Integer idAtto, LocalDateTime dataOra, Integer pubblicato) {
        super(DecretiNumero.DECRETI_NUMERO);

        setNumeroDecreto(numeroDecreto);
        setAnnoDecreto(annoDecreto);
        setIdTipoProvvedimento(idTipoProvvedimento);
        setIdAtto(idAtto);
        setDataOra(dataOra);
        setPubblicato(pubblicato);
        resetChangedOnNotNull();
    }
}
