/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.ElencoProgettiNeve;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ElencoProgettiNeveRecord extends TableRecordImpl<ElencoProgettiNeveRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.elenco_progetti_neve.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.id_comune</code>.
     */
    public void setIdComune(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.id_comune</code>.
     */
    public Integer getIdComune() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.COMUNE</code>.
     */
    public void setComune(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.COMUNE</code>.
     */
    public String getComune() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.PROV</code>.
     */
    public void setProv(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.PROV</code>.
     */
    public String getProv() {
        return (String) get(3);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.ID_PROVVISORIO</code>.
     */
    public void setIdProvvisorio(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.ID_PROVVISORIO</code>.
     */
    public String getIdProvvisorio() {
        return (String) get(4);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.prot_num</code>.
     */
    public void setProtNum(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.prot_num</code>.
     */
    public String getProtNum() {
        return (String) get(5);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.prot_data</code>.
     */
    public void setProtData(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.prot_data</code>.
     */
    public LocalDateTime getProtData() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.denominazione</code>.
     */
    public void setDenominazione(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.denominazione</code>.
     */
    public String getDenominazione() {
        return (String) get(7);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.pi</code>.
     */
    public void setPi(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.pi</code>.
     */
    public String getPi() {
        return (String) get(8);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.cf</code>.
     */
    public void setCf(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.cf</code>.
     */
    public String getCf() {
        return (String) get(9);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.importo_immobili</code>.
     */
    public void setImportoImmobili(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.importo_immobili</code>.
     */
    public Double getImportoImmobili() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.importo_mobili</code>.
     */
    public void setImportoMobili(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.importo_mobili</code>.
     */
    public Double getImportoMobili() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.importo_demolizioni</code>.
     */
    public void setImportoDemolizioni(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.importo_demolizioni</code>.
     */
    public Double getImportoDemolizioni() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.importo_scorte</code>.
     */
    public void setImportoScorte(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.importo_scorte</code>.
     */
    public Double getImportoScorte() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.tipo_intervento</code>.
     */
    public void setTipoIntervento(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.tipo_intervento</code>.
     */
    public String getTipoIntervento() {
        return (String) get(14);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.indirizzo</code>.
     */
    public void setIndirizzo(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.indirizzo</code>.
     */
    public String getIndirizzo() {
        return (String) get(15);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.stato_lavori</code>.
     */
    public void setStatoLavori(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.stato_lavori</code>.
     */
    public String getStatoLavori() {
        return (String) get(16);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.id_ricognizione</code>.
     */
    public void setIdRicognizione(Short value) {
        set(17, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.id_ricognizione</code>.
     */
    public Short getIdRicognizione() {
        return (Short) get(17);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.ISTRUTTORIA_STATO</code>.
     */
    public void setIstruttoriaStato(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.ISTRUTTORIA_STATO</code>.
     */
    public String getIstruttoriaStato() {
        return (String) get(18);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.SOMME ACCANTONATE</code>.
     */
    public void setSommeAccantonate(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.SOMME ACCANTONATE</code>.
     */
    public Double getSommeAccantonate() {
        return (Double) get(19);
    }

    /**
     * Setter for
     * <code>decreti.elenco_progetti_neve.ISTRUTTORIA_TIPOLOGIA</code>.
     */
    public void setIstruttoriaTipologia(String value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>decreti.elenco_progetti_neve.ISTRUTTORIA_TIPOLOGIA</code>.
     */
    public String getIstruttoriaTipologia() {
        return (String) get(20);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.RESPONSABILE
     * UFFICIO</code>.
     */
    public void setResponsabileUfficio(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.RESPONSABILE
     * UFFICIO</code>.
     */
    public String getResponsabileUfficio() {
        return (String) get(21);
    }

    /**
     * Setter for <code>decreti.elenco_progetti_neve.RESPONSABILE
     * UFFICIO2</code>.
     */
    public void setResponsabileUfficio2(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>decreti.elenco_progetti_neve.RESPONSABILE
     * UFFICIO2</code>.
     */
    public String getResponsabileUfficio2() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElencoProgettiNeveRecord
     */
    public ElencoProgettiNeveRecord() {
        super(ElencoProgettiNeve.ELENCO_PROGETTI_NEVE);
    }

    /**
     * Create a detached, initialised ElencoProgettiNeveRecord
     */
    public ElencoProgettiNeveRecord(Integer id, Integer idComune, String comune, String prov, String idProvvisorio, String protNum, LocalDateTime protData, String denominazione, String pi, String cf, Double importoImmobili, Double importoMobili, Double importoDemolizioni, Double importoScorte, String tipoIntervento, String indirizzo, String statoLavori, Short idRicognizione, String istruttoriaStato, Double sommeAccantonate, String istruttoriaTipologia, String responsabileUfficio, String responsabileUfficio2) {
        super(ElencoProgettiNeve.ELENCO_PROGETTI_NEVE);

        setId(id);
        setIdComune(idComune);
        setComune(comune);
        setProv(prov);
        setIdProvvisorio(idProvvisorio);
        setProtNum(protNum);
        setProtData(protData);
        setDenominazione(denominazione);
        setPi(pi);
        setCf(cf);
        setImportoImmobili(importoImmobili);
        setImportoMobili(importoMobili);
        setImportoDemolizioni(importoDemolizioni);
        setImportoScorte(importoScorte);
        setTipoIntervento(tipoIntervento);
        setIndirizzo(indirizzo);
        setStatoLavori(statoLavori);
        setIdRicognizione(idRicognizione);
        setIstruttoriaStato(istruttoriaStato);
        setSommeAccantonate(sommeAccantonate);
        setIstruttoriaTipologia(istruttoriaTipologia);
        setResponsabileUfficio(responsabileUfficio);
        setResponsabileUfficio2(responsabileUfficio2);
        resetChangedOnNotNull();
    }
}
