/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.GismanagerUtenti;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GismanagerUtentiRecord extends UpdatableRecordImpl<GismanagerUtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.gismanager_utenti.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.gismanager_utenti.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>decreti.gismanager_utenti.abilitato</code>.
     */
    public void setAbilitato(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.gismanager_utenti.abilitato</code>.
     */
    public Byte getAbilitato() {
        return (Byte) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GismanagerUtentiRecord
     */
    public GismanagerUtentiRecord() {
        super(GismanagerUtenti.GISMANAGER_UTENTI);
    }

    /**
     * Create a detached, initialised GismanagerUtentiRecord
     */
    public GismanagerUtentiRecord(String username, Byte abilitato) {
        super(GismanagerUtenti.GISMANAGER_UTENTI);

        setUsername(username);
        setAbilitato(abilitato);
        resetChangedOnNotNull();
    }
}
