/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.GisManifestazDettaglio;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GisManifestazDettaglioRecord extends UpdatableRecordImpl<GisManifestazDettaglioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.gis_manifestaz_dettaglio.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.gis_manifestaz_dettaglio.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.gis_manifestaz_dettaglio.id_poligon</code>.
     */
    public void setIdPoligon(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.gis_manifestaz_dettaglio.id_poligon</code>.
     */
    public Integer getIdPoligon() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>decreti.gis_manifestaz_dettaglio.codice_manifestazione</code>.
     */
    public void setCodiceManifestazione(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>decreti.gis_manifestaz_dettaglio.codice_manifestazione</code>.
     */
    public String getCodiceManifestazione() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>decreti.gis_manifestaz_dettaglio.data_manifestazione</code>.
     */
    public void setDataManifestazione(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>decreti.gis_manifestaz_dettaglio.data_manifestazione</code>.
     */
    public LocalDate getDataManifestazione() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GisManifestazDettaglioRecord
     */
    public GisManifestazDettaglioRecord() {
        super(GisManifestazDettaglio.GIS_MANIFESTAZ_DETTAGLIO);
    }

    /**
     * Create a detached, initialised GisManifestazDettaglioRecord
     */
    public GisManifestazDettaglioRecord(Integer id, Integer idPoligon, String codiceManifestazione, LocalDate dataManifestazione) {
        super(GisManifestazDettaglio.GIS_MANIFESTAZ_DETTAGLIO);

        setId(id);
        setIdPoligon(idPoligon);
        setCodiceManifestazione(codiceManifestazione);
        setDataManifestazione(dataManifestazione);
        resetTouchedOnNotNull();
    }
}
