/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.GisPrivataInterfaccia;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GisPrivataInterfacciaRecord extends UpdatableRecordImpl<GisPrivataInterfacciaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>decreti.gis_privata_interfaccia.id_pratica_poligono</code>.
     */
    public void setIdPraticaPoligono(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>decreti.gis_privata_interfaccia.id_pratica_poligono</code>.
     */
    public Integer getIdPraticaPoligono() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.gis_privata_interfaccia.id_pratica</code>.
     */
    public void setIdPratica(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.gis_privata_interfaccia.id_pratica</code>.
     */
    public Integer getIdPratica() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.gis_privata_interfaccia.dataora</code>.
     */
    public void setDataora(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.gis_privata_interfaccia.dataora</code>.
     */
    public LocalDateTime getDataora() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GisPrivataInterfacciaRecord
     */
    public GisPrivataInterfacciaRecord() {
        super(GisPrivataInterfaccia.GIS_PRIVATA_INTERFACCIA);
    }

    /**
     * Create a detached, initialised GisPrivataInterfacciaRecord
     */
    public GisPrivataInterfacciaRecord(Integer idPraticaPoligono, Integer idPratica, LocalDateTime dataora) {
        super(GisPrivataInterfaccia.GIS_PRIVATA_INTERFACCIA);

        setIdPraticaPoligono(idPraticaPoligono);
        setIdPratica(idPratica);
        setDataora(dataora);
        resetChangedOnNotNull();
    }
}
