/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.IdPraticheConRigetto;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IdPraticheConRigettoRecord extends TableRecordImpl<IdPraticheConRigettoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>decreti.id_pratiche_con_rigetto.id_pratica_con_rigetto</code>.
     */
    public void setIdPraticaConRigetto(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>decreti.id_pratiche_con_rigetto.id_pratica_con_rigetto</code>.
     */
    public Integer getIdPraticaConRigetto() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdPraticheConRigettoRecord
     */
    public IdPraticheConRigettoRecord() {
        super(IdPraticheConRigetto.ID_PRATICHE_CON_RIGETTO);
    }

    /**
     * Create a detached, initialised IdPraticheConRigettoRecord
     */
    public IdPraticheConRigettoRecord(Integer idPraticaConRigetto) {
        super(IdPraticheConRigetto.ID_PRATICHE_CON_RIGETTO);

        setIdPraticaConRigetto(idPraticaConRigetto);
        resetChangedOnNotNull();
    }
}
