/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.IstruttoriUffici;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IstruttoriUfficiRecord extends UpdatableRecordImpl<IstruttoriUfficiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.istruttori_uffici.id_istruttore_ufficio</code>.
     */
    public void setIdIstruttoreUfficio(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.istruttori_uffici.id_istruttore_ufficio</code>.
     */
    public Integer getIdIstruttoreUfficio() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.istruttori_uffici.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.istruttori_uffici.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.istruttori_uffici.id_ufficio</code>.
     */
    public void setIdUfficio(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.istruttori_uffici.id_ufficio</code>.
     */
    public Integer getIdUfficio() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.istruttori_uffici.data_inizio</code>.
     */
    public void setDataInizio(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.istruttori_uffici.data_inizio</code>.
     */
    public LocalDateTime getDataInizio() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>decreti.istruttori_uffici.data_fine</code>.
     */
    public void setDataFine(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.istruttori_uffici.data_fine</code>.
     */
    public LocalDateTime getDataFine() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IstruttoriUfficiRecord
     */
    public IstruttoriUfficiRecord() {
        super(IstruttoriUffici.ISTRUTTORI_UFFICI);
    }

    /**
     * Create a detached, initialised IstruttoriUfficiRecord
     */
    public IstruttoriUfficiRecord(Integer idIstruttoreUfficio, Integer idUtente, Integer idUfficio, LocalDateTime dataInizio, LocalDateTime dataFine) {
        super(IstruttoriUffici.ISTRUTTORI_UFFICI);

        setIdIstruttoreUfficio(idIstruttoreUfficio);
        setIdUtente(idUtente);
        setIdUfficio(idUfficio);
        setDataInizio(dataInizio);
        setDataFine(dataFine);
        resetTouchedOnNotNull();
    }
}
