/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.IterA;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IterARecord extends UpdatableRecordImpl<IterARecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.iter_a.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.iter_a.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.iter_a.id_pratica</code>.
     */
    public void setIdPratica(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.iter_a.id_pratica</code>.
     */
    public Integer getIdPratica() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.iter_a.data_evento</code>.
     */
    public void setDataEvento(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.iter_a.data_evento</code>.
     */
    public LocalDate getDataEvento() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>decreti.iter_a.protocollo</code>.
     */
    public void setProtocollo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.iter_a.protocollo</code>.
     */
    public String getProtocollo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>decreti.iter_a.codice_evento</code>.
     */
    public void setCodiceEvento(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.iter_a.codice_evento</code>.
     */
    public Integer getCodiceEvento() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IterARecord
     */
    public IterARecord() {
        super(IterA.ITER_A);
    }

    /**
     * Create a detached, initialised IterARecord
     */
    public IterARecord(Integer id, Integer idPratica, LocalDate dataEvento, String protocollo, Integer codiceEvento) {
        super(IterA.ITER_A);

        setId(id);
        setIdPratica(idPratica);
        setDataEvento(dataEvento);
        setProtocollo(protocollo);
        setCodiceEvento(codiceEvento);
        resetTouchedOnNotNull();
    }
}
