/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.LLavoriEseguitiNeve;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LLavoriEseguitiNeveRecord extends UpdatableRecordImpl<LLavoriEseguitiNeveRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>decreti.l_lavori_eseguiti_neve.id_lavori_eseguiti_neve</code>.
     */
    public void setIdLavoriEseguitiNeve(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>decreti.l_lavori_eseguiti_neve.id_lavori_eseguiti_neve</code>.
     */
    public Integer getIdLavoriEseguitiNeve() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.l_lavori_eseguiti_neve.attivo</code>.
     */
    public void setAttivo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.l_lavori_eseguiti_neve.attivo</code>.
     */
    public Integer getAttivo() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>decreti.l_lavori_eseguiti_neve.lavori_eseguiti_neve</code>.
     */
    public void setLavoriEseguitiNeve(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>decreti.l_lavori_eseguiti_neve.lavori_eseguiti_neve</code>.
     */
    public String getLavoriEseguitiNeve() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LLavoriEseguitiNeveRecord
     */
    public LLavoriEseguitiNeveRecord() {
        super(LLavoriEseguitiNeve.L_LAVORI_ESEGUITI_NEVE);
    }

    /**
     * Create a detached, initialised LLavoriEseguitiNeveRecord
     */
    public LLavoriEseguitiNeveRecord(Integer idLavoriEseguitiNeve, Integer attivo, String lavoriEseguitiNeve) {
        super(LLavoriEseguitiNeve.L_LAVORI_ESEGUITI_NEVE);

        setIdLavoriEseguitiNeve(idLavoriEseguitiNeve);
        setAttivo(attivo);
        setLavoriEseguitiNeve(lavoriEseguitiNeve);
        resetTouchedOnNotNull();
    }
}
