/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.LogUtenti;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LogUtentiRecord extends UpdatableRecordImpl<LogUtentiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.log_utenti.id_log</code>.
     */
    public void setIdLog(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.id_log</code>.
     */
    public Integer getIdLog() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.log_utenti.data_ora</code>.
     */
    public void setDataOra(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.data_ora</code>.
     */
    public LocalDateTime getDataOra() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>decreti.log_utenti.label</code>.
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.log_utenti.ip</code>.
     */
    public void setIp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.ip</code>.
     */
    public String getIp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>decreti.log_utenti.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>decreti.log_utenti.id_sessione</code>.
     */
    public void setIdSessione(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.id_sessione</code>.
     */
    public String getIdSessione() {
        return (String) get(5);
    }

    /**
     * Setter for <code>decreti.log_utenti.browser_client</code>.
     */
    public void setBrowserClient(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.log_utenti.browser_client</code>.
     */
    public String getBrowserClient() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogUtentiRecord
     */
    public LogUtentiRecord() {
        super(LogUtenti.LOG_UTENTI);
    }

    /**
     * Create a detached, initialised LogUtentiRecord
     */
    public LogUtentiRecord(Integer idLog, LocalDateTime dataOra, String label, String ip, Integer idUtente, String idSessione, String browserClient) {
        super(LogUtenti.LOG_UTENTI);

        setIdLog(idLog);
        setDataOra(dataOra);
        setLabel(label);
        setIp(ip);
        setIdUtente(idUtente);
        setIdSessione(idSessione);
        setBrowserClient(browserClient);
        resetChangedOnNotNull();
    }
}
