/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.LRuolo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LRuoloRecord extends UpdatableRecordImpl<LRuoloRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.l_ruolo.id_ruolo</code>.
     */
    public void setIdRuolo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.l_ruolo.id_ruolo</code>.
     */
    public Integer getIdRuolo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.l_ruolo.codice</code>.
     */
    public void setCodice(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.l_ruolo.codice</code>.
     */
    public String getCodice() {
        return (String) get(1);
    }

    /**
     * Setter for <code>decreti.l_ruolo.ruolo</code>.
     */
    public void setRuolo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.l_ruolo.ruolo</code>.
     */
    public String getRuolo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.l_ruolo.permessi_predefiniti</code>.
     */
    public void setPermessiPredefiniti(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.l_ruolo.permessi_predefiniti</code>.
     */
    public Integer getPermessiPredefiniti() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LRuoloRecord
     */
    public LRuoloRecord() {
        super(LRuolo.L_RUOLO);
    }

    /**
     * Create a detached, initialised LRuoloRecord
     */
    public LRuoloRecord(Integer idRuolo, String codice, String ruolo, Integer permessiPredefiniti) {
        super(LRuolo.L_RUOLO);

        setIdRuolo(idRuolo);
        setCodice(codice);
        setRuolo(ruolo);
        setPermessiPredefiniti(permessiPredefiniti);
        resetTouchedOnNotNull();
    }
}
