/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.LTipoLayer;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LTipoLayerRecord extends UpdatableRecordImpl<LTipoLayerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.l_tipo_layer.id_layer</code>.
     */
    public void setIdLayer(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.l_tipo_layer.id_layer</code>.
     */
    public Integer getIdLayer() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.l_tipo_layer.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.l_tipo_layer.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LTipoLayerRecord
     */
    public LTipoLayerRecord() {
        super(LTipoLayer.L_TIPO_LAYER);
    }

    /**
     * Create a detached, initialised LTipoLayerRecord
     */
    public LTipoLayerRecord(Integer idLayer, String descrizione) {
        super(LTipoLayer.L_TIPO_LAYER);

        setIdLayer(idLayer);
        setDescrizione(descrizione);
        resetTouchedOnNotNull();
    }
}
