/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.Membro;

import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MembroRecord extends TableRecordImpl<MembroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.membro.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.membro.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.membro.id_gruppo</code>.
     */
    public void setIdGruppo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.membro.id_gruppo</code>.
     */
    public String getIdGruppo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>decreti.membro.data_inizio</code>.
     */
    public void setDataInizio(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.membro.data_inizio</code>.
     */
    public LocalDate getDataInizio() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>decreti.membro.data_fine</code>.
     */
    public void setDataFine(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.membro.data_fine</code>.
     */
    public LocalDate getDataFine() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembroRecord
     */
    public MembroRecord() {
        super(Membro.MEMBRO);
    }

    /**
     * Create a detached, initialised MembroRecord
     */
    public MembroRecord(Integer idUtente, String idGruppo, LocalDate dataInizio, LocalDate dataFine) {
        super(Membro.MEMBRO);

        setIdUtente(idUtente);
        setIdGruppo(idGruppo);
        setDataInizio(dataInizio);
        setDataFine(dataFine);
        resetTouchedOnNotNull();
    }
}
