/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.MonIter;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonIterRecord extends UpdatableRecordImpl<MonIterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.mon_iter.ID_iter</code>.
     */
    public void setIdIter(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.ID_iter</code>.
     */
    public Integer getIdIter() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.mon_iter.ID_Pratica</code>.
     */
    public void setIdPratica(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.ID_Pratica</code>.
     */
    public Integer getIdPratica() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.mon_iter.istruttore</code>.
     */
    public void setIstruttore(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.istruttore</code>.
     */
    public String getIstruttore() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.mon_iter.data</code>.
     */
    public void setData(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.data</code>.
     */
    public LocalDateTime getData() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>decreti.mon_iter.prot_n</code>.
     */
    public void setProtN(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.prot_n</code>.
     */
    public String getProtN() {
        return (String) get(4);
    }

    /**
     * Setter for <code>decreti.mon_iter.codice_passo</code>.
     */
    public void setCodicePasso(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.codice_passo</code>.
     */
    public Short getCodicePasso() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>decreti.mon_iter.IstanzaMude</code>.
     */
    public void setIstanzamude(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.IstanzaMude</code>.
     */
    public String getIstanzamude() {
        return (String) get(6);
    }

    /**
     * Setter for <code>decreti.mon_iter.TipoIstanza</code>.
     */
    public void setTipoistanza(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.TipoIstanza</code>.
     */
    public String getTipoistanza() {
        return (String) get(7);
    }

    /**
     * Setter for <code>decreti.mon_iter.note</code>.
     */
    public void setNote(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.mon_iter.note</code>.
     */
    public String getNote() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonIterRecord
     */
    public MonIterRecord() {
        super(MonIter.MON_ITER);
    }

    /**
     * Create a detached, initialised MonIterRecord
     */
    public MonIterRecord(Integer idIter, Integer idPratica, String istruttore, LocalDateTime data, String protN, Short codicePasso, String istanzamude, String tipoistanza, String note) {
        super(MonIter.MON_ITER);

        setIdIter(idIter);
        setIdPratica(idPratica);
        setIstruttore(istruttore);
        setData(data);
        setProtN(protN);
        setCodicePasso(codicePasso);
        setIstanzamude(istanzamude);
        setTipoistanza(tipoistanza);
        setNote(note);
        resetTouchedOnNotNull();
    }
}
