/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.MonLivOpCatastale;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonLivOpCatastaleRecord extends UpdatableRecordImpl<MonLivOpCatastaleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.ora</code>.
     */
    public void setOra(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.ora</code>.
     */
    public LocalDateTime getOra() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.id_vlo</code>.
     */
    public void setIdVlo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.id_vlo</code>.
     */
    public String getIdVlo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.comune</code>.
     */
    public void setComune(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.comune</code>.
     */
    public String getComune() {
        return (String) get(3);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.istat_comune</code>.
     */
    public void setIstatComune(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.istat_comune</code>.
     */
    public String getIstatComune() {
        return (String) get(4);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.foglio</code>.
     */
    public void setFoglio(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.foglio</code>.
     */
    public String getFoglio() {
        return (String) get(5);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.mappale</code>.
     */
    public void setMappale(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.mappale</code>.
     */
    public String getMappale() {
        return (String) get(6);
    }

    /**
     * Setter for <code>decreti.mon_liv_op_catastale.data_istanza</code>.
     */
    public void setDataIstanza(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.mon_liv_op_catastale.data_istanza</code>.
     */
    public LocalDate getDataIstanza() {
        return (LocalDate) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonLivOpCatastaleRecord
     */
    public MonLivOpCatastaleRecord() {
        super(MonLivOpCatastale.MON_LIV_OP_CATASTALE);
    }

    /**
     * Create a detached, initialised MonLivOpCatastaleRecord
     */
    public MonLivOpCatastaleRecord(Integer id, LocalDateTime ora, String idVlo, String comune, String istatComune, String foglio, String mappale, LocalDate dataIstanza) {
        super(MonLivOpCatastale.MON_LIV_OP_CATASTALE);

        setId(id);
        setOra(ora);
        setIdVlo(idVlo);
        setComune(comune);
        setIstatComune(istatComune);
        setFoglio(foglio);
        setMappale(mappale);
        setDataIstanza(dataIstanza);
        resetTouchedOnNotNull();
    }
}
