/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.ProcAcl;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcAclRecord extends UpdatableRecordImpl<ProcAclRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.proc_acl.id_proc_acl</code>.
     */
    public void setIdProcAcl(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_proc_acl</code>.
     */
    public Integer getIdProcAcl() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_tipo_proc</code>.
     */
    public void setIdTipoProc(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_tipo_proc</code>.
     */
    public Integer getIdTipoProc() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_proc</code>.
     */
    public void setIdProc(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_proc</code>.
     */
    public Integer getIdProc() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_ufficio</code>.
     */
    public void setIdUfficio(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_ufficio</code>.
     */
    public Integer getIdUfficio() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_ruolo</code>.
     */
    public void setIdRuolo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_ruolo</code>.
     */
    public Integer getIdRuolo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>decreti.proc_acl.autorizzazioni</code>.
     */
    public void setAutorizzazioni(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.autorizzazioni</code>.
     */
    public Integer getAutorizzazioni() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_utente_assegnante</code>.
     */
    public void setIdUtenteAssegnante(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_utente_assegnante</code>.
     */
    public Integer getIdUtenteAssegnante() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_utente_delegante</code>.
     */
    public void setIdUtenteDelegante(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_utente_delegante</code>.
     */
    public Integer getIdUtenteDelegante() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>decreti.proc_acl.id_utente_rimozione</code>.
     */
    public void setIdUtenteRimozione(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.id_utente_rimozione</code>.
     */
    public Integer getIdUtenteRimozione() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>decreti.proc_acl.data_assegnazione</code>.
     */
    public void setDataAssegnazione(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.data_assegnazione</code>.
     */
    public LocalDateTime getDataAssegnazione() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>decreti.proc_acl.data_subentro</code>.
     */
    public void setDataSubentro(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.data_subentro</code>.
     */
    public LocalDateTime getDataSubentro() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>decreti.proc_acl.data_rimozione</code>.
     */
    public void setDataRimozione(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.data_rimozione</code>.
     */
    public LocalDateTime getDataRimozione() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>decreti.proc_acl.dataora</code>.
     */
    public void setDataora(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.dataora</code>.
     */
    public LocalDateTime getDataora() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>decreti.proc_acl.note</code>.
     */
    public void setNote(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>decreti.proc_acl.note</code>.
     */
    public String getNote() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcAclRecord
     */
    public ProcAclRecord() {
        super(ProcAcl.PROC_ACL);
    }

    /**
     * Create a detached, initialised ProcAclRecord
     */
    public ProcAclRecord(Integer idProcAcl, Integer idTipoProc, Integer idProc, Integer idUtente, Integer idUfficio, Integer idRuolo, Integer autorizzazioni, Integer idUtenteAssegnante, Integer idUtenteDelegante, Integer idUtenteRimozione, LocalDateTime dataAssegnazione, LocalDateTime dataSubentro, LocalDateTime dataRimozione, LocalDateTime dataora, String note) {
        super(ProcAcl.PROC_ACL);

        setIdProcAcl(idProcAcl);
        setIdTipoProc(idTipoProc);
        setIdProc(idProc);
        setIdUtente(idUtente);
        setIdUfficio(idUfficio);
        setIdRuolo(idRuolo);
        setAutorizzazioni(autorizzazioni);
        setIdUtenteAssegnante(idUtenteAssegnante);
        setIdUtenteDelegante(idUtenteDelegante);
        setIdUtenteRimozione(idUtenteRimozione);
        setDataAssegnazione(dataAssegnazione);
        setDataSubentro(dataSubentro);
        setDataRimozione(dataRimozione);
        setDataora(dataora);
        setNote(note);
        resetTouchedOnNotNull();
    }
}
