/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.ProcCat;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcCatRecord extends UpdatableRecordImpl<ProcCatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.proc_cat.id_proc_cat</code>.
     */
    public void setIdProcCat(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.id_proc_cat</code>.
     */
    public Integer getIdProcCat() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.proc_cat.id_proc</code>.
     */
    public void setIdProc(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.id_proc</code>.
     */
    public Integer getIdProc() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.proc_cat.attivo</code>.
     */
    public void setAttivo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.attivo</code>.
     */
    public Integer getAttivo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.proc_cat.istat_comune</code>.
     */
    public void setIstatComune(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.istat_comune</code>.
     */
    public String getIstatComune() {
        return (String) get(3);
    }

    /**
     * Setter for <code>decreti.proc_cat.sezione</code>.
     */
    public void setSezione(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.sezione</code>.
     */
    public String getSezione() {
        return (String) get(4);
    }

    /**
     * Setter for <code>decreti.proc_cat.foglio</code>.
     */
    public void setFoglio(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.foglio</code>.
     */
    public String getFoglio() {
        return (String) get(5);
    }

    /**
     * Setter for <code>decreti.proc_cat.particella</code>.
     */
    public void setParticella(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.proc_cat.particella</code>.
     */
    public String getParticella() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcCatRecord
     */
    public ProcCatRecord() {
        super(ProcCat.PROC_CAT);
    }

    /**
     * Create a detached, initialised ProcCatRecord
     */
    public ProcCatRecord(Integer idProcCat, Integer idProc, Integer attivo, String istatComune, String sezione, String foglio, String particella) {
        super(ProcCat.PROC_CAT);

        setIdProcCat(idProcCat);
        setIdProc(idProc);
        setAttivo(attivo);
        setIstatComune(istatComune);
        setSezione(sezione);
        setFoglio(foglio);
        setParticella(particella);
        resetTouchedOnNotNull();
    }
}
