/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.ProcAssAttuali;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcAssAttualiRecord extends UpdatableRecordImpl<ProcAssAttualiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.proc_ass_attuali.id_proc_ass_attuali</code>.
     */
    public void setIdProcAssAttuali(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.proc_ass_attuali.id_proc_ass_attuali</code>.
     */
    public Integer getIdProcAssAttuali() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.proc_ass_attuali.id_proc</code>.
     */
    public void setIdProc(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.proc_ass_attuali.id_proc</code>.
     */
    public Integer getIdProc() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.proc_ass_attuali.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.proc_ass_attuali.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.proc_ass_attuali.id_ruolo</code>.
     */
    public void setIdRuolo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.proc_ass_attuali.id_ruolo</code>.
     */
    public Integer getIdRuolo() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcAssAttualiRecord
     */
    public ProcAssAttualiRecord() {
        super(ProcAssAttuali.PROC_ASS_ATTUALI);
    }

    /**
     * Create a detached, initialised ProcAssAttualiRecord
     */
    public ProcAssAttualiRecord(Integer idProcAssAttuali, Integer idProc, Integer idUtente, Integer idRuolo) {
        super(ProcAssAttuali.PROC_ASS_ATTUALI);

        setIdProcAssAttuali(idProcAssAttuali);
        setIdProc(idProc);
        setIdUtente(idUtente);
        setIdRuolo(idRuolo);
        resetChangedOnNotNull();
    }
}
