/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.ProcFun;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcFunRecord extends UpdatableRecordImpl<ProcFunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.proc_fun.id_proc_fun</code>.
     */
    public void setIdProcFun(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.proc_fun.id_proc_fun</code>.
     */
    public Integer getIdProcFun() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.proc_fun.codice_app</code>.
     */
    public void setCodiceApp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.proc_fun.codice_app</code>.
     */
    public String getCodiceApp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>decreti.proc_fun.codice_fun</code>.
     */
    public void setCodiceFun(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.proc_fun.codice_fun</code>.
     */
    public String getCodiceFun() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.proc_fun.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.proc_fun.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcFunRecord
     */
    public ProcFunRecord() {
        super(ProcFun.PROC_FUN);
    }

    /**
     * Create a detached, initialised ProcFunRecord
     */
    public ProcFunRecord(Integer idProcFun, String codiceApp, String codiceFun, String descrizione) {
        super(ProcFun.PROC_FUN);

        setIdProcFun(idProcFun);
        setCodiceApp(codiceApp);
        setCodiceFun(codiceFun);
        setDescrizione(descrizione);
        resetTouchedOnNotNull();
    }
}
