/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.ProgettiPrivata;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProgettiPrivataRecord extends TableRecordImpl<ProgettiPrivataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.progetti_privata.ID_Pratica</code>.
     */
    public void setIdPratica(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.ID_Pratica</code>.
     */
    public Integer getIdPratica() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.progetti_privata.Comune</code>.
     */
    public void setComune(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.Comune</code>.
     */
    public String getComune() {
        return (String) get(1);
    }

    /**
     * Setter for <code>decreti.progetti_privata.destinatario</code>.
     */
    public void setDestinatario(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.destinatario</code>.
     */
    public String getDestinatario() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.progetti_privata.id_tipo_proprieta</code>.
     */
    public void setIdTipoProprieta(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.id_tipo_proprieta</code>.
     */
    public Integer getIdTipoProprieta() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.progetti_privata.id_tipo_pratica</code>.
     */
    public void setIdTipoPratica(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.id_tipo_pratica</code>.
     */
    public Integer getIdTipoPratica() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>decreti.progetti_privata.id_ordinanza_riferimento</code>.
     */
    public void setIdOrdinanzaRiferimento(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>decreti.progetti_privata.id_ordinanza_riferimento</code>.
     */
    public Integer getIdOrdinanzaRiferimento() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>decreti.progetti_privata.stato</code>.
     */
    public void setStato(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.stato</code>.
     */
    public Integer getStato() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>decreti.progetti_privata.Abit_Principale</code>.
     */
    public void setAbitPrincipale(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.Abit_Principale</code>.
     */
    public String getAbitPrincipale() {
        return (String) get(7);
    }

    /**
     * Setter for <code>decreti.progetti_privata.Assistenza</code>.
     */
    public void setAssistenza(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.Assistenza</code>.
     */
    public String getAssistenza() {
        return (String) get(8);
    }

    /**
     * Setter for <code>decreti.progetti_privata.Att_Produttiva</code>.
     */
    public void setAttProduttiva(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.Att_Produttiva</code>.
     */
    public String getAttProduttiva() {
        return (String) get(9);
    }

    /**
     * Setter for <code>decreti.progetti_privata.ord100</code>.
     */
    public void setOrd100(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>decreti.progetti_privata.ord100</code>.
     */
    public Integer getOrd100() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgettiPrivataRecord
     */
    public ProgettiPrivataRecord() {
        super(ProgettiPrivata.PROGETTI_PRIVATA);
    }

    /**
     * Create a detached, initialised ProgettiPrivataRecord
     */
    public ProgettiPrivataRecord(Integer idPratica, String comune, String destinatario, Integer idTipoProprieta, Integer idTipoPratica, Integer idOrdinanzaRiferimento, Integer stato, String abitPrincipale, String assistenza, String attProduttiva, Integer ord100) {
        super(ProgettiPrivata.PROGETTI_PRIVATA);

        setIdPratica(idPratica);
        setComune(comune);
        setDestinatario(destinatario);
        setIdTipoProprieta(idTipoProprieta);
        setIdTipoPratica(idTipoPratica);
        setIdOrdinanzaRiferimento(idOrdinanzaRiferimento);
        setStato(stato);
        setAbitPrincipale(abitPrincipale);
        setAssistenza(assistenza);
        setAttProduttiva(attProduttiva);
        setOrd100(ord100);
        resetChangedOnNotNull();
    }
}
