/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.Reportcommissario;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportcommissarioRecord extends UpdatableRecordImpl<ReportcommissarioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.reportcommissario.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerofascicolomude</code>.
     */
    public void setNumerofascicolomude(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerofascicolomude</code>.
     */
    public String getNumerofascicolomude() {
        return (String) get(1);
    }

    /**
     * Setter for <code>decreti.reportcommissario.ordinanza</code>.
     */
    public void setOrdinanza(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.ordinanza</code>.
     */
    public Integer getOrdinanza() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.reportcommissario.ordinanza100</code>.
     */
    public void setOrdinanza100(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.ordinanza100</code>.
     */
    public String getOrdinanza100() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.sorteggiatoperverificaacampione</code>.
     */
    public void setSorteggiatoperverificaacampione(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.sorteggiatoperverificaacampione</code>.
     */
    public String getSorteggiatoperverificaacampione() {
        return (String) get(4);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numeroprotocollousr</code>.
     */
    public void setNumeroprotocollousr(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numeroprotocollousr</code>.
     */
    public String getNumeroprotocollousr() {
        return (String) get(5);
    }

    /**
     * Setter for <code>decreti.reportcommissario.dataprotocollousr</code>.
     */
    public void setDataprotocollousr(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.dataprotocollousr</code>.
     */
    public LocalDate getDataprotocollousr() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerofascicolousr</code>.
     */
    public void setNumerofascicolousr(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerofascicolousr</code>.
     */
    public String getNumerofascicolousr() {
        return (String) get(7);
    }

    /**
     * Setter for <code>decreti.reportcommissario.cfintestatario</code>.
     */
    public void setCfintestatario(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.cfintestatario</code>.
     */
    public String getCfintestatario() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.nomecognomeintestatario</code>.
     */
    public void setNomecognomeintestatario(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.nomecognomeintestatario</code>.
     */
    public String getNomecognomeintestatario() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.titolaritagiuridicarichiedente</code>.
     */
    public void setTitolaritagiuridicarichiedente(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.titolaritagiuridicarichiedente</code>.
     */
    public String getTitolaritagiuridicarichiedente() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.cfprofessionistacapogruppo</code>.
     */
    public void setCfprofessionistacapogruppo(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.cfprofessionistacapogruppo</code>.
     */
    public String getCfprofessionistacapogruppo() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.nomecognomeprofessionistacapogruppo</code>.
     */
    public void setNomecognomeprofessionistacapogruppo(String value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.nomecognomeprofessionistacapogruppo</code>.
     */
    public String getNomecognomeprofessionistacapogruppo() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.cfopivaimpresaaffidataria</code>.
     */
    public void setCfopivaimpresaaffidataria(String value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.cfopivaimpresaaffidataria</code>.
     */
    public String getCfopivaimpresaaffidataria() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.ragionesocialeimpresaaffidataria</code>.
     */
    public void setRagionesocialeimpresaaffidataria(String value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.ragionesocialeimpresaaffidataria</code>.
     */
    public String getRagionesocialeimpresaaffidataria() {
        return (String) get(14);
    }

    /**
     * Setter for <code>decreti.reportcommissario.codiceistatprovincia</code>.
     */
    public void setCodiceistatprovincia(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.codiceistatprovincia</code>.
     */
    public String getCodiceistatprovincia() {
        return (String) get(15);
    }

    /**
     * Setter for <code>decreti.reportcommissario.codiceistatcomune</code>.
     */
    public void setCodiceistatcomune(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.codiceistatcomune</code>.
     */
    public String getCodiceistatcomune() {
        return (String) get(16);
    }

    /**
     * Setter for <code>decreti.reportcommissario.indirizzo</code>.
     */
    public void setIndirizzo(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.indirizzo</code>.
     */
    public String getIndirizzo() {
        return (String) get(17);
    }

    /**
     * Setter for <code>decreti.reportcommissario.foglio</code>.
     */
    public void setFoglio(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.foglio</code>.
     */
    public String getFoglio() {
        return (String) get(18);
    }

    /**
     * Setter for <code>decreti.reportcommissario.mappaleterreni</code>.
     */
    public void setMappaleterreni(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.mappaleterreni</code>.
     */
    public String getMappaleterreni() {
        return (String) get(19);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.destinazioneusoprevalente</code>.
     */
    public void setDestinazioneusoprevalente(String value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.destinazioneusoprevalente</code>.
     */
    public String getDestinazioneusoprevalente() {
        return (String) get(20);
    }

    /**
     * Setter for <code>decreti.reportcommissario.livellooperativo</code>.
     */
    public void setLivellooperativo(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.livellooperativo</code>.
     */
    public String getLivellooperativo() {
        return (String) get(21);
    }

    /**
     * Setter for <code>decreti.reportcommissario.tipologiaintervento</code>.
     */
    public void setTipologiaintervento(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.tipologiaintervento</code>.
     */
    public String getTipologiaintervento() {
        return (String) get(22);
    }

    /**
     * Setter for <code>decreti.reportcommissario.interventoaggregato</code>.
     */
    public void setInterventoaggregato(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.interventoaggregato</code>.
     */
    public String getInterventoaggregato() {
        return (String) get(23);
    }

    /**
     * Setter for <code>decreti.reportcommissario.totustrutturali</code>.
     */
    public void setTotustrutturali(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.totustrutturali</code>.
     */
    public Integer getTotustrutturali() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>decreti.reportcommissario.totui</code>.
     */
    public void setTotui(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.totui</code>.
     */
    public Integer getTotui() {
        return (Integer) get(25);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.totuiprincipalioattprodese</code>.
     */
    public void setTotuiprincipalioattprodese(Integer value) {
        set(26, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.totuiprincipalioattprodese</code>.
     */
    public Integer getTotuiprincipalioattprodese() {
        return (Integer) get(26);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.istanzarigettataarchiviata</code>.
     */
    public void setIstanzarigettataarchiviata(String value) {
        set(27, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.istanzarigettataarchiviata</code>.
     */
    public String getIstanzarigettataarchiviata() {
        return (String) get(27);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.datarigettoarchiviazione</code>.
     */
    public void setDatarigettoarchiviazione(LocalDate value) {
        set(28, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.datarigettoarchiviazione</code>.
     */
    public LocalDate getDatarigettoarchiviazione() {
        return (LocalDate) get(28);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.numerodecretocontributo</code>.
     */
    public void setNumerodecretocontributo(String value) {
        set(29, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.numerodecretocontributo</code>.
     */
    public String getNumerodecretocontributo() {
        return (String) get(29);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretocontributo</code>.
     */
    public void setDatadecretocontributo(LocalDate value) {
        set(30, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretocontributo</code>.
     */
    public LocalDate getDatadecretocontributo() {
        return (LocalDate) get(30);
    }

    /**
     * Setter for <code>decreti.reportcommissario.cup</code>.
     */
    public void setCup(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.cup</code>.
     */
    public String getCup() {
        return (String) get(31);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.datapresentazioneanticipazionespesetecniche</code>.
     */
    public void setDatapresentazioneanticipazionespesetecniche(LocalDate value) {
        set(32, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.datapresentazioneanticipazionespesetecniche</code>.
     */
    public LocalDate getDatapresentazioneanticipazionespesetecniche() {
        return (LocalDate) get(32);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.numerodecretoanticipazionespesetecniche</code>.
     */
    public void setNumerodecretoanticipazionespesetecniche(String value) {
        set(33, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.numerodecretoanticipazionespesetecniche</code>.
     */
    public String getNumerodecretoanticipazionespesetecniche() {
        return (String) get(33);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.datadecretoanticipazionespesetecniche</code>.
     */
    public void setDatadecretoanticipazionespesetecniche(LocalDate value) {
        set(34, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.datadecretoanticipazionespesetecniche</code>.
     */
    public LocalDate getDatadecretoanticipazionespesetecniche() {
        return (LocalDate) get(34);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.importoanticipazionespesetecniche</code>.
     */
    public void setImportoanticipazionespesetecniche(BigDecimal value) {
        set(35, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.importoanticipazionespesetecniche</code>.
     */
    public BigDecimal getImportoanticipazionespesetecniche() {
        return (BigDecimal) get(35);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datapresentazionesal0</code>.
     */
    public void setDatapresentazionesal0(LocalDate value) {
        set(36, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datapresentazionesal0</code>.
     */
    public LocalDate getDatapresentazionesal0() {
        return (LocalDate) get(36);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerodecretosal0</code>.
     */
    public void setNumerodecretosal0(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerodecretosal0</code>.
     */
    public String getNumerodecretosal0() {
        return (String) get(37);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretosal0</code>.
     */
    public void setDatadecretosal0(LocalDate value) {
        set(38, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretosal0</code>.
     */
    public LocalDate getDatadecretosal0() {
        return (LocalDate) get(38);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datapresentazionesal20</code>.
     */
    public void setDatapresentazionesal20(LocalDate value) {
        set(39, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datapresentazionesal20</code>.
     */
    public LocalDate getDatapresentazionesal20() {
        return (LocalDate) get(39);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerodecretosal20</code>.
     */
    public void setNumerodecretosal20(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerodecretosal20</code>.
     */
    public String getNumerodecretosal20() {
        return (String) get(40);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretosal20</code>.
     */
    public void setDatadecretosal20(LocalDate value) {
        set(41, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretosal20</code>.
     */
    public LocalDate getDatadecretosal20() {
        return (LocalDate) get(41);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datapresentazionesal40</code>.
     */
    public void setDatapresentazionesal40(LocalDate value) {
        set(42, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datapresentazionesal40</code>.
     */
    public LocalDate getDatapresentazionesal40() {
        return (LocalDate) get(42);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerodecretosal40</code>.
     */
    public void setNumerodecretosal40(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerodecretosal40</code>.
     */
    public String getNumerodecretosal40() {
        return (String) get(43);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretosal40</code>.
     */
    public void setDatadecretosal40(LocalDate value) {
        set(44, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretosal40</code>.
     */
    public LocalDate getDatadecretosal40() {
        return (LocalDate) get(44);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datapresentazionesal50</code>.
     */
    public void setDatapresentazionesal50(LocalDate value) {
        set(45, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datapresentazionesal50</code>.
     */
    public LocalDate getDatapresentazionesal50() {
        return (LocalDate) get(45);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerodecretosal50</code>.
     */
    public void setNumerodecretosal50(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerodecretosal50</code>.
     */
    public String getNumerodecretosal50() {
        return (String) get(46);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretosal50</code>.
     */
    public void setDatadecretosal50(LocalDate value) {
        set(47, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretosal50</code>.
     */
    public LocalDate getDatadecretosal50() {
        return (LocalDate) get(47);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datapresentazionesal70</code>.
     */
    public void setDatapresentazionesal70(LocalDate value) {
        set(48, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datapresentazionesal70</code>.
     */
    public LocalDate getDatapresentazionesal70() {
        return (LocalDate) get(48);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerodecretosal70</code>.
     */
    public void setNumerodecretosal70(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerodecretosal70</code>.
     */
    public String getNumerodecretosal70() {
        return (String) get(49);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretosal70</code>.
     */
    public void setDatadecretosal70(LocalDate value) {
        set(50, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretosal70</code>.
     */
    public LocalDate getDatadecretosal70() {
        return (LocalDate) get(50);
    }

    /**
     * Setter for
     * <code>decreti.reportcommissario.datapresentazionesalfinale</code>.
     */
    public void setDatapresentazionesalfinale(LocalDate value) {
        set(51, value);
    }

    /**
     * Getter for
     * <code>decreti.reportcommissario.datapresentazionesalfinale</code>.
     */
    public LocalDate getDatapresentazionesalfinale() {
        return (LocalDate) get(51);
    }

    /**
     * Setter for <code>decreti.reportcommissario.numerodecretosalfinale</code>.
     */
    public void setNumerodecretosalfinale(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.numerodecretosalfinale</code>.
     */
    public String getNumerodecretosalfinale() {
        return (String) get(52);
    }

    /**
     * Setter for <code>decreti.reportcommissario.datadecretosalfinale</code>.
     */
    public void setDatadecretosalfinale(LocalDate value) {
        set(53, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.datadecretosalfinale</code>.
     */
    public LocalDate getDatadecretosalfinale() {
        return (LocalDate) get(53);
    }

    /**
     * Setter for <code>decreti.reportcommissario.contributoconcesso</code>.
     */
    public void setContributoconcesso(BigDecimal value) {
        set(54, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.contributoconcesso</code>.
     */
    public BigDecimal getContributoconcesso() {
        return (BigDecimal) get(54);
    }

    /**
     * Setter for <code>decreti.reportcommissario.contributoliquidato</code>.
     */
    public void setContributoliquidato(BigDecimal value) {
        set(55, value);
    }

    /**
     * Getter for <code>decreti.reportcommissario.contributoliquidato</code>.
     */
    public BigDecimal getContributoliquidato() {
        return (BigDecimal) get(55);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportcommissarioRecord
     */
    public ReportcommissarioRecord() {
        super(Reportcommissario.REPORTCOMMISSARIO);
    }

    /**
     * Create a detached, initialised ReportcommissarioRecord
     */
    public ReportcommissarioRecord(Integer id, String numerofascicolomude, Integer ordinanza, String ordinanza100, String sorteggiatoperverificaacampione, String numeroprotocollousr, LocalDate dataprotocollousr, String numerofascicolousr, String cfintestatario, String nomecognomeintestatario, String titolaritagiuridicarichiedente, String cfprofessionistacapogruppo, String nomecognomeprofessionistacapogruppo, String cfopivaimpresaaffidataria, String ragionesocialeimpresaaffidataria, String codiceistatprovincia, String codiceistatcomune, String indirizzo, String foglio, String mappaleterreni, String destinazioneusoprevalente, String livellooperativo, String tipologiaintervento, String interventoaggregato, Integer totustrutturali, Integer totui, Integer totuiprincipalioattprodese, String istanzarigettataarchiviata, LocalDate datarigettoarchiviazione, String numerodecretocontributo, LocalDate datadecretocontributo, String cup, LocalDate datapresentazioneanticipazionespesetecniche, String numerodecretoanticipazionespesetecniche, LocalDate datadecretoanticipazionespesetecniche, BigDecimal importoanticipazionespesetecniche, LocalDate datapresentazionesal0, String numerodecretosal0, LocalDate datadecretosal0, LocalDate datapresentazionesal20, String numerodecretosal20, LocalDate datadecretosal20, LocalDate datapresentazionesal40, String numerodecretosal40, LocalDate datadecretosal40, LocalDate datapresentazionesal50, String numerodecretosal50, LocalDate datadecretosal50, LocalDate datapresentazionesal70, String numerodecretosal70, LocalDate datadecretosal70, LocalDate datapresentazionesalfinale, String numerodecretosalfinale, LocalDate datadecretosalfinale, BigDecimal contributoconcesso, BigDecimal contributoliquidato) {
        super(Reportcommissario.REPORTCOMMISSARIO);

        setId(id);
        setNumerofascicolomude(numerofascicolomude);
        setOrdinanza(ordinanza);
        setOrdinanza100(ordinanza100);
        setSorteggiatoperverificaacampione(sorteggiatoperverificaacampione);
        setNumeroprotocollousr(numeroprotocollousr);
        setDataprotocollousr(dataprotocollousr);
        setNumerofascicolousr(numerofascicolousr);
        setCfintestatario(cfintestatario);
        setNomecognomeintestatario(nomecognomeintestatario);
        setTitolaritagiuridicarichiedente(titolaritagiuridicarichiedente);
        setCfprofessionistacapogruppo(cfprofessionistacapogruppo);
        setNomecognomeprofessionistacapogruppo(nomecognomeprofessionistacapogruppo);
        setCfopivaimpresaaffidataria(cfopivaimpresaaffidataria);
        setRagionesocialeimpresaaffidataria(ragionesocialeimpresaaffidataria);
        setCodiceistatprovincia(codiceistatprovincia);
        setCodiceistatcomune(codiceistatcomune);
        setIndirizzo(indirizzo);
        setFoglio(foglio);
        setMappaleterreni(mappaleterreni);
        setDestinazioneusoprevalente(destinazioneusoprevalente);
        setLivellooperativo(livellooperativo);
        setTipologiaintervento(tipologiaintervento);
        setInterventoaggregato(interventoaggregato);
        setTotustrutturali(totustrutturali);
        setTotui(totui);
        setTotuiprincipalioattprodese(totuiprincipalioattprodese);
        setIstanzarigettataarchiviata(istanzarigettataarchiviata);
        setDatarigettoarchiviazione(datarigettoarchiviazione);
        setNumerodecretocontributo(numerodecretocontributo);
        setDatadecretocontributo(datadecretocontributo);
        setCup(cup);
        setDatapresentazioneanticipazionespesetecniche(datapresentazioneanticipazionespesetecniche);
        setNumerodecretoanticipazionespesetecniche(numerodecretoanticipazionespesetecniche);
        setDatadecretoanticipazionespesetecniche(datadecretoanticipazionespesetecniche);
        setImportoanticipazionespesetecniche(importoanticipazionespesetecniche);
        setDatapresentazionesal0(datapresentazionesal0);
        setNumerodecretosal0(numerodecretosal0);
        setDatadecretosal0(datadecretosal0);
        setDatapresentazionesal20(datapresentazionesal20);
        setNumerodecretosal20(numerodecretosal20);
        setDatadecretosal20(datadecretosal20);
        setDatapresentazionesal40(datapresentazionesal40);
        setNumerodecretosal40(numerodecretosal40);
        setDatadecretosal40(datadecretosal40);
        setDatapresentazionesal50(datapresentazionesal50);
        setNumerodecretosal50(numerodecretosal50);
        setDatadecretosal50(datadecretosal50);
        setDatapresentazionesal70(datapresentazionesal70);
        setNumerodecretosal70(numerodecretosal70);
        setDatadecretosal70(datadecretosal70);
        setDatapresentazionesalfinale(datapresentazionesalfinale);
        setNumerodecretosalfinale(numerodecretosalfinale);
        setDatadecretosalfinale(datadecretosalfinale);
        setContributoconcesso(contributoconcesso);
        setContributoliquidato(contributoliquidato);
        resetTouchedOnNotNull();
    }
}
