/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.RuoloAmbito;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RuoloAmbitoRecord extends UpdatableRecordImpl<RuoloAmbitoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.ruolo_ambito.idruolo_ambito</code>.
     */
    public void setIdruoloAmbito(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.ruolo_ambito.idruolo_ambito</code>.
     */
    public Integer getIdruoloAmbito() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.ruolo_ambito.id_ruolo</code>.
     */
    public void setIdRuolo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.ruolo_ambito.id_ruolo</code>.
     */
    public Integer getIdRuolo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.ruolo_ambito.id_ambito</code>.
     */
    public void setIdAmbito(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.ruolo_ambito.id_ambito</code>.
     */
    public Integer getIdAmbito() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.ruolo_ambito.note</code>.
     */
    public void setNote(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.ruolo_ambito.note</code>.
     */
    public String getNote() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RuoloAmbitoRecord
     */
    public RuoloAmbitoRecord() {
        super(RuoloAmbito.RUOLO_AMBITO);
    }

    /**
     * Create a detached, initialised RuoloAmbitoRecord
     */
    public RuoloAmbitoRecord(Integer idruoloAmbito, Integer idRuolo, Integer idAmbito, String note) {
        super(RuoloAmbito.RUOLO_AMBITO);

        setIdruoloAmbito(idruoloAmbito);
        setIdRuolo(idRuolo);
        setIdAmbito(idAmbito);
        setNote(note);
        resetChangedOnNotNull();
    }
}
