/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.TipoProcProgressivo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TipoProcProgressivoRecord extends UpdatableRecordImpl<TipoProcProgressivoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.tipo_proc_progressivo.id_tipo_proc</code>.
     */
    public void setIdTipoProc(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.tipo_proc_progressivo.id_tipo_proc</code>.
     */
    public Integer getIdTipoProc() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.tipo_proc_progressivo.progressivo</code>.
     */
    public void setProgressivo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.tipo_proc_progressivo.progressivo</code>.
     */
    public Integer getProgressivo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.tipo_proc_progressivo.formato</code>.
     */
    public void setFormato(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.tipo_proc_progressivo.formato</code>.
     */
    public String getFormato() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TipoProcProgressivoRecord
     */
    public TipoProcProgressivoRecord() {
        super(TipoProcProgressivo.TIPO_PROC_PROGRESSIVO);
    }

    /**
     * Create a detached, initialised TipoProcProgressivoRecord
     */
    public TipoProcProgressivoRecord(Integer idTipoProc, Integer progressivo, String formato) {
        super(TipoProcProgressivo.TIPO_PROC_PROGRESSIVO);

        setIdTipoProc(idTipoProc);
        setProgressivo(progressivo);
        setFormato(formato);
        resetChangedOnNotNull();
    }
}
