/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.Uffici;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UfficiRecord extends UpdatableRecordImpl<UfficiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.uffici.id_ufficio</code>.
     */
    public void setIdUfficio(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.uffici.id_ufficio</code>.
     */
    public Integer getIdUfficio() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.uffici.attivo</code>.
     */
    public void setAttivo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.uffici.attivo</code>.
     */
    public Integer getAttivo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.uffici.ufficio</code>.
     */
    public void setUfficio(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.uffici.ufficio</code>.
     */
    public String getUfficio() {
        return (String) get(2);
    }

    /**
     * Setter for <code>decreti.uffici.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.uffici.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.uffici.id_ufficio_sovraordinato</code>.
     */
    public void setIdUfficioSovraordinato(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.uffici.id_ufficio_sovraordinato</code>.
     */
    public Integer getIdUfficioSovraordinato() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>decreti.uffici.data_disattivazione</code>.
     */
    public void setDataDisattivazione(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.uffici.data_disattivazione</code>.
     */
    public LocalDateTime getDataDisattivazione() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>decreti.uffici.note</code>.
     */
    public void setNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.uffici.note</code>.
     */
    public String getNote() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UfficiRecord
     */
    public UfficiRecord() {
        super(Uffici.UFFICI);
    }

    /**
     * Create a detached, initialised UfficiRecord
     */
    public UfficiRecord(Integer idUfficio, Integer attivo, String ufficio, Integer idUtente, Integer idUfficioSovraordinato, LocalDateTime dataDisattivazione, String note) {
        super(Uffici.UFFICI);

        setIdUfficio(idUfficio);
        setAttivo(attivo);
        setUfficio(ufficio);
        setIdUtente(idUtente);
        setIdUfficioSovraordinato(idUfficioSovraordinato);
        setDataDisattivazione(dataDisattivazione);
        setNote(note);
        resetTouchedOnNotNull();
    }
}
