/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.VAssegnantiAttivi;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VAssegnantiAttiviRecord extends TableRecordImpl<VAssegnantiAttiviRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_tipo_proc_ass</code>.
     */
    public void setIdTipoProcAss(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_tipo_proc_ass</code>.
     */
    public Integer getIdTipoProcAss() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_tipo_proc</code>.
     */
    public void setIdTipoProc(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_tipo_proc</code>.
     */
    public Integer getIdTipoProc() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_ruolo</code>.
     */
    public void setIdRuolo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_ruolo</code>.
     */
    public Integer getIdRuolo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_ufficio</code>.
     */
    public void setIdUfficio(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_ufficio</code>.
     */
    public Integer getIdUfficio() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_utente_assegnante</code>.
     */
    public void setIdUtenteAssegnante(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_utente_assegnante</code>.
     */
    public Integer getIdUtenteAssegnante() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.id_delegante</code>.
     */
    public void setIdDelegante(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.id_delegante</code>.
     */
    public Integer getIdDelegante() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.autorizzazioni</code>.
     */
    public void setAutorizzazioni(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.autorizzazioni</code>.
     */
    public String getAutorizzazioni() {
        return (String) get(7);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.data_assegnazione</code>.
     */
    public void setDataAssegnazione(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.data_assegnazione</code>.
     */
    public LocalDateTime getDataAssegnazione() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.data_rimozione</code>.
     */
    public void setDataRimozione(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.data_rimozione</code>.
     */
    public LocalDateTime getDataRimozione() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.dataora</code>.
     */
    public void setDataora(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.dataora</code>.
     */
    public LocalDateTime getDataora() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>decreti.v_assegnanti_attivi.note</code>.
     */
    public void setNote(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>decreti.v_assegnanti_attivi.note</code>.
     */
    public String getNote() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VAssegnantiAttiviRecord
     */
    public VAssegnantiAttiviRecord() {
        super(VAssegnantiAttivi.V_ASSEGNANTI_ATTIVI);
    }

    /**
     * Create a detached, initialised VAssegnantiAttiviRecord
     */
    public VAssegnantiAttiviRecord(Integer idTipoProcAss, Integer idTipoProc, Integer idUtente, Integer idRuolo, Integer idUfficio, Integer idUtenteAssegnante, Integer idDelegante, String autorizzazioni, LocalDateTime dataAssegnazione, LocalDateTime dataRimozione, LocalDateTime dataora, String note) {
        super(VAssegnantiAttivi.V_ASSEGNANTI_ATTIVI);

        setIdTipoProcAss(idTipoProcAss);
        setIdTipoProc(idTipoProc);
        setIdUtente(idUtente);
        setIdRuolo(idRuolo);
        setIdUfficio(idUfficio);
        setIdUtenteAssegnante(idUtenteAssegnante);
        setIdDelegante(idDelegante);
        setAutorizzazioni(autorizzazioni);
        setDataAssegnazione(dataAssegnazione);
        setDataRimozione(dataRimozione);
        setDataora(dataora);
        setNote(note);
        resetChangedOnNotNull();
    }
}
