/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.VOrd100Decretati;

import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VOrd100DecretatiRecord extends TableRecordImpl<VOrd100DecretatiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.v_ord100_decretati.ID_Pratica</code>.
     */
    public void setIdPratica(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.v_ord100_decretati.ID_Pratica</code>.
     */
    public Integer getIdPratica() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>decreti.v_ord100_decretati.data_ora_provvedimento</code>.
     */
    public void setDataOraProvvedimento(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>decreti.v_ord100_decretati.data_ora_provvedimento</code>.
     */
    public LocalDate getDataOraProvvedimento() {
        return (LocalDate) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VOrd100DecretatiRecord
     */
    public VOrd100DecretatiRecord() {
        super(VOrd100Decretati.V_ORD100_DECRETATI);
    }

    /**
     * Create a detached, initialised VOrd100DecretatiRecord
     */
    public VOrd100DecretatiRecord(Integer idPratica, LocalDate dataOraProvvedimento) {
        super(VOrd100Decretati.V_ORD100_DECRETATI);

        setIdPratica(idPratica);
        setDataOraProvvedimento(dataOraProvvedimento);
        resetChangedOnNotNull();
    }
}
