/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.VRuoliutenteAttivi;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VRuoliutenteAttiviRecord extends TableRecordImpl<VRuoliutenteAttiviRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.v_ruoliutente_attivi.id_ruoli_utente</code>.
     */
    public void setIdRuoliUtente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.v_ruoliutente_attivi.id_ruoli_utente</code>.
     */
    public Integer getIdRuoliUtente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.v_ruoliutente_attivi.id_ruolo</code>.
     */
    public void setIdRuolo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.v_ruoliutente_attivi.id_ruolo</code>.
     */
    public Integer getIdRuolo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.v_ruoliutente_attivi.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.v_ruoliutente_attivi.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.v_ruoliutente_attivi.id_ufficio</code>.
     */
    public void setIdUfficio(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.v_ruoliutente_attivi.id_ufficio</code>.
     */
    public Integer getIdUfficio() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.v_ruoliutente_attivi.data_inizio</code>.
     */
    public void setDataInizio(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.v_ruoliutente_attivi.data_inizio</code>.
     */
    public LocalDateTime getDataInizio() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>decreti.v_ruoliutente_attivi.data_fine</code>.
     */
    public void setDataFine(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.v_ruoliutente_attivi.data_fine</code>.
     */
    public LocalDateTime getDataFine() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VRuoliutenteAttiviRecord
     */
    public VRuoliutenteAttiviRecord() {
        super(VRuoliutenteAttivi.V_RUOLIUTENTE_ATTIVI);
    }

    /**
     * Create a detached, initialised VRuoliutenteAttiviRecord
     */
    public VRuoliutenteAttiviRecord(Integer idRuoliUtente, Integer idRuolo, Integer idUtente, Integer idUfficio, LocalDateTime dataInizio, LocalDateTime dataFine) {
        super(VRuoliutenteAttivi.V_RUOLIUTENTE_ATTIVI);

        setIdRuoliUtente(idRuoliUtente);
        setIdRuolo(idRuolo);
        setIdUtente(idUtente);
        setIdUfficio(idUfficio);
        setDataInizio(dataInizio);
        setDataFine(dataFine);
        resetTouchedOnNotNull();
    }
}
