/*
 * This file is generated by jOOQ.
 */
package it.usr.web.usromniapp.domain.tables.records;


import it.usr.web.usromniapp.domain.tables.VUtentiAttivi;

import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VUtentiAttiviRecord extends TableRecordImpl<VUtentiAttiviRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>decreti.v_utenti_attivi.id_utente</code>.
     */
    public void setIdUtente(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.id_utente</code>.
     */
    public Integer getIdUtente() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.id_gruppo</code>.
     */
    public void setIdGruppo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.id_gruppo</code>.
     */
    public Integer getIdGruppo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.id_ambito</code>.
     */
    public void setIdAmbito(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.id_ambito</code>.
     */
    public Integer getIdAmbito() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.id_ruolo_predefinito</code>.
     */
    public void setIdRuoloPredefinito(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.id_ruolo_predefinito</code>.
     */
    public Integer getIdRuoloPredefinito() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.attivo</code>.
     */
    public void setAttivo(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.attivo</code>.
     */
    public Integer getAttivo() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.utente_fisico</code>.
     */
    public void setUtenteFisico(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.utente_fisico</code>.
     */
    public Integer getUtenteFisico() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.matricola</code>.
     */
    public void setMatricola(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.matricola</code>.
     */
    public String getMatricola() {
        return (String) get(6);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.nome_utente</code>.
     */
    public void setNomeUtente(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.nome_utente</code>.
     */
    public String getNomeUtente() {
        return (String) get(7);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.utente</code>.
     */
    public void setUtente(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.utente</code>.
     */
    public String getUtente() {
        return (String) get(8);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.utente_pigrego</code>.
     */
    public void setUtentePigrego(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.utente_pigrego</code>.
     */
    public String getUtentePigrego() {
        return (String) get(9);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.password</code>.
     */
    public void setPassword(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.password</code>.
     */
    public String getPassword() {
        return (String) get(10);
    }

    /**
     * Setter for <code>decreti.v_utenti_attivi.data_scadenza_password</code>.
     */
    public void setDataScadenzaPassword(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>decreti.v_utenti_attivi.data_scadenza_password</code>.
     */
    public LocalDate getDataScadenzaPassword() {
        return (LocalDate) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VUtentiAttiviRecord
     */
    public VUtentiAttiviRecord() {
        super(VUtentiAttivi.V_UTENTI_ATTIVI);
    }

    /**
     * Create a detached, initialised VUtentiAttiviRecord
     */
    public VUtentiAttiviRecord(Integer idUtente, Integer idGruppo, Integer idAmbito, Integer idRuoloPredefinito, Integer attivo, Integer utenteFisico, String matricola, String nomeUtente, String utente, String utentePigrego, String password, LocalDate dataScadenzaPassword) {
        super(VUtentiAttivi.V_UTENTI_ATTIVI);

        setIdUtente(idUtente);
        setIdGruppo(idGruppo);
        setIdAmbito(idAmbito);
        setIdRuoloPredefinito(idRuoloPredefinito);
        setAttivo(attivo);
        setUtenteFisico(utenteFisico);
        setMatricola(matricola);
        setNomeUtente(nomeUtente);
        setUtente(utente);
        setUtentePigrego(utentePigrego);
        setPassword(password);
        setDataScadenzaPassword(dataScadenzaPassword);
        resetTouchedOnNotNull();
    }
}
